# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: StirlingTools.StirlingPDF
PackageVersion: 2.8.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
