package stirling.software.proprietary.security.model.api;

import io.swagger.v3.oas.annotations.media.Schema;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import stirling.software.common.model.api.GeneralFile;

// TODO: Migration required - dropped @ConditionalOnProperty("mail.enabled"). This is a request
// DTO, not a CDI bean, so conditional bean registration does not apply. The mail.enabled gate must
// be enforced on the consuming endpoint/service (e.g. via @IfBuildProfile / LookupIfProperty or a
// runtime guard on the email controller), not on this model.
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class Email extends GeneralFile {

    @Schema(
            description = "The recipient's email address",
            requiredMode = Schema.RequiredMode.REQUIRED,
            format = "email")
    private String to;

    @Schema(
            description = "The subject of the email",
            defaultValue = "Stirling Software PDF Notification",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    private String subject;

    @Schema(
            description = "The body of the email",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED,
            defaultValue =
                    "This message was automatically generated by Stirling-PDF, an innovative"
                            + " solution from Stirling Software. For more information, visit our <a"
                            + " href=\"https://stirling-software.com\">website</a>.<br><br>Please do"
                            + " not reply directly to this email.")
    private String body;
}
