# Build jbig2enc in a separate stage
FROM bellsoft/liberica-openjdk-alpine:17

# Copy the application JAR file
COPY build/libs/*.jar app.jar

# Expose the application port
EXPOSE 8080

# Set environment variables
ENV GROUPS_TO_REMOVE=LibreOffice,CLI

# Run the application
CMD ["java", "-jar", "/app.jar"]
