import type { IconName } from "@app/ui/Icon";

/** Icon palette for saved automations and watched folders. The KEYS are
 * persisted (e.g. "SettingsIcon"), so only the values may change. */
export const iconMap: Record<string, IconName> = {
  SettingsIcon: "settings",
  CompressIcon: "shrink",
  SwapHorizIcon: "arrow-left-right",
  CleaningServicesIcon: "brush-cleaning",
  CropIcon: "crop",
  TextFieldsIcon: "type",
  PictureAsPdfIcon: "file-text",
  EditIcon: "pencil",
  DeleteIcon: "trash",
  FolderIcon: "folder",
  CloudIcon: "cloud",
  StorageIcon: "server",
  SearchIcon: "search",
  DownloadIcon: "download",
  UploadIcon: "upload",
  PlayArrowIcon: "play",
  RotateLeftIcon: "rotate-ccw",
  RotateRightIcon: "rotate-cw",
  VisibilityIcon: "eye",
  ContentCutIcon: "scissors",
  ContentCopyIcon: "copy",
  WorkIcon: "briefcase",
  BuildIcon: "wrench",
  AutoAwesomeIcon: "sparkles",
  SmartToyIcon: "bot",
  CheckIcon: "check",
  SecurityIcon: "shield-check",
  StarIcon: "star",
};

export const iconOptions = [
  { value: "SettingsIcon", label: "Settings" },
  { value: "CompressIcon", label: "Compress" },
  { value: "SwapHorizIcon", label: "Convert" },
  { value: "CleaningServicesIcon", label: "Clean" },
  { value: "CropIcon", label: "Crop" },
  { value: "TextFieldsIcon", label: "Text" },
  { value: "PictureAsPdfIcon", label: "PDF" },
  { value: "EditIcon", label: "Edit" },
  { value: "DeleteIcon", label: "Delete" },
  { value: "FolderIcon", label: "Folder" },
  { value: "CloudIcon", label: "Cloud" },
  { value: "StorageIcon", label: "Storage" },
  { value: "SearchIcon", label: "Search" },
  { value: "DownloadIcon", label: "Download" },
  { value: "UploadIcon", label: "Upload" },
  { value: "PlayArrowIcon", label: "Play" },
  { value: "RotateLeftIcon", label: "Rotate Left" },
  { value: "RotateRightIcon", label: "Rotate Right" },
  { value: "VisibilityIcon", label: "View" },
  { value: "ContentCutIcon", label: "Cut" },
  { value: "ContentCopyIcon", label: "Copy" },
  { value: "WorkIcon", label: "Work" },
  { value: "BuildIcon", label: "Build" },
  { value: "AutoAwesomeIcon", label: "Magic" },
  { value: "SmartToyIcon", label: "Robot" },
  { value: "CheckIcon", label: "Check" },
  { value: "SecurityIcon", label: "Security" },
  { value: "StarIcon", label: "Star" },
];

export type IconKey = keyof typeof iconMap;
