FROM alpine:3.20.2

ARG PYMUPDF_VERSION

RUN apk upgrade --no-cache -a && \
    apk add --no-cache python3 \
    py3-pip \
    musl-dev \
    jpeg-dev \
    zlib-dev \
    freetype-dev \
    clang \
    clang-dev \
    llvm \
    m4 \
    cmake \
    python3-dev \
    build-base \
    swig \
    git

WORKDIR /tmp

# Erstelle und aktiviere ein virtuelles Umfeld
RUN <<EOF
    pip install --break-system-packages libclang
    wget https://github.com/pymupdf/PyMuPDF/archive/refs/tags/$PYMUPDF_VERSION.tar.gz
    tar -xvf $PYMUPDF_VERSION.tar.gz
    cd PyMuPDF-$PYMUPDF_VERSION
    PYMUPDF_SETUP_MUPDF_TESSERACT=0 python3 setup.py install
    cd ..
    rm -rf PyMuPDF-$PYMUPDF_VERSION $PYMUPDF_VERSION.tar.gz  # Clean up
EOF

WORKDIR /

RUN apk del \
    clang \
    clang-dev \
    llvm \
    m4 \
    cmake \
    build-base \
    python3-dev \
    swig \
    git
