// Broad-corpus accuracy gate for the heuristic engine: one realistic specimen per common document
// type, asserted on the REAL engine + rules pack. Text is written the way such documents actually
// read (not keyword-stuffed), so additions to the rules pack are validated against natural prose.

import { beforeAll, describe, expect, it } from "vitest";
import {
  classifyHeuristic,
  ensureRulesLoaded,
} from "@app/services/heuristic/heuristicEngine";
import type { HeuristicDoc } from "@app/services/heuristic/types";

beforeAll(async () => {
  await ensureRulesLoaded();
});

interface Case {
  /** Expected top label; "" asserts the document stays unlabelled. */
  expect: string;
  file: string;
  pages?: number;
  /** Replace every space with U+00A0, as some pdf.js text layers do. */
  nbsp?: boolean;
  title: string;
  body: string[];
}

const run = (c: Case) => {
  let body = c.body.join("\n");
  let title = c.title;
  if (c.nbsp) {
    body = body.replace(/ /g, "\u00A0");
    title = title.replace(/ /g, "\u00A0");
  }
  const doc: HeuristicDoc = {
    fileName: c.file,
    pageCount: c.pages ?? 1,
    meta: {},
    titleZone: title,
    firstZone: body,
    allZone: body,
  };
  return classifyHeuristic(doc);
};

const CASES: Case[] = [
  {
    expect: "invoice",
    file: "2024-014.pdf",
    title: "Invoice",
    body: [
      "Invoice",
      "Jane Mills Design, 14 Fern Road, Bristol BS1 5TR",
      "Invoice #: 2024-014    Date: 3 May 2024",
      "Bill To: Harbour Cafe Ltd",
      "Logo refresh and brand guidelines ... $950.00",
      "Menu redesign (2 rounds) ... $250.00",
      "Total: $1,200.00",
      "Payment terms: Net 30. Bank transfer to sort code 20-00-00, account 55667788.",
    ],
  },
  {
    expect: "receipt",
    file: "20240506_183212.pdf",
    title: "Greenway Grocers",
    body: [
      "Greenway Grocers",
      "112 Station Road    06/05/2024 18:32",
      "Oat milk 1L            2.20",
      "Sourdough loaf         3.80",
      "Free range eggs x12    4.10",
      "TOTAL                 10.10",
      "VISA ****4421   Contactless",
      "Approval code: 08841",
      "Thank you for shopping with us",
    ],
  },
  {
    expect: "bank-statement",
    file: "statement_march.pdf",
    pages: 3,
    title: "Your account statement",
    body: [
      "Your account statement",
      "Statement period: 1 March 2024 - 31 March 2024",
      "Sort code: 40-12-31    Account number: 71002233",
      "Opening balance                          2,140.55",
      "2 Mar   Faster payment - RENT            -950.00",
      "5 Mar   Salary ACME LTD                 +2,850.00",
      "12 Mar  Direct debit - CITY POWER         -84.20",
      "19 Mar  Card purchase - GREENWAY          -10.10",
      "Closing balance                          3,946.25",
      "Money in: 2,850.00    Money out: 1,044.30",
    ],
  },
  {
    expect: "statement-of-account",
    file: "april_card.pdf",
    pages: 2,
    title: "Monthly statement",
    body: [
      "Monthly statement",
      "Account ending in 8891",
      "Previous balance: $412.90    New balance: $388.15",
      "Minimum payment due: $25.00    Payment due date: 28 April 2024",
      "Credit limit: $4,500    Available credit: $4,111.85",
      "Annual percentage rate (APR): 22.9% variable",
      "Late payment warning: if we do not receive your minimum payment by the date listed above,",
      "you may have to pay a late fee of up to $39.",
      "Interest charge calculation: your APR is applied to the daily balance.",
    ],
  },
  {
    expect: "purchase-order",
    file: "PO-88412.pdf",
    title: "Purchase Order",
    body: [
      "Purchase Order",
      "P.O. Number: PO-88412    Date: 11 June 2024",
      "Vendor: Brightline Packaging Ltd",
      "Ship To: Unit 4, Riverside Industrial Estate, Leeds LS10 1AB",
      "Qty Ordered   Description                Unit Price",
      "500           Corrugated boxes 40x30cm   0.85",
      "200           Kraft void fill rolls      3.20",
      "Delivery date: on or before 25 June 2024.",
      "All invoices must quote the PO number. No PO, no pay.",
    ],
  },
  {
    expect: "quote",
    file: "landscaping_quote.pdf",
    title: "Quotation",
    body: [
      "Quotation",
      "Quotation number: Q-2231    Date: 8 April 2024",
      "Prepared for: Mr and Mrs Aldridge",
      "We are pleased to quote for the following garden works:",
      "Re-turf rear lawn (85 sqm) ... 1,540.00",
      "Patio pressure wash and re-point ... 380.00",
      "Total (inc VAT): 1,920.00",
      "This quote is valid for 30 days from the date above.",
    ],
  },
  {
    expect: "expense-report",
    file: "march_expenses.pdf",
    title: "Expense report",
    body: [
      "Expense report",
      "Employee: D. Okafor    Department: Field Sales",
      "Period: 1-31 March 2024",
      "04 Mar  Client lunch, Manchester        38.50",
      "11 Mar  Rail ticket, London return      86.00",
      "18 Mar  Hotel, 1 night (conference)    129.00",
      "Per diem (2 days)                       90.00",
      "Total reimbursable: 343.50",
      "Receipts attached. Approved by: S. Hughes",
    ],
  },
  {
    expect: "payslip",
    file: "payslip_2024_05.pdf",
    title: "Payslip",
    body: [
      "Payslip",
      "Employee: R. Patel    Employee no: 00482    Pay date: 31 May 2024",
      "Payments                       Deductions",
      "Basic pay      2,916.67        PAYE tax        382.40",
      "                               National Insurance 231.15",
      "                               Pension (5%)    145.83",
      "Gross pay: 2,916.67            Net pay: 2,157.29",
      "Tax code: 1257L    NI category: A",
      "Year to date: gross 14,583.35, tax 1,912.00",
    ],
  },
  {
    expect: "tax-form",
    file: "W2_2023.pdf",
    title: "Wage and Tax Statement",
    body: [
      "Form W-2 Wage and Tax Statement 2023",
      "Employer: Lakeshore Analytics Inc, EIN 84-2210043",
      "Employee: M. Torres    SSN XXX-XX-4821",
      "1 Wages, tips, other compensation   72,450.00",
      "2 Federal income tax withheld        9,812.00",
      "3 Social security wages             72,450.00",
      "4 Social security tax withheld       4,491.90",
      "5 Medicare wages and tips           72,450.00",
      "Copy B - to be filed with employee's federal tax return.",
    ],
  },
  {
    expect: "nda",
    file: "acme_nda_signed.pdf",
    pages: 4,
    title: "Non-Disclosure Agreement",
    body: [
      "Non-Disclosure Agreement",
      "This Agreement is made between Acme Ltd (the Disclosing Party) and the undersigned",
      "recipient (the Receiving Party).",
      "1. The Receiving Party shall hold all Confidential Information in strict confidence.",
      "2. Confidential Information excludes information that is or becomes publicly available.",
      "3. This Agreement shall remain in force for five years from the date of signature.",
      "Signed for and on behalf of the parties:",
    ],
  },
  {
    expect: "contract",
    file: "signed_agreement_final_v3.pdf",
    pages: 9,
    title: "Agreement",
    body: [
      "Agreement",
      "This Agreement is entered into as of 1 July 2024 between Corven Holdings Ltd and",
      "Meridian Supplies Ltd.",
      "WITNESSETH: in consideration of the mutual covenants contained herein, the parties",
      "agree as follows:",
      "1. Definitions. Capitalised terms have the meanings set out in Schedule 1.",
      "5. Limitation of liability. Neither party shall be liable for indirect losses.",
      "9. Entire agreement. This Agreement constitutes the entire agreement between the parties.",
      "IN WITNESS WHEREOF the parties have executed this Agreement.",
    ],
  },
  {
    expect: "employment-contract",
    file: "contract_r_patel.pdf",
    pages: 7,
    title: "Contract of Employment",
    body: [
      "Contract of Employment",
      "This contract of employment is made between Northgate Logistics Ltd (the Employer)",
      "and R. Patel (the Employee).",
      "1. Commencement. Your employment begins on 2 September 2024.",
      "2. Probationary period. The first six months are a probationary period.",
      "3. Hours. The Employee shall work 37.5 hours per week.",
      "4. Holiday. 25 days per annum plus public holidays.",
      "5. Notice. Either party may terminate on eight weeks written notice.",
    ],
  },
  {
    expect: "lease-agreement",
    file: "flat2_tenancy.pdf",
    pages: 12,
    title: "Assured Shorthold Tenancy Agreement",
    body: [
      "Assured Shorthold Tenancy Agreement",
      "Property: Flat 2, 18 Camden Row, London NW1 8QP",
      "Landlord: H. Berger    Tenant: L. Novak",
      "Term: 12 months commencing 1 August 2024",
      "Rent: 1,650 per calendar month, payable in advance",
      "Security deposit: 1,903.85, protected with the Deposit Protection Service",
      "The tenant shall not sublet the property without written consent.",
    ],
  },
  {
    expect: "terms-and-conditions",
    file: "tos.pdf",
    pages: 14,
    title: "Terms of Service",
    body: [
      "Terms of Service",
      "Last updated: 12 February 2024",
      "By accessing or using the Kestrel platform you agree to be bound by these terms.",
      "1. Your account. You are responsible for safeguarding your credentials.",
      "2. Acceptable use. You must not misuse the services or interfere with their operation.",
      "3. Termination. We may suspend or terminate access for breach of these terms.",
      "4. Disclaimers. The services are provided on an as-is basis.",
    ],
  },
  {
    expect: "privacy-policy",
    file: "privacy.pdf",
    pages: 8,
    title: "Privacy Notice",
    body: [
      "Privacy Notice",
      "This notice explains how Kestrel Ltd, as data controller, handles your information.",
      "Personal data we collect: account details, usage data, and support correspondence.",
      "How we use your information: to provide the service, for billing, and for security.",
      "Your rights include access, rectification, and the right to erasure.",
      "We retain personal data only as long as necessary for the purposes described.",
      "Contact our data protection officer at privacy@kestrel.example.",
    ],
  },
  {
    expect: "will",
    file: "last_will.pdf",
    pages: 5,
    title: "Last Will and Testament",
    body: [
      "Last Will and Testament",
      "I, Margaret Ellen Shaw, being of sound mind, declare this to be my last will and",
      "testament, revoking all former wills.",
      "1. I appoint my daughter, C. Shaw, as executor of this will.",
      "2. I give, devise and bequeath my residuary estate to my children in equal shares,",
      "per stirpes.",
      "Signed by the testator in our presence, who in her presence signed as witnesses.",
    ],
  },
  {
    expect: "power-of-attorney",
    file: "lpa_finance.pdf",
    pages: 10,
    title: "Lasting Power of Attorney",
    body: [
      "Lasting Power of Attorney",
      "Property and financial affairs",
      "Donor: A. Whitfield    Attorney: J. Whitfield",
      "I appoint my attorney to make decisions about my property and financial affairs.",
      "This lasting power of attorney is registered with the Office of the Public Guardian.",
      "Certificate provider statement: the donor understands the purpose of this LPA.",
    ],
  },
  {
    expect: "resume",
    file: "john_smith.pdf",
    pages: 2,
    title: "JOHN SMITH",
    body: [
      "JOHN SMITH",
      "Software Engineer | San Francisco, CA | john.smith@example.com | linkedin.com/in/jsmith",
      "EXPERIENCE",
      "Senior Software Engineer, Meridian Labs    2021 - Present",
      "- Led a team of four building a real-time analytics pipeline handling 2B events/day",
      "- Cut infrastructure spend 30% by consolidating streaming services",
      "Software Engineer, Halcyon Systems    2017 - 2021",
      "- Shipped the customer-facing dashboard used by 40k monthly users",
      "EDUCATION",
      "B.S. Computer Science, University of Washington, 2017",
      "SKILLS",
      "Go, TypeScript, Kubernetes, PostgreSQL, Kafka",
    ],
  },
  {
    expect: "cover-letter",
    file: "application_kestrel.pdf",
    title: "Application for Product Designer",
    body: [
      "Dear Hiring Manager,",
      "I am writing to apply for the Product Designer role advertised on your careers page.",
      "In my current position at Fieldnote I redesigned the onboarding flow, lifting",
      "activation by 22%, and I run our fortnightly usability testing programme.",
      "Kestrel's focus on accessible tools is why I am excited to apply; my portfolio",
      "includes two WCAG AA redesigns shipped end to end.",
      "Thank you for considering my application. I look forward to the opportunity to",
      "discuss how I can contribute.",
      "Yours sincerely, Amara Diallo",
    ],
  },
  {
    expect: "offer-letter",
    file: "kestrel_offer.pdf",
    title: "Offer of Employment",
    body: [
      "Offer of Employment",
      "Dear Amara,",
      "We are pleased to offer you the position of Product Designer at Kestrel Ltd.",
      "Your start date will be 7 October 2024, and your annual base salary will be 68,000.",
      "This offer is contingent on satisfactory references and right-to-work checks.",
      "To accept this offer, please sign and return a copy of this letter by 20 September.",
      "We look forward to welcoming you to the team.",
    ],
  },
  {
    expect: "reference-letter",
    file: "reference_adiallo.pdf",
    title: "Letter of Recommendation",
    body: [
      "Letter of Recommendation",
      "To whom it may concern,",
      "It is my pleasure to recommend Amara Diallo, who reported to me for three years",
      "at Fieldnote as a product designer.",
      "Amara combines rigorous research habits with fast, pragmatic delivery; her",
      "onboarding redesign became the template for the rest of the product.",
      "I highly recommend her without reservation. Please contact me with any questions.",
      "Daniel Reyes, Head of Design, Fieldnote",
    ],
  },
  {
    expect: "job-description",
    file: "jd_platform_eng.pdf",
    title: "Senior Platform Engineer",
    body: [
      "Senior Platform Engineer",
      "About the role",
      "We are seeking a senior engineer to own our deployment platform and developer",
      "tooling, reporting to the Head of Infrastructure.",
      "Responsibilities",
      "- Operate and evolve the Kubernetes-based delivery pipeline",
      "Required qualifications",
      "- 5+ years running production cloud infrastructure",
      "Preferred qualifications",
      "- Experience with progressive delivery and service meshes",
    ],
  },
  {
    expect: "performance-review",
    file: "h2_review_jsmith.pdf",
    title: "Performance Review",
    body: [
      "Performance Review - H2 2024",
      "Employee: J. Smith    Reviewer: T. Nguyen    Role: Senior Engineer",
      "Overall rating: exceeds expectations",
      "Strengths: consistently unblocks the team; the analytics migration landed a",
      "quarter early with zero data loss.",
      "Areas for improvement: delegate more of the operational load; invest in",
      "documenting decisions for newer engineers.",
      "Goals for next period: lead the multi-region rollout; mentor two engineers.",
    ],
  },
  {
    expect: "timesheet",
    file: "week_22_hours.pdf",
    title: "Timesheet",
    body: [
      "Timesheet",
      "Employee: K. Osei    Week ending: 31 May 2024",
      "Mon 7.50    Tue 7.50    Wed 8.00    Thu 7.50    Fri 6.00",
      "Regular hours: 36.50",
      "Overtime hours: 0.00",
      "Total hours: 36.50",
      "Employee signature: ____________    Approved by: L. Grant",
    ],
  },
  {
    expect: "meeting-minutes",
    file: "board_minutes_may.pdf",
    pages: 3,
    title: "Minutes of the Meeting",
    body: [
      "Minutes of the Meeting of the Facilities Committee",
      "Held 14 May 2024, Committee Room B. Present: R. Holt (chair), five members.",
      "Apologies for absence: D. Cole.",
      "The meeting was called to order at 18:05. A quorum was present.",
      "Matters arising: the roofing tender shortlist was approved. Motion carried.",
      "Any other business: none.",
      "Date of next meeting: 11 June 2024. The meeting adjourned at 19:20.",
    ],
  },
  {
    expect: "meeting-agenda",
    file: "agenda_11june.pdf",
    title: "Meeting Agenda",
    body: [
      "Meeting Agenda",
      "Facilities Committee - 11 June 2024, 18:00, Committee Room B",
      "1. Call to order and apologies for absence",
      "2. Adoption of the agenda",
      "3. Approval of minutes of the previous meeting",
      "4. Agenda item: roofing contract award",
      "5. Agenda item: car park resurfacing budget",
      "6. Any other business",
      "7. Date of next meeting",
    ],
  },
  {
    expect: "memo",
    file: "memo_hybrid_policy.pdf",
    title: "Memorandum",
    body: [
      "Memorandum",
      "To: All staff    From: Operations    Date: 3 June 2024",
      "Re: Updated hybrid working arrangements",
      "Effective 1 July, core in-office days move to Tuesday through Thursday.",
      "Team leads may approve exceptions for caregiving or medical needs.",
      "Desk booking opens each Thursday for the following week.",
      "Questions to operations@corven.example.",
    ],
  },
  {
    expect: "press-release",
    file: "kestrel_series_b.pdf",
    title: "FOR IMMEDIATE RELEASE",
    body: [
      "FOR IMMEDIATE RELEASE",
      "Kestrel raises $40M Series B to expand accessible design tooling",
      "LONDON, 4 June 2024 - Kestrel Ltd today announced a $40 million Series B round",
      "led by Meridian Growth, with participation from existing investors.",
      "The funding will accelerate hiring and the launch of Kestrel's audit platform.",
      '"Accessibility is still an afterthought in most tooling," said CEO N. Okafor.',
      "Media contact: press@kestrel.example    Notes to editors: photography available.",
    ],
  },
  {
    expect: "newsletter",
    file: "parish_news_june.pdf",
    pages: 4,
    title: "The Elmswell Bulletin",
    body: [
      "The Elmswell Bulletin - June edition",
      "In this issue: the summer fete returns, allotment news, and a new cafe on the green.",
      "From the editor: thank you to everyone who volunteered at the spring clean-up.",
      "Dates for your diary: 15 June - summer fete; 22 June - open gardens.",
      "Allotment corner: plots 12 and 14 are available; contact the parish office.",
      "Next month we profile the new head teacher at Elmswell Primary.",
    ],
  },
  {
    expect: "white-paper",
    file: "zero_trust_wp.pdf",
    pages: 16,
    title: "Zero Trust in Practice",
    body: [
      "Zero Trust in Practice",
      "A white paper on migrating enterprise networks beyond the perimeter model.",
      "Executive summary",
      "This white paper examines the operational realities of zero-trust rollouts across",
      "three sectors, drawing on 40 practitioner interviews.",
      "Key findings: phased device-trust rollouts outperform big-bang migrations; identity",
      "debt is the leading cause of stalled programmes.",
      "Conclusions and recommendations follow in section 6.",
    ],
  },
  {
    expect: "case-study",
    file: "meridian_case_study.pdf",
    pages: 3,
    title: "Customer Case Study",
    body: [
      "Customer Case Study",
      "How Meridian Logistics cut fleet downtime by 34% with Kestrel Audit",
      "About the client: Meridian operates 1,200 vehicles across the UK and Ireland.",
      "The challenge: paper-based inspections meant defects surfaced days late.",
      "The solution: digital inspections with automated triage and parts ordering.",
      "The results: downtime fell 34% in six months; audit prep time fell from three",
      "weeks to two days.",
      '"It paid for itself in a quarter," said the fleet director.',
    ],
  },
  {
    expect: "financial-statement",
    file: "annual_accounts_2023.pdf",
    pages: 42,
    title: "Consolidated Financial Statements",
    body: [
      "Consolidated Financial Statements",
      "For the year ended 31 December 2023",
      "Independent auditor's report to the members of Corven Holdings plc",
      "Consolidated statement of financial position",
      "Consolidated statement of cash flows",
      "Notes to the financial statements",
      "1. Basis of preparation. These statements are prepared under IFRS.",
      "Revenue for the year was 84.2m (2022: 71.9m).",
    ],
  },
  {
    expect: "budget",
    file: "fy25_operating_budget.pdf",
    pages: 6,
    title: "FY25 Operating Budget",
    body: [
      "FY25 Operating Budget",
      "Department: Product Engineering",
      "Budget vs actual, FY24, and proposed FY25 allocations",
      "Headcount            FY24 actual 3.2m    FY25 budget 3.6m",
      "Cloud infrastructure FY24 actual 1.1m    FY25 budget 1.0m",
      "Tooling and licences FY24 actual 0.3m    FY25 budget 0.4m",
      "The rolling forecast is updated quarterly; variances above 10% require sign-off.",
    ],
  },
  {
    expect: "insurance-policy",
    file: "home_policy_renewal.pdf",
    pages: 18,
    title: "Your Home Insurance Policy",
    body: [
      "Your Home Insurance Policy",
      "Policy number: HP-2214-8871    Period of insurance: 1 Aug 2024 - 31 Jul 2025",
      "Your policy is due for renewal. Renewal premium: 341.20 including insurance",
      "premium tax.",
      "This policy wording, together with your schedule, forms your contract of insurance.",
      "Section 1 - Buildings. We insure the buildings against loss or damage.",
      "Insuring agreement: we will indemnify you subject to the terms and exclusions.",
    ],
  },
  {
    expect: "insurance-claim",
    file: "claim_ref_44821.pdf",
    title: "Claim acknowledgement",
    body: [
      "Claim acknowledgement",
      "Claim reference: 44821    Policy number: HP-2214-8871",
      "We have received your claim for water damage reported on 12 May 2024.",
      "Date of loss: 10 May 2024",
      "A claims adjuster will contact you within two working days to arrange an",
      "inspection and to explain the proof of loss requirements.",
      "Please retain damaged items until the adjuster has visited.",
    ],
  },
  {
    expect: "lab-report",
    file: "bloods_2024_05.pdf",
    title: "Laboratory Report",
    body: [
      "Laboratory Report",
      "Patient: R. Patel    DOB: 14/02/1988    Collected: 21 May 2024",
      "Full blood count",
      "Haemoglobin      142 g/L      Reference range 130-170",
      "White cell count 6.1 x10^9/L  Reference range 4.0-11.0",
      "Platelets        260 x10^9/L  Reference range 150-400",
      "Comprehensive metabolic panel: sodium 139 mmol/L (135-145), potassium 4.2 (3.5-5.3)",
      "Reported by: City Pathology Services",
    ],
  },
  {
    expect: "prescription",
    file: "rx_amoxicillin.pdf",
    title: "Prescription",
    body: [
      "Prescription",
      "Patient: L. Novak    DOB: 02/11/1979",
      "Amoxicillin 500mg capsules",
      "Take one capsule three times daily for 7 days. Qty dispensed: 21",
      "Refills remaining: 0    Days supply: 7",
      "Prescriber: Dr H. Adeyemi, Riverside Practice",
      "Pharmacy stamp: Elmswell Pharmacy, 4 High Street",
    ],
  },
  {
    expect: "utility-bill",
    file: "city_power_june.pdf",
    pages: 3,
    title: "Your energy statement",
    body: [
      "Your energy statement",
      "Supply address: Flat 2, 18 Camden Row, London NW1 8QP",
      "Billing period: 1 May - 31 May 2024",
      "Electricity used: 212 kWh at 27.4p per kWh ... 58.09",
      "Standing charge: 31 days at 53.8p ... 16.68",
      "Meter number: E19D 44210    Previous reading: 30412 (estimated reading)",
      "Present reading: 30624",
      "Total charges this period: 74.77",
    ],
  },
  {
    expect: "booking-confirmation",
    file: "hotel_confirmation.pdf",
    title: "Booking Confirmation",
    body: [
      "Booking Confirmation",
      "Confirmation number: HTL-99281",
      "Your booking is confirmed at the Harbourview Hotel, Edinburgh.",
      "Check-in date: 12 July 2024 from 15:00",
      "Check-out date: 14 July 2024 by 11:00",
      "Room: Double, city view, breakfast included. 2 nights, 2 guests.",
      "Total: 286.00, payable at the property. Free cancellation until 10 July.",
    ],
  },
  {
    expect: "itinerary",
    file: "trip_edinburgh.pdf",
    title: "Travel Itinerary",
    body: [
      "Travel Itinerary",
      "Traveller: A. Diallo    Booking reference: XK9PLQ",
      "Outbound - 12 July 2024",
      "LHR London Heathrow 09:15 -> EDI Edinburgh 10:40, BA 1442, seat 14C",
      "Return - 14 July 2024",
      "EDI Edinburgh 18:05 -> LHR London Heathrow 19:35, BA 1447, seat 9A",
      "Hotel: Harbourview Hotel, 2 nights. Trip summary and e-tickets attached.",
    ],
  },
  {
    expect: "order-confirmation",
    file: "order_10422.pdf",
    title: "Order Confirmation",
    body: [
      "Order Confirmation",
      "Thank you for your order, Amara.",
      "Order number: 10422    Placed: 2 June 2024",
      "1x Ergonomic split keyboard ... 129.00",
      "1x Palm rest, walnut ... 39.00",
      "Estimated delivery: 6-8 June to 14 Fern Road, Bristol.",
      "We will email you when your order ships.",
    ],
  },
  {
    expect: "packing-slip",
    file: "packing_slip_10422.pdf",
    title: "Packing Slip",
    body: [
      "Packing Slip",
      "Order number: 10422    Shipped: 5 June 2024",
      "Ship to: A. Diallo, 14 Fern Road, Bristol BS1 5TR",
      "Qty shipped   Item",
      "1             Ergonomic split keyboard",
      "1             Palm rest, walnut",
      "Items in this shipment: 2 of 2. This is not an invoice.",
    ],
  },
  {
    expect: "delivery-note",
    file: "delivery_note_8871.pdf",
    title: "Delivery Note",
    body: [
      "Delivery Note",
      "Delivery note no: DN-8871    Date: 25 June 2024",
      "Deliver to: Unit 4, Riverside Industrial Estate, Leeds LS10 1AB",
      "Against order: PO-88412",
      "500 x Corrugated boxes 40x30cm",
      "200 x Kraft void fill rolls",
      "Received in good condition. Signed for by: ____________  Time: ______",
    ],
  },
  {
    expect: "user-guide",
    file: "kettle_manual.pdf",
    pages: 24,
    title: "Instruction Manual",
    body: [
      "Instruction Manual",
      "Rapid-boil kettle, model KB-170",
      "Important safety instructions - read before first use.",
      "This appliance can be used by children aged from 8 years and above if they have",
      "been given supervision or instruction concerning use of the appliance.",
      "Operating instructions: fill between MIN and MAX, close the lid, press the switch.",
      "Cleaning and descaling: unplug and allow to cool before cleaning.",
      "Troubleshooting and warranty information on page 20.",
    ],
  },
  {
    expect: "safety-data-sheet",
    file: "sds_isopropanol.pdf",
    pages: 11,
    title: "Safety Data Sheet",
    body: [
      "Safety Data Sheet",
      "Section 1: Identification. Product: Isopropyl alcohol 99.9%",
      "Section 2: Hazards identification. Highly flammable liquid and vapour.",
      "Section 4: First aid measures. IF IN EYES: rinse cautiously with water.",
      "Section 6: Accidental release measures. Eliminate all ignition sources.",
      "Section 11: Toxicological information. May cause drowsiness or dizziness.",
      "According to Regulation (EC) No 1907/2006 (REACH).",
    ],
  },
  {
    expect: "certificate",
    file: "first_aid_cert.pdf",
    title: "Certificate of Completion",
    body: [
      "Certificate of Completion",
      "This is to certify that",
      "K. Osei",
      "has successfully completed the Emergency First Aid at Work course",
      "held on 20 May 2024 at the Elmswell Training Centre.",
      "Valid for three years from the date of issue.",
      "Instructor: P. Marsh    Certificate no: EFAW-20240520-081",
    ],
  },
  {
    expect: "transcript",
    file: "uw_transcript.pdf",
    pages: 2,
    title: "Official Transcript",
    body: [
      "Official Transcript",
      "Office of the Registrar, University of Washington",
      "Student: John Smith    Student ID: 1735522",
      "Program: B.S. Computer Science",
      "CSE 142 Programming I      4.0 credits   grade 3.8",
      "CSE 143 Programming II     4.0 credits   grade 3.9",
      "MATH 126 Calculus III      5.0 credits   grade 3.6",
      "Cumulative GPA: 3.72    Degree conferred: 10 June 2017",
    ],
  },
  {
    expect: "research-paper",
    file: "streaming_paper.pdf",
    pages: 12,
    title: "Adaptive Backpressure in Distributed Stream Processors",
    body: [
      "Adaptive Backpressure in Distributed Stream Processors",
      "J. Smith, L. Chen - Meridian Labs",
      "Abstract - We present an adaptive backpressure protocol that reduces tail",
      "latency by 41% under skewed load. In this paper we formalise the problem,",
      "prove stability bounds, and evaluate on three production traces.",
      "1. Introduction. Stream processors must balance throughput against latency.",
      "Corresponding author: j.smith@meridianlabs.example",
      "References [1] Chen et al. (2021) [2] Okafor and Reyes (2019)",
    ],
  },
  {
    expect: "statement-of-work",
    file: "sow_kestrel_phase2.pdf",
    pages: 6,
    title: "Statement of Work",
    body: [
      "Statement of Work",
      "This Statement of Work is entered into under the Master Services Agreement",
      "dated 1 March 2024 between Kestrel Ltd and Corven Holdings.",
      "Scope of work: phase 2 accessibility audit of the claims portal.",
      "Deliverables: audit report, remediation backlog, retest of priority issues.",
      "Period of performance: 1 July - 30 September 2024.",
      "Acceptance criteria: all priority-1 issues verified fixed on retest.",
      "Fees: time and materials, capped at 48,000.",
    ],
  },
  {
    expect: "proposal",
    file: "proposal_fleet_audit.pdf",
    pages: 8,
    title: "Proposal",
    body: [
      "Proposal for Meridian Logistics",
      "Fleet inspection digitisation - our proposed approach",
      "Scope of work: replace paper inspection sheets across 14 depots with digital",
      "checklists, defect triage, and parts integration.",
      "Timeline: 12 weeks from kick-off, phased by region.",
      "Investment: 86,000 fixed fee, including training.",
      "Acceptance of this proposal: sign below to authorise the work.",
      "This proposal is valid for 60 days.",
    ],
  },
  {
    expect: "form",
    file: "trip_permission.pdf",
    title: "School Trip Permission Slip",
    body: [
      "School Trip Permission Slip",
      "Elmswell Primary School - Year 4 visit to the Natural History Museum",
      "Date of trip: 9 July 2024. Cost: 12.50, payable via the school office.",
      "Please print clearly and return by 28 June.",
      "Child's name: ______________________  Class: ________",
      "I give permission for my child to attend the trip.",
      "Parent/guardian signature: ______________________",
      "Emergency contact number: ______________________",
      "For office use only: payment received [ ]  consent received [ ]",
    ],
  },
  {
    expect: "invitation",
    file: "wedding_invite.pdf",
    title: "You are cordially invited",
    body: [
      "You are cordially invited",
      "to celebrate the marriage of",
      "Amara Diallo and Daniel Reyes",
      "Saturday the fourteenth of September, two thousand twenty-four",
      "at three o'clock in the afternoon",
      "The Orangery, Holland Park, London",
      "Reception to follow. Kindly respond by the first of August.",
    ],
  },
  {
    expect: "email-thread",
    file: "re_re_roofing_tender.pdf",
    pages: 3,
    title: "RE: RE: Roofing tender",
    body: [
      "From: R. Holt <rholt@example.org>",
      "Sent: Tuesday 14 May 2024 09:12",
      "To: D. Cole <dcole@example.org>",
      "Subject: RE: RE: Roofing tender",
      "Agreed - let's shortlist the two lowest compliant bids.",
      "-----Original Message-----",
      "From: D. Cole    Sent: Monday 13 May 2024 16:40",
      "On Mon, 13 May 2024, R. Holt wrote:",
      "> The committee meets Tuesday; can you circulate the tender summary?",
      "Sent from my iPhone",
    ],
  },
  {
    expect: "warranty-document",
    file: "kb170_warranty.pdf",
    title: "Warranty Certificate",
    body: [
      "Warranty Certificate",
      "Rapid-boil kettle, model KB-170",
      "This limited warranty covers defects in materials and workmanship for a",
      "warranty period of two years from the date of purchase.",
      "This warranty does not cover damage from misuse, descaling neglect, or",
      "commercial use.",
      "To make a claim, contact support with your receipt and serial number.",
    ],
  },
  // --- scanned documents: no text layer, the filename is the only signal ---
  {
    expect: "invoice",
    file: "invoice_4412_scan.pdf",
    title: "",
    body: [],
  },
  {
    expect: "bank-statement",
    file: "hsbc_bank_statement_jan.pdf",
    title: "",
    body: [],
  },
  // --- pdf.js extraction artifacts: NBSP separators, curly quotes, fi/fl ligatures ---
  {
    expect: "invoice",
    file: "doc.pdf",
    nbsp: true,
    title: "Tax Invoice",
    body: [
      "Tax Invoice",
      "Invoice Number: INV-2024-3319    Invoice Date: 12 June 2024",
      "Bill To: Harbour Cafe Ltd",
      "Consulting services — May ... 1,400.00",
      "Invoice Total: 1,400.00. Remit payment to the account below.",
    ],
  },
  {
    expect: "nda",
    file: "doc.pdf",
    pages: 3,
    title: "Conﬁdentiality Agreement",
    body: [
      "Conﬁdentiality Agreement",
      "This conﬁdentiality agreement is made between the Disclosing Party and the",
      "Receiving Party. Each party’s conﬁdential information shall be held in",
      "strict conﬁdence and used only to evaluate the proposed relationship.",
      "The obligations survive for ﬁve years from the date of disclosure.",
    ],
  },
  // --- additional common types ---
  {
    expect: "tax-return",
    file: "1040_2023.pdf",
    pages: 4,
    title: "U.S. Individual Income Tax Return",
    body: [
      "Form 1040 - U.S. Individual Income Tax Return 2023",
      "Filing status: married filing jointly",
      "1a Total amount from Form(s) W-2, box 1 ... 72,450",
      "11 Adjusted gross income ... 71,200",
      "16 Tax ... 8,102",
      "25 Federal income tax withheld ... 9,812",
      "34 Refund: amount you overpaid ... 1,710",
    ],
  },
  {
    expect: "subscription-confirmation",
    file: "apple_receipt.pdf",
    title: "Your receipt from Apple",
    body: [
      "Your receipt from Apple",
      "Subscription: CloudSync Pro, monthly",
      "Renewal price: 2.99. Next billing date: 12 July 2024.",
      "Your subscription will automatically renew each month until cancelled.",
      "Manage your subscription in Settings.",
    ],
  },
  {
    expect: "donation-receipt",
    file: "gift_aid_receipt.pdf",
    title: "Donation Receipt",
    body: [
      "Donation Receipt",
      "Riverside Foodbank, registered charity 1122334",
      "Thank you for your donation of 50.00 received on 3 June 2024.",
      "No goods or services were provided in exchange for this contribution.",
      "Gift Aid: as a UK taxpayer, your donation is worth 25% more at no cost to you.",
    ],
  },
  {
    expect: "waybill",
    file: "shipping_label_1Z999.pdf",
    title: "Shipping label",
    body: [
      "Shipping label",
      "UPS Ground    Tracking: 1Z 999 AA1 01 2345 6784",
      "Ship from: Brightline Packaging, Leeds LS10 1AB",
      "Ship to: A. Diallo, 14 Fern Road, Bristol BS1 5TR",
      "Weight: 2.4 kg    Billing: P/P",
      "Package 1 of 1",
    ],
  },
  {
    expect: "customs-declaration",
    file: "cn22.pdf",
    title: "Customs Declaration CN22",
    body: [
      "Customs Declaration CN22",
      "May be opened officially",
      "Description of contents: cotton t-shirts (2)",
      "HS tariff number: 610910    Country of origin: Portugal",
      "Declared value: 38.00    Reason for export: sale of goods",
      "I certify that the particulars given are correct.",
    ],
  },
  {
    expect: "medical-report",
    file: "clinic_letter_rp.pdf",
    pages: 2,
    title: "Clinical Assessment",
    body: [
      "Clinical Assessment",
      "Patient: R. Patel    NHS no: 943 476 5919    Seen: 21 May 2024",
      "Presenting complaint: six weeks of intermittent chest tightness on exertion.",
      "History of present illness: symptoms began after a respiratory infection;",
      "no orthopnoea; exercise tolerance reduced to one flight of stairs.",
      "Past medical history: hypertension, well controlled.",
      "On examination: chest clear, heart sounds normal, BP 132/84.",
      "Impression and plan: likely post-viral; arrange ECG and review in 4 weeks.",
    ],
  },
  {
    expect: "referral-letter",
    file: "referral_cardiology.pdf",
    title: "Referral Letter",
    body: [
      "Referral Letter",
      "Dear colleague,",
      "Re: R. Patel, DOB 14/02/1988",
      "Reason for referral: exertional chest tightness with an abnormal baseline ECG.",
      "I am referring this patient to the rapid access chest pain clinic.",
      "Please see this patient within two weeks given the symptom pattern.",
      "Referring GP: Dr H. Adeyemi, Riverside Practice",
    ],
  },
  {
    expect: "consent-form",
    file: "consent_gastroscopy.pdf",
    title: "Consent Form",
    body: [
      "Consent Form",
      "Procedure: diagnostic gastroscopy",
      "I confirm the procedure, its benefits, and its risks have been explained to me.",
      "I have had the opportunity to ask questions and all my questions have been",
      "answered to my satisfaction.",
      "I consent to the procedure described above.",
      "Patient signature: ____________    Person taking consent: ____________",
    ],
  },
  {
    expect: "benefits-summary",
    file: "pension_statement_2024.pdf",
    pages: 3,
    title: "Annual Benefit Statement",
    body: [
      "Annual Benefit Statement",
      "Scheme: Northgate Group Personal Pension",
      "Statement date: 5 April 2024",
      "Your pension pot on 5 April 2024: 48,210",
      "Contributions received this year: 4,860 (you 2,430, employer 2,430)",
      "Projected pot at age 67: 214,000 in today's money.",
      "This statement is provided annually; it is not a guarantee.",
    ],
  },
  {
    expect: "grade-report",
    file: "y4_summer_report.pdf",
    title: "End of Year Report",
    body: [
      "End of Year Report - Year 4",
      "Pupil: T. Diallo    Class: 4B    Attendance: 96.8%",
      "Reading: working at greater depth. Thoughtful, fluent, and adventurous choices.",
      "Writing: working towards the expected standard; handwriting is improving.",
      "Mathematics: expected standard. Confident with fractions and perimeter.",
      "Effort grade: excellent across all subjects.",
      "Teacher: Ms P. Whitlow    Headteacher: Mr J. Okafor",
    ],
  },
  {
    expect: "course-syllabus",
    file: "cse143_syllabus.pdf",
    pages: 5,
    title: "Course Syllabus",
    body: [
      "Course Syllabus",
      "CSE 143: Computer Programming II, Autumn 2024",
      "Learning objectives: implement and analyse core data structures; write",
      "well-tested object-oriented programs.",
      "Required textbook: Building Java Programs, 5th edition.",
      "Grading: homework 40%, midterm 25%, final 35%.",
      "Week 1: recursion. Week 2: linked lists. Week 3: stacks and queues.",
      "Office hours: Tuesdays 2-4pm, Allen Center 303.",
    ],
  },
  {
    expect: "datasheet",
    file: "lm317_datasheet.pdf",
    pages: 22,
    title: "LM317 Adjustable Regulator",
    body: [
      "LM317 3-Terminal Adjustable Regulator",
      "1 Features: output voltage range adjustable from 1.25V to 37V.",
      "6 Specifications",
      "6.1 Absolute maximum ratings over operating temperature range",
      "6.3 Recommended operating conditions",
      "6.5 Electrical characteristics",
      "7.2 Typical application circuit: adjustable voltage regulator with protection diodes.",
      "8 Pin configuration and functions: ADJ, OUT, IN.",
    ],
  },
  {
    expect: "incident-report",
    file: "ir_2024_007.pdf",
    pages: 6,
    title: "Security Incident Report",
    body: [
      "Security Incident Report IR-2024-007",
      "Severity: SEV-2    Status: closed",
      "Summary: credential stuffing against the customer login endpoint.",
      "Timeline: detected 02:14 UTC by rate-limit alerting; contained 03:05 UTC.",
      "Containment and eradication: blocked source ASNs, forced resets for 112 accounts.",
      "Indicators of compromise: IP list attached; no data exfiltration observed.",
      "Follow-ups: roll out WebAuthn, tighten per-IP limits.",
    ],
  },
  {
    expect: "audit-report",
    file: "soc2_type2_2024.pdf",
    pages: 48,
    title: "SOC 2 Type II Report",
    body: [
      "SOC 2 Type II Report",
      "System and Organization Controls report on Kestrel Ltd's audit platform.",
      "Independent service auditor's report for the period 1 April 2023 to 31 March 2024.",
      "Applicable trust services criteria: security, availability, confidentiality.",
      "Section 3: description of the system. Section 4: tests of controls and results.",
      "In our opinion, controls were suitably designed and operated effectively.",
    ],
  },
  // A US-style resume with bare section headings, no CV title, and no LinkedIn URL.
  {
    expect: "resume",
    file: "jordan_avery_2024.pdf",
    title: "JORDAN AVERY",
    body: [
      "JORDAN AVERY",
      "Portland, OR | (503) 555-0142 | j.avery@example.com",
      "EXPERIENCE",
      "Operations Manager, Cascade Outfitters    2019 - Present",
      "- Run daily operations for a 40-person retail and rental business",
      "- Cut inventory shrinkage 18% by introducing weekly cycle counts",
      "Assistant Manager, Trailhead Sports    2015 - 2019",
      "EDUCATION",
      "B.A. Business Administration, University of Oregon, 2015",
      "SKILLS",
      "Scheduling, budgeting, vendor negotiation, POS systems",
    ],
  },
  // --- negative controls: must stay unlabelled ---
  {
    expect: "",
    file: "weekend_notes.pdf",
    title: "Weekend Notes",
    body: [
      "The weather was clear on Saturday so we walked along the river and stopped",
      "for coffee near the old bridge before the rain started in the afternoon.",
      "On Sunday we tidied the garden, read for a while and then cooked a simple",
      "dinner with the vegetables that were still fresh from last week.",
      "Nothing else of note happened, and it was a quiet couple of days overall.",
    ],
  },
  {
    expect: "",
    file: "contrato.pdf",
    title: "CONTRATO DE ARRENDAMIENTO",
    body: [
      "El presente contrato de arrendamiento se celebra entre el arrendador y el",
      "arrendatario para el alquiler de la vivienda situada en la direccion indicada.",
      "El arrendatario se compromete a pagar la renta mensual dentro de los primeros",
      "cinco dias de cada mes segun las condiciones que se establecen en este documento.",
      "Ambas partes firman este contrato en senal de conformidad con sus clausulas.",
    ],
  },
];

describe("heuristic engine broad corpus", () => {
  it.each(CASES.map((c) => [c.expect || `nothing (${c.file})`, c] as const))(
    "labels a %s correctly",
    (_label, c) => {
      const r = run(c);
      const detail = `expected ${c.expect || "no label"}, got [${r.labels.join(", ")}] (confidence ${r.confidence}, score ${r.score})`;
      if (c.expect === "") {
        expect(r.labels, detail).toEqual([]);
      } else {
        expect(r.labels[0], detail).toBe(c.expect);
      }
    },
  );
});
