// Broad-corpus accuracy gate: one realistic, natural-prose specimen per document
// type, asserted on the real engine + rules pack.

import { beforeAll, describe, expect, it } from "vitest";
import {
  classifyHeuristic,
  ensureRulesLoaded,
} from "@app/services/heuristic/heuristicEngine";
import type { HeuristicDoc } from "@app/services/heuristic/types";

beforeAll(async () => {
  await ensureRulesLoaded();
});

interface Case {
  /** Expected top label; "" asserts the document stays unlabelled. */
  expect: string;
  file: string;
  pages?: number;
  /** Replace every space with U+00A0, as some pdf.js text layers do. */
  nbsp?: boolean;
  /** Info-dict metadata (lowercase keys), e.g. a generator's producer string. */
  meta?: Record<string, string>;
  title: string;
  body: string[];
}

const run = (c: Case) => {
  let body = c.body.join("\n");
  let title = c.title;
  if (c.nbsp) {
    body = body.replace(/ /g, "\u00A0");
    title = title.replace(/ /g, "\u00A0");
  }
  const doc: HeuristicDoc = {
    fileName: c.file,
    pageCount: c.pages ?? 1,
    meta: c.meta ?? {},
    titleZone: title,
    firstZone: body,
    allZone: body,
  };
  return classifyHeuristic(doc);
};

const CASES: Case[] = [
  {
    expect: "invoice",
    file: "2024-014.pdf",
    title: "Invoice",
    body: [
      "Invoice",
      "Jane Mills Design, 14 Fern Road, Bristol BS1 5TR",
      "Invoice #: 2024-014    Date: 3 May 2024",
      "Bill To: Harbour Cafe Ltd",
      "Logo refresh and brand guidelines ... $950.00",
      "Menu redesign (2 rounds) ... $250.00",
      "Total: $1,200.00",
      "Payment terms: Net 30. Bank transfer to sort code 20-00-00, account 55667788.",
    ],
  },
  {
    expect: "receipt",
    file: "20240506_183212.pdf",
    title: "Greenway Grocers",
    body: [
      "Greenway Grocers",
      "112 Station Road    06/05/2024 18:32",
      "Oat milk 1L            2.20",
      "Sourdough loaf         3.80",
      "Free range eggs x12    4.10",
      "TOTAL                 10.10",
      "VISA ****4421   Contactless",
      "Approval code: 08841",
      "Thank you for shopping with us",
    ],
  },
  {
    expect: "bank-statement",
    file: "statement_march.pdf",
    pages: 3,
    title: "Your account statement",
    body: [
      "Your account statement",
      "Statement period: 1 March 2024 - 31 March 2024",
      "Sort code: 40-12-31    Account number: 71002233",
      "Opening balance                          2,140.55",
      "2 Mar   Faster payment - RENT            -950.00",
      "5 Mar   Salary ACME LTD                 +2,850.00",
      "12 Mar  Direct debit - CITY POWER         -84.20",
      "19 Mar  Card purchase - GREENWAY          -10.10",
      "Closing balance                          3,946.25",
      "Money in: 2,850.00    Money out: 1,044.30",
    ],
  },
  {
    expect: "statement-of-account",
    file: "april_card.pdf",
    pages: 2,
    title: "Monthly statement",
    body: [
      "Monthly statement",
      "Account ending in 8891",
      "Previous balance: $412.90    New balance: $388.15",
      "Minimum payment due: $25.00    Payment due date: 28 April 2024",
      "Credit limit: $4,500    Available credit: $4,111.85",
      "Annual percentage rate (APR): 22.9% variable",
      "Late payment warning: if we do not receive your minimum payment by the date listed above,",
      "you may have to pay a late fee of up to $39.",
      "Interest charge calculation: your APR is applied to the daily balance.",
    ],
  },
  {
    expect: "purchase-order",
    file: "PO-88412.pdf",
    title: "Purchase Order",
    body: [
      "Purchase Order",
      "P.O. Number: PO-88412    Date: 11 June 2024",
      "Vendor: Brightline Packaging Ltd",
      "Ship To: Unit 4, Riverside Industrial Estate, Leeds LS10 1AB",
      "Qty Ordered   Description                Unit Price",
      "500           Corrugated boxes 40x30cm   0.85",
      "200           Kraft void fill rolls      3.20",
      "Delivery date: on or before 25 June 2024.",
      "All invoices must quote the PO number. No PO, no pay.",
    ],
  },
  {
    expect: "quote",
    file: "landscaping_quote.pdf",
    title: "Quotation",
    body: [
      "Quotation",
      "Quotation number: Q-2231    Date: 8 April 2024",
      "Prepared for: Mr and Mrs Aldridge",
      "We are pleased to quote for the following garden works:",
      "Re-turf rear lawn (85 sqm) ... 1,540.00",
      "Patio pressure wash and re-point ... 380.00",
      "Total (inc VAT): 1,920.00",
      "This quote is valid for 30 days from the date above.",
    ],
  },
  {
    expect: "expense-report",
    file: "march_expenses.pdf",
    title: "Expense report",
    body: [
      "Expense report",
      "Employee: D. Okafor    Department: Field Sales",
      "Period: 1-31 March 2024",
      "04 Mar  Client lunch, Manchester        38.50",
      "11 Mar  Rail ticket, London return      86.00",
      "18 Mar  Hotel, 1 night (conference)    129.00",
      "Per diem (2 days)                       90.00",
      "Total reimbursable: 343.50",
      "Receipts attached. Approved by: S. Hughes",
    ],
  },
  {
    expect: "payslip",
    file: "payslip_2024_05.pdf",
    title: "Payslip",
    body: [
      "Payslip",
      "Employee: R. Patel    Employee no: 00482    Pay date: 31 May 2024",
      "Payments                       Deductions",
      "Basic pay      2,916.67        PAYE tax        382.40",
      "                               National Insurance 231.15",
      "                               Pension (5%)    145.83",
      "Gross pay: 2,916.67            Net pay: 2,157.29",
      "Tax code: 1257L    NI category: A",
      "Year to date: gross 14,583.35, tax 1,912.00",
    ],
  },
  {
    expect: "tax-form",
    file: "W2_2023.pdf",
    title: "Wage and Tax Statement",
    body: [
      "Form W-2 Wage and Tax Statement 2023",
      "Employer: Lakeshore Analytics Inc, EIN 84-2210043",
      "Employee: M. Torres    SSN XXX-XX-4821",
      "1 Wages, tips, other compensation   72,450.00",
      "2 Federal income tax withheld        9,812.00",
      "3 Social security wages             72,450.00",
      "4 Social security tax withheld       4,491.90",
      "5 Medicare wages and tips           72,450.00",
      "Copy B - to be filed with employee's federal tax return.",
    ],
  },
  {
    expect: "nda",
    file: "acme_nda_signed.pdf",
    pages: 4,
    title: "Non-Disclosure Agreement",
    body: [
      "Non-Disclosure Agreement",
      "This Agreement is made between Acme Ltd (the Disclosing Party) and the undersigned",
      "recipient (the Receiving Party).",
      "1. The Receiving Party shall hold all Confidential Information in strict confidence.",
      "2. Confidential Information excludes information that is or becomes publicly available.",
      "3. This Agreement shall remain in force for five years from the date of signature.",
      "Signed for and on behalf of the parties:",
    ],
  },
  {
    expect: "contract",
    file: "signed_agreement_final_v3.pdf",
    pages: 9,
    title: "Agreement",
    body: [
      "Agreement",
      "This Agreement is entered into as of 1 July 2024 between Corven Holdings Ltd and",
      "Meridian Supplies Ltd.",
      "WITNESSETH: in consideration of the mutual covenants contained herein, the parties",
      "agree as follows:",
      "1. Definitions. Capitalised terms have the meanings set out in Schedule 1.",
      "5. Limitation of liability. Neither party shall be liable for indirect losses.",
      "9. Entire agreement. This Agreement constitutes the entire agreement between the parties.",
      "IN WITNESS WHEREOF the parties have executed this Agreement.",
    ],
  },
  {
    expect: "employment-contract",
    file: "contract_r_patel.pdf",
    pages: 7,
    title: "Contract of Employment",
    body: [
      "Contract of Employment",
      "This contract of employment is made between Northgate Logistics Ltd (the Employer)",
      "and R. Patel (the Employee).",
      "1. Commencement. Your employment begins on 2 September 2024.",
      "2. Probationary period. The first six months are a probationary period.",
      "3. Hours. The Employee shall work 37.5 hours per week.",
      "4. Holiday. 25 days per annum plus public holidays.",
      "5. Notice. Either party may terminate on eight weeks written notice.",
    ],
  },
  {
    expect: "lease-agreement",
    file: "flat2_tenancy.pdf",
    pages: 12,
    title: "Assured Shorthold Tenancy Agreement",
    body: [
      "Assured Shorthold Tenancy Agreement",
      "Property: Flat 2, 18 Camden Row, London NW1 8QP",
      "Landlord: H. Berger    Tenant: L. Novak",
      "Term: 12 months commencing 1 August 2024",
      "Rent: 1,650 per calendar month, payable in advance",
      "Security deposit: 1,903.85, protected with the Deposit Protection Service",
      "The tenant shall not sublet the property without written consent.",
    ],
  },
  {
    expect: "terms-and-conditions",
    file: "tos.pdf",
    pages: 14,
    title: "Terms of Service",
    body: [
      "Terms of Service",
      "Last updated: 12 February 2024",
      "By accessing or using the Kestrel platform you agree to be bound by these terms.",
      "1. Your account. You are responsible for safeguarding your credentials.",
      "2. Acceptable use. You must not misuse the services or interfere with their operation.",
      "3. Termination. We may suspend or terminate access for breach of these terms.",
      "4. Disclaimers. The services are provided on an as-is basis.",
    ],
  },
  {
    expect: "privacy-policy",
    file: "privacy.pdf",
    pages: 8,
    title: "Privacy Notice",
    body: [
      "Privacy Notice",
      "This notice explains how Kestrel Ltd, as data controller, handles your information.",
      "Personal data we collect: account details, usage data, and support correspondence.",
      "How we use your information: to provide the service, for billing, and for security.",
      "Your rights include access, rectification, and the right to erasure.",
      "We retain personal data only as long as necessary for the purposes described.",
      "Contact our data protection officer at privacy@kestrel.example.",
    ],
  },
  {
    expect: "will",
    file: "last_will.pdf",
    pages: 5,
    title: "Last Will and Testament",
    body: [
      "Last Will and Testament",
      "I, Margaret Ellen Shaw, being of sound mind, declare this to be my last will and",
      "testament, revoking all former wills.",
      "1. I appoint my daughter, C. Shaw, as executor of this will.",
      "2. I give, devise and bequeath my residuary estate to my children in equal shares,",
      "per stirpes.",
      "Signed by the testator in our presence, who in her presence signed as witnesses.",
    ],
  },
  {
    expect: "power-of-attorney",
    file: "lpa_finance.pdf",
    pages: 10,
    title: "Lasting Power of Attorney",
    body: [
      "Lasting Power of Attorney",
      "Property and financial affairs",
      "Donor: A. Whitfield    Attorney: J. Whitfield",
      "I appoint my attorney to make decisions about my property and financial affairs.",
      "This lasting power of attorney is registered with the Office of the Public Guardian.",
      "Certificate provider statement: the donor understands the purpose of this LPA.",
    ],
  },
  {
    expect: "resume",
    file: "john_smith.pdf",
    pages: 2,
    title: "JOHN SMITH",
    body: [
      "JOHN SMITH",
      "Software Engineer | San Francisco, CA | john.smith@example.com | linkedin.com/in/jsmith",
      "EXPERIENCE",
      "Senior Software Engineer, Meridian Labs    2021 - Present",
      "- Led a team of four building a real-time analytics pipeline handling 2B events/day",
      "- Cut infrastructure spend 30% by consolidating streaming services",
      "Software Engineer, Halcyon Systems    2017 - 2021",
      "- Shipped the customer-facing dashboard used by 40k monthly users",
      "EDUCATION",
      "B.S. Computer Science, University of Washington, 2017",
      "SKILLS",
      "Go, TypeScript, Kubernetes, PostgreSQL, Kafka",
    ],
  },
  {
    expect: "cover-letter",
    file: "application_kestrel.pdf",
    title: "Application for Product Designer",
    body: [
      "Dear Hiring Manager,",
      "I am writing to apply for the Product Designer role advertised on your careers page.",
      "In my current position at Fieldnote I redesigned the onboarding flow, lifting",
      "activation by 22%, and I run our fortnightly usability testing programme.",
      "Kestrel's focus on accessible tools is why I am excited to apply; my portfolio",
      "includes two WCAG AA redesigns shipped end to end.",
      "Thank you for considering my application. I look forward to the opportunity to",
      "discuss how I can contribute.",
      "Yours sincerely, Amara Diallo",
    ],
  },
  {
    expect: "offer-letter",
    file: "kestrel_offer.pdf",
    title: "Offer of Employment",
    body: [
      "Offer of Employment",
      "Dear Amara,",
      "We are pleased to offer you the position of Product Designer at Kestrel Ltd.",
      "Your start date will be 7 October 2024, and your annual base salary will be 68,000.",
      "This offer is contingent on satisfactory references and right-to-work checks.",
      "To accept this offer, please sign and return a copy of this letter by 20 September.",
      "We look forward to welcoming you to the team.",
    ],
  },
  {
    expect: "reference-letter",
    file: "reference_adiallo.pdf",
    title: "Letter of Recommendation",
    body: [
      "Letter of Recommendation",
      "To whom it may concern,",
      "It is my pleasure to recommend Amara Diallo, who reported to me for three years",
      "at Fieldnote as a product designer.",
      "Amara combines rigorous research habits with fast, pragmatic delivery; her",
      "onboarding redesign became the template for the rest of the product.",
      "I highly recommend her without reservation. Please contact me with any questions.",
      "Daniel Reyes, Head of Design, Fieldnote",
    ],
  },
  {
    expect: "job-description",
    file: "jd_platform_eng.pdf",
    title: "Senior Platform Engineer",
    body: [
      "Senior Platform Engineer",
      "About the role",
      "We are seeking a senior engineer to own our deployment platform and developer",
      "tooling, reporting to the Head of Infrastructure.",
      "Responsibilities",
      "- Operate and evolve the Kubernetes-based delivery pipeline",
      "Required qualifications",
      "- 5+ years running production cloud infrastructure",
      "Preferred qualifications",
      "- Experience with progressive delivery and service meshes",
    ],
  },
  {
    expect: "performance-review",
    file: "h2_review_jsmith.pdf",
    title: "Performance Review",
    body: [
      "Performance Review - H2 2024",
      "Employee: J. Smith    Reviewer: T. Nguyen    Role: Senior Engineer",
      "Overall rating: exceeds expectations",
      "Strengths: consistently unblocks the team; the analytics migration landed a",
      "quarter early with zero data loss.",
      "Areas for improvement: delegate more of the operational load; invest in",
      "documenting decisions for newer engineers.",
      "Goals for next period: lead the multi-region rollout; mentor two engineers.",
    ],
  },
  {
    expect: "timesheet",
    file: "week_22_hours.pdf",
    title: "Timesheet",
    body: [
      "Timesheet",
      "Employee: K. Osei    Week ending: 31 May 2024",
      "Mon 7.50    Tue 7.50    Wed 8.00    Thu 7.50    Fri 6.00",
      "Regular hours: 36.50",
      "Overtime hours: 0.00",
      "Total hours: 36.50",
      "Employee signature: ____________    Approved by: L. Grant",
    ],
  },
  {
    expect: "meeting-minutes",
    file: "board_minutes_may.pdf",
    pages: 3,
    title: "Minutes of the Meeting",
    body: [
      "Minutes of the Meeting of the Facilities Committee",
      "Held 14 May 2024, Committee Room B. Present: R. Holt (chair), five members.",
      "Apologies for absence: D. Cole.",
      "The meeting was called to order at 18:05. A quorum was present.",
      "Matters arising: the roofing tender shortlist was approved. Motion carried.",
      "Any other business: none.",
      "Date of next meeting: 11 June 2024. The meeting adjourned at 19:20.",
    ],
  },
  {
    expect: "meeting-agenda",
    file: "agenda_11june.pdf",
    title: "Meeting Agenda",
    body: [
      "Meeting Agenda",
      "Facilities Committee - 11 June 2024, 18:00, Committee Room B",
      "1. Call to order and apologies for absence",
      "2. Adoption of the agenda",
      "3. Approval of minutes of the previous meeting",
      "4. Agenda item: roofing contract award",
      "5. Agenda item: car park resurfacing budget",
      "6. Any other business",
      "7. Date of next meeting",
    ],
  },
  {
    expect: "memo",
    file: "memo_hybrid_policy.pdf",
    title: "Memorandum",
    body: [
      "Memorandum",
      "To: All staff    From: Operations    Date: 3 June 2024",
      "Re: Updated hybrid working arrangements",
      "Effective 1 July, core in-office days move to Tuesday through Thursday.",
      "Team leads may approve exceptions for caregiving or medical needs.",
      "Desk booking opens each Thursday for the following week.",
      "Questions to operations@corven.example.",
    ],
  },
  {
    expect: "press-release",
    file: "kestrel_series_b.pdf",
    title: "FOR IMMEDIATE RELEASE",
    body: [
      "FOR IMMEDIATE RELEASE",
      "Kestrel raises $40M Series B to expand accessible design tooling",
      "LONDON, 4 June 2024 - Kestrel Ltd today announced a $40 million Series B round",
      "led by Meridian Growth, with participation from existing investors.",
      "The funding will accelerate hiring and the launch of Kestrel's audit platform.",
      '"Accessibility is still an afterthought in most tooling," said CEO N. Okafor.',
      "Media contact: press@kestrel.example    Notes to editors: photography available.",
    ],
  },
  {
    expect: "newsletter",
    file: "parish_news_june.pdf",
    pages: 4,
    title: "The Elmswell Bulletin",
    body: [
      "The Elmswell Bulletin - June edition",
      "In this issue: the summer fete returns, allotment news, and a new cafe on the green.",
      "From the editor: thank you to everyone who volunteered at the spring clean-up.",
      "Dates for your diary: 15 June - summer fete; 22 June - open gardens.",
      "Allotment corner: plots 12 and 14 are available; contact the parish office.",
      "Next month we profile the new head teacher at Elmswell Primary.",
    ],
  },
  {
    expect: "white-paper",
    file: "zero_trust_wp.pdf",
    pages: 16,
    title: "Zero Trust in Practice",
    body: [
      "Zero Trust in Practice",
      "A white paper on migrating enterprise networks beyond the perimeter model.",
      "Executive summary",
      "This white paper examines the operational realities of zero-trust rollouts across",
      "three sectors, drawing on 40 practitioner interviews.",
      "Key findings: phased device-trust rollouts outperform big-bang migrations; identity",
      "debt is the leading cause of stalled programmes.",
      "Conclusions and recommendations follow in section 6.",
    ],
  },
  {
    expect: "case-study",
    file: "meridian_case_study.pdf",
    pages: 3,
    title: "Customer Case Study",
    body: [
      "Customer Case Study",
      "How Meridian Logistics cut fleet downtime by 34% with Kestrel Audit",
      "About the client: Meridian operates 1,200 vehicles across the UK and Ireland.",
      "The challenge: paper-based inspections meant defects surfaced days late.",
      "The solution: digital inspections with automated triage and parts ordering.",
      "The results: downtime fell 34% in six months; audit prep time fell from three",
      "weeks to two days.",
      '"It paid for itself in a quarter," said the fleet director.',
    ],
  },
  {
    expect: "financial-statement",
    file: "annual_accounts_2023.pdf",
    pages: 42,
    title: "Consolidated Financial Statements",
    body: [
      "Consolidated Financial Statements",
      "For the year ended 31 December 2023",
      "Independent auditor's report to the members of Corven Holdings plc",
      "Consolidated statement of financial position",
      "Consolidated statement of cash flows",
      "Notes to the financial statements",
      "1. Basis of preparation. These statements are prepared under IFRS.",
      "Revenue for the year was 84.2m (2022: 71.9m).",
    ],
  },
  {
    expect: "budget",
    file: "fy25_operating_budget.pdf",
    pages: 6,
    title: "FY25 Operating Budget",
    body: [
      "FY25 Operating Budget",
      "Department: Product Engineering",
      "Budget vs actual, FY24, and proposed FY25 allocations",
      "Headcount            FY24 actual 3.2m    FY25 budget 3.6m",
      "Cloud infrastructure FY24 actual 1.1m    FY25 budget 1.0m",
      "Tooling and licences FY24 actual 0.3m    FY25 budget 0.4m",
      "The rolling forecast is updated quarterly; variances above 10% require sign-off.",
    ],
  },
  {
    expect: "insurance-policy",
    file: "home_policy_renewal.pdf",
    pages: 18,
    title: "Your Home Insurance Policy",
    body: [
      "Your Home Insurance Policy",
      "Policy number: HP-2214-8871    Period of insurance: 1 Aug 2024 - 31 Jul 2025",
      "Your policy is due for renewal. Renewal premium: 341.20 including insurance",
      "premium tax.",
      "This policy wording, together with your schedule, forms your contract of insurance.",
      "Section 1 - Buildings. We insure the buildings against loss or damage.",
      "Insuring agreement: we will indemnify you subject to the terms and exclusions.",
    ],
  },
  {
    expect: "insurance-claim",
    file: "claim_ref_44821.pdf",
    title: "Claim acknowledgement",
    body: [
      "Claim acknowledgement",
      "Claim reference: 44821    Policy number: HP-2214-8871",
      "We have received your claim for water damage reported on 12 May 2024.",
      "Date of loss: 10 May 2024",
      "A claims adjuster will contact you within two working days to arrange an",
      "inspection and to explain the proof of loss requirements.",
      "Please retain damaged items until the adjuster has visited.",
    ],
  },
  {
    expect: "lab-report",
    file: "bloods_2024_05.pdf",
    title: "Laboratory Report",
    body: [
      "Laboratory Report",
      "Patient: R. Patel    DOB: 14/02/1988    Collected: 21 May 2024",
      "Full blood count",
      "Haemoglobin      142 g/L      Reference range 130-170",
      "White cell count 6.1 x10^9/L  Reference range 4.0-11.0",
      "Platelets        260 x10^9/L  Reference range 150-400",
      "Comprehensive metabolic panel: sodium 139 mmol/L (135-145), potassium 4.2 (3.5-5.3)",
      "Reported by: City Pathology Services",
    ],
  },
  {
    expect: "prescription",
    file: "rx_amoxicillin.pdf",
    title: "Prescription",
    body: [
      "Prescription",
      "Patient: L. Novak    DOB: 02/11/1979",
      "Amoxicillin 500mg capsules",
      "Take one capsule three times daily for 7 days. Qty dispensed: 21",
      "Refills remaining: 0    Days supply: 7",
      "Prescriber: Dr H. Adeyemi, Riverside Practice",
      "Pharmacy stamp: Elmswell Pharmacy, 4 High Street",
    ],
  },
  {
    expect: "utility-bill",
    file: "city_power_june.pdf",
    pages: 3,
    title: "Your energy statement",
    body: [
      "Your energy statement",
      "Supply address: Flat 2, 18 Camden Row, London NW1 8QP",
      "Billing period: 1 May - 31 May 2024",
      "Electricity used: 212 kWh at 27.4p per kWh ... 58.09",
      "Standing charge: 31 days at 53.8p ... 16.68",
      "Meter number: E19D 44210    Previous reading: 30412 (estimated reading)",
      "Present reading: 30624",
      "Total charges this period: 74.77",
    ],
  },
  {
    expect: "booking-confirmation",
    file: "hotel_confirmation.pdf",
    title: "Booking Confirmation",
    body: [
      "Booking Confirmation",
      "Confirmation number: HTL-99281",
      "Your booking is confirmed at the Harbourview Hotel, Edinburgh.",
      "Check-in date: 12 July 2024 from 15:00",
      "Check-out date: 14 July 2024 by 11:00",
      "Room: Double, city view, breakfast included. 2 nights, 2 guests.",
      "Total: 286.00, payable at the property. Free cancellation until 10 July.",
    ],
  },
  {
    expect: "itinerary",
    file: "trip_edinburgh.pdf",
    title: "Travel Itinerary",
    body: [
      "Travel Itinerary",
      "Traveller: A. Diallo    Booking reference: XK9PLQ",
      "Outbound - 12 July 2024",
      "LHR London Heathrow 09:15 -> EDI Edinburgh 10:40, BA 1442, seat 14C",
      "Return - 14 July 2024",
      "EDI Edinburgh 18:05 -> LHR London Heathrow 19:35, BA 1447, seat 9A",
      "Hotel: Harbourview Hotel, 2 nights. Trip summary and e-tickets attached.",
    ],
  },
  {
    expect: "order-confirmation",
    file: "order_10422.pdf",
    title: "Order Confirmation",
    body: [
      "Order Confirmation",
      "Thank you for your order, Amara.",
      "Order number: 10422    Placed: 2 June 2024",
      "1x Ergonomic split keyboard ... 129.00",
      "1x Palm rest, walnut ... 39.00",
      "Estimated delivery: 6-8 June to 14 Fern Road, Bristol.",
      "We will email you when your order ships.",
    ],
  },
  {
    expect: "packing-slip",
    file: "packing_slip_10422.pdf",
    title: "Packing Slip",
    body: [
      "Packing Slip",
      "Order number: 10422    Shipped: 5 June 2024",
      "Ship to: A. Diallo, 14 Fern Road, Bristol BS1 5TR",
      "Qty shipped   Item",
      "1             Ergonomic split keyboard",
      "1             Palm rest, walnut",
      "Items in this shipment: 2 of 2. This is not an invoice.",
    ],
  },
  {
    expect: "delivery-note",
    file: "delivery_note_8871.pdf",
    title: "Delivery Note",
    body: [
      "Delivery Note",
      "Delivery note no: DN-8871    Date: 25 June 2024",
      "Deliver to: Unit 4, Riverside Industrial Estate, Leeds LS10 1AB",
      "Against order: PO-88412",
      "500 x Corrugated boxes 40x30cm",
      "200 x Kraft void fill rolls",
      "Received in good condition. Signed for by: ____________  Time: ______",
    ],
  },
  {
    expect: "user-guide",
    file: "kettle_manual.pdf",
    pages: 24,
    title: "Instruction Manual",
    body: [
      "Instruction Manual",
      "Rapid-boil kettle, model KB-170",
      "Important safety instructions - read before first use.",
      "This appliance can be used by children aged from 8 years and above if they have",
      "been given supervision or instruction concerning use of the appliance.",
      "Operating instructions: fill between MIN and MAX, close the lid, press the switch.",
      "Cleaning and descaling: unplug and allow to cool before cleaning.",
      "Troubleshooting and warranty information on page 20.",
    ],
  },
  {
    expect: "safety-data-sheet",
    file: "sds_isopropanol.pdf",
    pages: 11,
    title: "Safety Data Sheet",
    body: [
      "Safety Data Sheet",
      "Section 1: Identification. Product: Isopropyl alcohol 99.9%",
      "Section 2: Hazards identification. Highly flammable liquid and vapour.",
      "Section 4: First aid measures. IF IN EYES: rinse cautiously with water.",
      "Section 6: Accidental release measures. Eliminate all ignition sources.",
      "Section 11: Toxicological information. May cause drowsiness or dizziness.",
      "According to Regulation (EC) No 1907/2006 (REACH).",
    ],
  },
  {
    expect: "certificate",
    file: "first_aid_cert.pdf",
    title: "Certificate of Completion",
    body: [
      "Certificate of Completion",
      "This is to certify that",
      "K. Osei",
      "has successfully completed the Emergency First Aid at Work course",
      "held on 20 May 2024 at the Elmswell Training Centre.",
      "Valid for three years from the date of issue.",
      "Instructor: P. Marsh    Certificate no: EFAW-20240520-081",
    ],
  },
  {
    expect: "transcript",
    file: "uw_transcript.pdf",
    pages: 2,
    title: "Official Transcript",
    body: [
      "Official Transcript",
      "Office of the Registrar, University of Washington",
      "Student: John Smith    Student ID: 1735522",
      "Program: B.S. Computer Science",
      "CSE 142 Programming I      4.0 credits   grade 3.8",
      "CSE 143 Programming II     4.0 credits   grade 3.9",
      "MATH 126 Calculus III      5.0 credits   grade 3.6",
      "Cumulative GPA: 3.72    Degree conferred: 10 June 2017",
    ],
  },
  {
    expect: "research-paper",
    file: "streaming_paper.pdf",
    pages: 12,
    title: "Adaptive Backpressure in Distributed Stream Processors",
    body: [
      "Adaptive Backpressure in Distributed Stream Processors",
      "J. Smith, L. Chen - Meridian Labs",
      "Abstract - We present an adaptive backpressure protocol that reduces tail",
      "latency by 41% under skewed load. In this paper we formalise the problem,",
      "prove stability bounds, and evaluate on three production traces.",
      "1. Introduction. Stream processors must balance throughput against latency.",
      "Corresponding author: j.smith@meridianlabs.example",
      "References [1] Chen et al. (2021) [2] Okafor and Reyes (2019)",
    ],
  },
  {
    expect: "statement-of-work",
    file: "sow_kestrel_phase2.pdf",
    pages: 6,
    title: "Statement of Work",
    body: [
      "Statement of Work",
      "This Statement of Work is entered into under the Master Services Agreement",
      "dated 1 March 2024 between Kestrel Ltd and Corven Holdings.",
      "Scope of work: phase 2 accessibility audit of the claims portal.",
      "Deliverables: audit report, remediation backlog, retest of priority issues.",
      "Period of performance: 1 July - 30 September 2024.",
      "Acceptance criteria: all priority-1 issues verified fixed on retest.",
      "Fees: time and materials, capped at 48,000.",
    ],
  },
  {
    expect: "proposal",
    file: "proposal_fleet_audit.pdf",
    pages: 8,
    title: "Proposal",
    body: [
      "Proposal for Meridian Logistics",
      "Fleet inspection digitisation - our proposed approach",
      "Scope of work: replace paper inspection sheets across 14 depots with digital",
      "checklists, defect triage, and parts integration.",
      "Timeline: 12 weeks from kick-off, phased by region.",
      "Investment: 86,000 fixed fee, including training.",
      "Acceptance of this proposal: sign below to authorise the work.",
      "This proposal is valid for 60 days.",
    ],
  },
  {
    expect: "form",
    file: "trip_permission.pdf",
    title: "School Trip Permission Slip",
    body: [
      "School Trip Permission Slip",
      "Elmswell Primary School - Year 4 visit to the Natural History Museum",
      "Date of trip: 9 July 2024. Cost: 12.50, payable via the school office.",
      "Please print clearly and return by 28 June.",
      "Child's name: ______________________  Class: ________",
      "I give permission for my child to attend the trip.",
      "Parent/guardian signature: ______________________",
      "Emergency contact number: ______________________",
      "For office use only: payment received [ ]  consent received [ ]",
    ],
  },
  {
    expect: "invitation",
    file: "wedding_invite.pdf",
    title: "You are cordially invited",
    body: [
      "You are cordially invited",
      "to celebrate the marriage of",
      "Amara Diallo and Daniel Reyes",
      "Saturday the fourteenth of September, two thousand twenty-four",
      "at three o'clock in the afternoon",
      "The Orangery, Holland Park, London",
      "Reception to follow. Kindly respond by the first of August.",
    ],
  },
  {
    expect: "email-thread",
    file: "re_re_roofing_tender.pdf",
    pages: 3,
    title: "RE: RE: Roofing tender",
    body: [
      "From: R. Holt <rholt@example.org>",
      "Sent: Tuesday 14 May 2024 09:12",
      "To: D. Cole <dcole@example.org>",
      "Subject: RE: RE: Roofing tender",
      "Agreed - let's shortlist the two lowest compliant bids.",
      "-----Original Message-----",
      "From: D. Cole    Sent: Monday 13 May 2024 16:40",
      "On Mon, 13 May 2024, R. Holt wrote:",
      "> The committee meets Tuesday; can you circulate the tender summary?",
      "Sent from my iPhone",
    ],
  },
  {
    expect: "warranty-document",
    file: "kb170_warranty.pdf",
    title: "Warranty Certificate",
    body: [
      "Warranty Certificate",
      "Rapid-boil kettle, model KB-170",
      "This limited warranty covers defects in materials and workmanship for a",
      "warranty period of two years from the date of purchase.",
      "This warranty does not cover damage from misuse, descaling neglect, or",
      "commercial use.",
      "To make a claim, contact support with your receipt and serial number.",
    ],
  },
  // --- scanned documents: no text layer, the filename is the only signal ---
  {
    expect: "invoice",
    file: "invoice_4412_scan.pdf",
    title: "",
    body: [],
  },
  {
    expect: "bank-statement",
    file: "hsbc_bank_statement_jan.pdf",
    title: "",
    body: [],
  },
  // --- pdf.js extraction artifacts: NBSP separators, curly quotes, fi/fl ligatures ---
  {
    expect: "invoice",
    file: "doc.pdf",
    nbsp: true,
    title: "Tax Invoice",
    body: [
      "Tax Invoice",
      "Invoice Number: INV-2024-3319    Invoice Date: 12 June 2024",
      "Bill To: Harbour Cafe Ltd",
      "Consulting services — May ... 1,400.00",
      "Invoice Total: 1,400.00. Remit payment to the account below.",
    ],
  },
  {
    expect: "nda",
    file: "doc.pdf",
    pages: 3,
    title: "Conﬁdentiality Agreement",
    body: [
      "Conﬁdentiality Agreement",
      "This conﬁdentiality agreement is made between the Disclosing Party and the",
      "Receiving Party. Each party’s conﬁdential information shall be held in",
      "strict conﬁdence and used only to evaluate the proposed relationship.",
      "The obligations survive for ﬁve years from the date of disclosure.",
    ],
  },
  // --- additional common types ---
  {
    expect: "tax-return",
    file: "1040_2023.pdf",
    pages: 4,
    title: "U.S. Individual Income Tax Return",
    body: [
      "Form 1040 - U.S. Individual Income Tax Return 2023",
      "Filing status: married filing jointly",
      "1a Total amount from Form(s) W-2, box 1 ... 72,450",
      "11 Adjusted gross income ... 71,200",
      "16 Tax ... 8,102",
      "25 Federal income tax withheld ... 9,812",
      "34 Refund: amount you overpaid ... 1,710",
    ],
  },
  {
    expect: "subscription-confirmation",
    file: "apple_receipt.pdf",
    title: "Your receipt from Apple",
    body: [
      "Your receipt from Apple",
      "Subscription: CloudSync Pro, monthly",
      "Renewal price: 2.99. Next billing date: 12 July 2024.",
      "Your subscription will automatically renew each month until cancelled.",
      "Manage your subscription in Settings.",
    ],
  },
  {
    expect: "donation-receipt",
    file: "gift_aid_receipt.pdf",
    title: "Donation Receipt",
    body: [
      "Donation Receipt",
      "Riverside Foodbank, registered charity 1122334",
      "Thank you for your donation of 50.00 received on 3 June 2024.",
      "No goods or services were provided in exchange for this contribution.",
      "Gift Aid: as a UK taxpayer, your donation is worth 25% more at no cost to you.",
    ],
  },
  {
    expect: "waybill",
    file: "shipping_label_1Z999.pdf",
    title: "Shipping label",
    body: [
      "Shipping label",
      "UPS Ground    Tracking: 1Z 999 AA1 01 2345 6784",
      "Ship from: Brightline Packaging, Leeds LS10 1AB",
      "Ship to: A. Diallo, 14 Fern Road, Bristol BS1 5TR",
      "Weight: 2.4 kg    Billing: P/P",
      "Package 1 of 1",
    ],
  },
  {
    expect: "customs-declaration",
    file: "cn22.pdf",
    title: "Customs Declaration CN22",
    body: [
      "Customs Declaration CN22",
      "May be opened officially",
      "Description of contents: cotton t-shirts (2)",
      "HS tariff number: 610910    Country of origin: Portugal",
      "Declared value: 38.00    Reason for export: sale of goods",
      "I certify that the particulars given are correct.",
    ],
  },
  {
    expect: "medical-report",
    file: "clinic_letter_rp.pdf",
    pages: 2,
    title: "Clinical Assessment",
    body: [
      "Clinical Assessment",
      "Patient: R. Patel    NHS no: 943 476 5919    Seen: 21 May 2024",
      "Presenting complaint: six weeks of intermittent chest tightness on exertion.",
      "History of present illness: symptoms began after a respiratory infection;",
      "no orthopnoea; exercise tolerance reduced to one flight of stairs.",
      "Past medical history: hypertension, well controlled.",
      "On examination: chest clear, heart sounds normal, BP 132/84.",
      "Impression and plan: likely post-viral; arrange ECG and review in 4 weeks.",
    ],
  },
  {
    expect: "referral-letter",
    file: "referral_cardiology.pdf",
    title: "Referral Letter",
    body: [
      "Referral Letter",
      "Dear colleague,",
      "Re: R. Patel, DOB 14/02/1988",
      "Reason for referral: exertional chest tightness with an abnormal baseline ECG.",
      "I am referring this patient to the rapid access chest pain clinic.",
      "Please see this patient within two weeks given the symptom pattern.",
      "Referring GP: Dr H. Adeyemi, Riverside Practice",
    ],
  },
  {
    expect: "consent-form",
    file: "consent_gastroscopy.pdf",
    title: "Consent Form",
    body: [
      "Consent Form",
      "Procedure: diagnostic gastroscopy",
      "I confirm the procedure, its benefits, and its risks have been explained to me.",
      "I have had the opportunity to ask questions and all my questions have been",
      "answered to my satisfaction.",
      "I consent to the procedure described above.",
      "Patient signature: ____________    Person taking consent: ____________",
    ],
  },
  {
    expect: "benefits-summary",
    file: "pension_statement_2024.pdf",
    pages: 3,
    title: "Annual Benefit Statement",
    body: [
      "Annual Benefit Statement",
      "Scheme: Northgate Group Personal Pension",
      "Statement date: 5 April 2024",
      "Your pension pot on 5 April 2024: 48,210",
      "Contributions received this year: 4,860 (you 2,430, employer 2,430)",
      "Projected pot at age 67: 214,000 in today's money.",
      "This statement is provided annually; it is not a guarantee.",
    ],
  },
  {
    expect: "grade-report",
    file: "y4_summer_report.pdf",
    title: "End of Year Report",
    body: [
      "End of Year Report - Year 4",
      "Pupil: T. Diallo    Class: 4B    Attendance: 96.8%",
      "Reading: working at greater depth. Thoughtful, fluent, and adventurous choices.",
      "Writing: working towards the expected standard; handwriting is improving.",
      "Mathematics: expected standard. Confident with fractions and perimeter.",
      "Effort grade: excellent across all subjects.",
      "Teacher: Ms P. Whitlow    Headteacher: Mr J. Okafor",
    ],
  },
  {
    expect: "course-syllabus",
    file: "cse143_syllabus.pdf",
    pages: 5,
    title: "Course Syllabus",
    body: [
      "Course Syllabus",
      "CSE 143: Computer Programming II, Autumn 2024",
      "Learning objectives: implement and analyse core data structures; write",
      "well-tested object-oriented programs.",
      "Required textbook: Building Java Programs, 5th edition.",
      "Grading: homework 40%, midterm 25%, final 35%.",
      "Week 1: recursion. Week 2: linked lists. Week 3: stacks and queues.",
      "Office hours: Tuesdays 2-4pm, Allen Center 303.",
    ],
  },
  {
    expect: "datasheet",
    file: "lm317_datasheet.pdf",
    pages: 22,
    title: "LM317 Adjustable Regulator",
    body: [
      "LM317 3-Terminal Adjustable Regulator",
      "1 Features: output voltage range adjustable from 1.25V to 37V.",
      "6 Specifications",
      "6.1 Absolute maximum ratings over operating temperature range",
      "6.3 Recommended operating conditions",
      "6.5 Electrical characteristics",
      "7.2 Typical application circuit: adjustable voltage regulator with protection diodes.",
      "8 Pin configuration and functions: ADJ, OUT, IN.",
    ],
  },
  {
    expect: "incident-report",
    file: "ir_2024_007.pdf",
    pages: 6,
    title: "Security Incident Report",
    body: [
      "Security Incident Report IR-2024-007",
      "Severity: SEV-2    Status: closed",
      "Summary: credential stuffing against the customer login endpoint.",
      "Timeline: detected 02:14 UTC by rate-limit alerting; contained 03:05 UTC.",
      "Containment and eradication: blocked source ASNs, forced resets for 112 accounts.",
      "Indicators of compromise: IP list attached; no data exfiltration observed.",
      "Follow-ups: roll out WebAuthn, tighten per-IP limits.",
    ],
  },
  {
    expect: "audit-report",
    file: "soc2_type2_2024.pdf",
    pages: 48,
    title: "SOC 2 Type II Report",
    body: [
      "SOC 2 Type II Report",
      "System and Organization Controls report on Kestrel Ltd's audit platform.",
      "Independent service auditor's report for the period 1 April 2023 to 31 March 2024.",
      "Applicable trust services criteria: security, availability, confidentiality.",
      "Section 3: description of the system. Section 4: tests of controls and results.",
      "In our opinion, controls were suitably designed and operated effectively.",
    ],
  },
  // A US-style resume with bare section headings, no CV title, and no LinkedIn URL.
  {
    expect: "resume",
    file: "jordan_avery_2024.pdf",
    title: "JORDAN AVERY",
    body: [
      "JORDAN AVERY",
      "Portland, OR | (503) 555-0142 | j.avery@example.com",
      "EXPERIENCE",
      "Operations Manager, Cascade Outfitters    2019 - Present",
      "- Run daily operations for a 40-person retail and rental business",
      "- Cut inventory shrinkage 18% by introducing weekly cycle counts",
      "Assistant Manager, Trailhead Sports    2015 - 2019",
      "EDUCATION",
      "B.A. Business Administration, University of Oregon, 2015",
      "SKILLS",
      "Scheduling, budgeting, vendor negotiation, POS systems",
    ],
  },
  // --- negative controls: must stay unlabelled ---
  {
    expect: "",
    file: "weekend_notes.pdf",
    title: "Weekend Notes",
    body: [
      "The weather was clear on Saturday so we walked along the river and stopped",
      "for coffee near the old bridge before the rain started in the afternoon.",
      "On Sunday we tidied the garden, read for a while and then cooked a simple",
      "dinner with the vegetables that were still fresh from last week.",
      "Nothing else of note happened, and it was a quiet couple of days overall.",
    ],
  },
  {
    expect: "",
    file: "contrato.pdf",
    title: "CONTRATO DE ARRENDAMIENTO",
    body: [
      "El presente contrato de arrendamiento se celebra entre el arrendador y el",
      "arrendatario para el alquiler de la vivienda situada en la direccion indicada.",
      "El arrendatario se compromete a pagar la renta mensual dentro de los primeros",
      "cinco dias de cada mes segun las condiciones que se establecen en este documento.",
      "Ambas partes firman este contrato en senal de conformidad con sus clausulas.",
    ],
  },
  // --- extended coverage: every remaining emitted label + new-rule checks ---
  {
    expect: "remittance-advice",
    file: "remit_20240418.pdf",
    title: "Remittance Advice",
    body: [
      "Remittance Advice",
      "From: Harlow Manufacturing Ltd    To: Brightline Packaging Ltd",
      "Payment date: 18 April 2024    Payment reference: HM-2024-0418",
      "BACS payment to sort code 20-00-00, account ending 4471.",
      "The following invoices are covered by this payment:",
      "INV-2201    12 March 2024    1,480.00",
      "INV-2214    28 March 2024      960.00",
      "Amount remitted: 2,440.00",
      "Your account has been credited accordingly. No action is required.",
    ],
  },
  {
    expect: "credit-note",
    file: "CN-0092.pdf",
    title: "Credit Note",
    body: [
      "Credit Note",
      "Credit note number: CN-0092    Credit note date: 6 June 2024",
      "Customer: Harbour Cafe Ltd    Original invoice: INV-2024-014",
      "Reason for credit: goods returned - two chairs received damaged.",
      "Item: Bistro chair (oak)    Qty: 2    Unit price: 85.00",
      "Total credit: 170.00",
      "Your account has been credited with the amount shown above.",
    ],
  },
  {
    expect: "loan-agreement",
    file: "loan_agreement_final.pdf",
    pages: 9,
    title: "Loan Agreement",
    body: [
      "Loan Agreement",
      "This Loan Agreement is made between Fairview Capital LLC (the Lender)",
      "and Meadowbrook Joinery Ltd (the Borrower).",
      "1. Principal amount. The Lender agrees to advance the principal amount of",
      "$150,000 to the Borrower on the terms set out below.",
      "2. Interest. Interest shall accrue on the outstanding balance at a rate of",
      "7.5% per annum, calculated daily.",
      "3. Repayment. The Borrower shall repay the loan in accordance with the",
      "repayment schedule in Schedule 1, over sixty equal monthly instalments.",
      "4. Default. Each of the following is an event of default: failure to pay any",
      "sum within fourteen days of its due date, or breach of any obligation herein.",
      "Signed for and on behalf of the Borrower and the Lender.",
    ],
  },
  {
    expect: "letter",
    file: "important_account_information.pdf",
    title: "Important information about your account",
    body: [
      "Important information about your account",
      "Dear account holder,",
      "We are writing to inform you about changes to your account that take effect",
      "from 1 September 2024. This letter confirms that your everyday banking",
      "will continue as normal and there is nothing you need to do.",
      "The changes to your interest rate are set out in the enclosed leaflet, and",
      "your account with us will keep the same sort code and account number.",
      "Thank you for banking with us.",
      "Yours faithfully,",
      "Customer Services Team",
    ],
  },
  {
    expect: "board-report",
    file: "board_pack_q2.pdf",
    pages: 18,
    title: "Board Pack",
    body: [
      "Board Pack",
      "Quarterly board meeting of Northwind Trading Ltd, 20 June 2024.",
      "These confidential board materials have been prepared for the board and",
      "distributed to the directors one week ahead of the meeting.",
      "Contents: CEO overview, KPI review, finance update, people update, and",
      "items for board discussion including the proposed warehouse lease.",
      "Strategic priorities remain unchanged from the March meeting.",
      "Appendix B sets out the management accounts for the quarter.",
    ],
  },
  {
    expect: "pitch-deck",
    file: "acme_seed_deck.pdf",
    pages: 14,
    title: "Acme Robotics",
    body: [
      "Acme Robotics",
      "The problem we solve: warehouse picking is slow, error-prone and expensive.",
      "Our solution: a modular picking robot that installs in a weekend.",
      "Total addressable market: $8.4B across e-commerce fulfilment.",
      "Traction to date: 11 paying customers, 240% net revenue retention.",
      "Why now: labour shortages and cheap depth sensors change the economics.",
      "Meet the team: ex-Amazon robotics and two-time founders.",
      "The ask: we are raising a seed round of $2.5M.",
      "Use of funds: 60% engineering, 25% go-to-market, 15% operations.",
    ],
  },
  {
    expect: "investment-summary",
    file: "investor_update_march.pdf",
    title: "Investor Update",
    body: [
      "Investor Update - March 2024",
      "Dear investors,",
      "Highlights and lowlights: we shipped the v2 dashboard and closed our two",
      "largest deals to date; hiring for the platform team slipped a month.",
      "Key metrics this month: monthly recurring revenue of $86k, up 9% on",
      "February; net new MRR of $7.1k; burn rate steady at $110k.",
      "That leaves fourteen months of runway at the current plan.",
      "How you can help: intros to heads of operations at mid-market 3PLs.",
      "Thank you, as ever, for your support.",
    ],
  },
  {
    expect: "letter-of-intent",
    file: "loi_project_falcon.pdf",
    pages: 4,
    title: "Letter of Intent",
    body: [
      "Letter of Intent",
      "Project Falcon - strictly private and confidential",
      "This letter of intent sets out the indicative terms on which Redwood",
      "Industrial Group would be willing to pursue the acquisition of the",
      "business and assets of Meadowbrook Joinery Ltd.",
      "This letter is non-binding and does not create any obligation on either",
      "party, and any transaction remains subject to definitive agreement.",
      "During the exclusivity period of sixty days the Sellers shall not solicit",
      "offers from any other person, and both parties shall proceed in good",
      "faith negotiations toward completion.",
    ],
  },
  {
    expect: "quarterly-report",
    file: "q3_earnings_release.pdf",
    pages: 8,
    title: "Quarterly Earnings Release",
    body: [
      "Quarterly Earnings Release",
      "Northwind Group reports third quarter results and raises full-year guidance.",
      "Revenue of $412M, up 14% year-over-year; operating margin of 18.2%.",
      "Diluted earnings per share of $0.94, ahead of consensus estimates.",
      "The company beat analyst estimates on both revenue and earnings.",
      "Management will host a conference call to discuss these results at 5:00pm",
      "Eastern Time today; a replay of the earnings call will be available.",
      "Guidance for the full year: revenue of $1.63B to $1.66B.",
    ],
  },
  {
    expect: "report",
    file: "report_to_cabinet_leisure.pdf",
    pages: 12,
    title: "Report to Cabinet",
    body: [
      "Report to Cabinet",
      "Report of the Director of Communities: future of the Riverside Leisure Centre.",
      "Portfolio holder: Councillor J. Ellis    Wards affected: Castle, Riverside.",
      "Key decision: yes.",
      "The committee is recommended to approve option two, refurbishment in",
      "phases, and it is recommended that officers procure a design partner.",
      "Financial implications: capital cost of 4.2m over two years.",
      "Legal implications: none beyond standard procurement obligations.",
      "Reason for the decision: the centre no longer meets accessibility standards.",
    ],
  },
  {
    expect: "regulatory-filing",
    file: "uksi_2024_0871.pdf",
    pages: 16,
    title: "The Data Protection (Amendment) Regulations 2024",
    body: [
      "Statutory Instruments",
      "2024 No. 871",
      "The Data Protection (Amendment) Regulations 2024",
      "Made 4 June 2024. Laid before Parliament 6 June 2024.",
      "The Secretary of State makes these Regulations in exercise of the powers",
      "conferred by sections 16 and 211 of the Data Protection Act 2018.",
      "1. These Regulations may be cited as the Data Protection (Amendment)",
      "Regulations 2024 and come into force on 1 August 2024.",
      "2. Regulation 4 of the principal Regulations is amended as follows.",
      "Explanatory note: this note is not part of the Regulations.",
    ],
  },
  {
    expect: "appraisal-report",
    file: "409a_valuation_2024.pdf",
    pages: 34,
    title: "409A Valuation Report",
    body: [
      "409A Valuation Report",
      "Prepared for the board of Acme Robotics, Inc.",
      "Valuation date: 31 March 2024.",
      "Purpose: to estimate the fair market value of the company's common stock.",
      "We considered the market approach and the income approach. Under the",
      "income approach we applied a discounted cash flow analysis using a",
      "weighted average cost of capital of 24%.",
      "Under the market approach we performed a comparable company analysis",
      "using the guideline public company method across eight peers.",
      "Concluded fair market value: $2.84 per common share.",
    ],
  },
  {
    expect: "tax-statement",
    file: "cp14_notice.pdf",
    title: "Notice of Assessment",
    body: [
      "Notice of Assessment",
      "Notice date: 12 May 2024    Taxpayer ID ending: 4417",
      "You have unpaid taxes for the 2023 tax year.",
      "Proposed amount due: $1,240.00, which includes a late payment penalty",
      "of $62.00 and interest calculated to the date of this notice.",
      "Amount due immediately: $1,240.00.",
      "If you do not pay by 5 June 2024, additional penalties will apply.",
      "Payment options are listed on the back of this notice.",
    ],
  },
  {
    expect: "court-filing",
    file: "motion_to_dismiss.pdf",
    pages: 11,
    title: "Motion to Dismiss",
    body: [
      "United States District Court for the Northern District of Ohio",
      "Civil Action No. 5:24-cv-00311",
      "Meridian Supply Co., Plaintiff, v. Lakeshore Logistics LLC, Defendant.",
      "Defendant's Motion to Dismiss",
      "Comes now Defendant Lakeshore Logistics LLC, by and through undersigned",
      "counsel, and moves this Court to dismiss the complaint for failure to",
      "state a cause of action, as set out in the memorandum in support filed",
      "herewith. The complaint's prayer for relief seeks damages unavailable",
      "as a matter of law.",
      "Respectfully submitted, /s/ Dana Whitfield, Counsel for Defendant.",
      "Certificate of service: a copy was served on all counsel of record.",
    ],
  },
  {
    expect: "affidavit",
    file: "affidavit_of_residence.pdf",
    title: "Affidavit of Residence",
    body: [
      "Affidavit of Residence",
      "State of Texas, County of Travis.",
      "I, Morgan Reyes, being duly sworn, deposes and says:",
      "1. I am over eighteen years of age and competent to make this affidavit.",
      "2. I have resided at 118 Fern Road, Austin, Texas since March 2019.",
      "3. The facts stated here are true and correct to the best of my knowledge.",
      "Affiant: Morgan Reyes",
      "Subscribed and sworn to before me this 9th day of May 2024.",
      "Notary Public, State of Texas. My commission expires 01/31/2026.",
    ],
  },
  {
    expect: "legal-notice",
    file: "letter_before_action.pdf",
    title: "Letter Before Action",
    body: [
      "Letter Before Action",
      "Dear Mr Hale,",
      "We act for Brightline Packaging Ltd. This is a letter before claim under",
      "the pre-action protocol for debt claims.",
      "Our client is owed 4,860.00 under invoices that remain unpaid despite",
      "repeated reminders. This is our client's final demand for payment.",
      "Unless payment is received within fourteen days we are instructed to",
      "issue proceedings without further notice, and further legal action may",
      "include a claim for interest and costs.",
      "Govern yourself accordingly.",
    ],
  },
  {
    expect: "purchase-agreement",
    file: "asset_purchase_agreement.pdf",
    pages: 64,
    title: "Asset Purchase Agreement",
    body: [
      "Asset Purchase Agreement",
      "by and among Redwood Industrial Group, Inc., as Buyer, and Meadowbrook",
      "Joinery Ltd, as Seller, dated as of 12 July 2024.",
      "Article III sets out the representations and warranties of the Seller,",
      "qualified by the disclosure schedule delivered at signing.",
      "Article II provides for a purchase price adjustment based on closing",
      "working capital, with an escrow amount of $1,500,000 to be held by the",
      "escrow agent for eighteen months.",
      "Article VII sets out the closing conditions, including the absence of any",
      "material adverse effect on the business of the target company.",
    ],
  },
  {
    expect: "shareholder-agreement",
    file: "shareholders_agreement_2024.pdf",
    pages: 28,
    title: "Shareholders' Agreement",
    body: [
      "Shareholders' Agreement",
      "relating to Acme Robotics Ltd, entered into by the persons listed in",
      "Schedule 1 as holders of shares in the company.",
      "5. Transfer of shares. No shareholder may transfer shares except as",
      "permitted by this clause, subject to the pre-emption rights in clause 6.",
      "7. Drag-along rights. If holders of 75% of the shares accept an offer,",
      "they may require every other shareholder to sell on the same terms.",
      "8. Tag-along rights. No transfer may complete unless each minority",
      "shareholder is offered the same price per share.",
      "10. Reserved matters. The consent of investor directors is required for",
      "the matters in Schedule 3, including changes to board composition.",
    ],
  },
  {
    expect: "legal-opinion",
    file: "approved_judgment_hale.pdf",
    pages: 22,
    title: "Approved Judgment",
    body: [
      "Approved Judgment",
      "In the matter of Meridian Supply Co v Lakeshore Logistics.",
      "Before the Honourable Mrs Justice Carey, handed down 14 June 2024.",
      "This is the judgment of the court on the defendant's application.",
      "For the reasons given below, the appeal is dismissed.",
      "The claimant's construction of clause 9 is to be preferred; the",
      "commercial context points firmly in the same direction.",
      "Costs follow the event. Permission to appeal is refused.",
    ],
  },
  {
    expect: "subpoena",
    file: "subpoena_duces_tecum.pdf",
    title: "Subpoena to Produce Documents",
    body: [
      "Subpoena to Produce Documents, Information, or Objects",
      "To: Custodian of Records, Lakeshore Logistics LLC.",
      "You are commanded to produce at the time, date and place set forth below",
      "the documents described in Attachment A.",
      "This subpoena duces tecum is issued in the matter of Meridian Supply Co",
      "v Lakeshore Logistics, pending in the district court.",
      "Place of compliance: 400 Main Street, Suite 210, Cleveland, Ohio.",
      "Return date: 2 August 2024 at 10:00 a.m.",
      "Issued by the clerk of court on application of counsel for the plaintiff.",
    ],
  },
  {
    expect: "settlement-agreement",
    file: "settlement_agreement_reyes.pdf",
    pages: 7,
    title: "Settlement Agreement",
    body: [
      "Settlement Agreement",
      "between Morgan Reyes (the Claimant) and Northwind Trading Ltd",
      "(the Respondent), each a party and together the parties.",
      "The parties desire to resolve all matters between them arising out of",
      "the Claimant's employment, without any admission of liability.",
      "1. The Respondent shall pay the Claimant a settlement sum of 24,000",
      "within 21 days, in full and final settlement of all claims.",
      "2. The Claimant agrees to withdraw the claim before the employment",
      "tribunal and enters into the release of claims in Schedule 1.",
      "3. This agreement was reached following discussions through a",
      "conciliation officer.",
    ],
  },
  {
    expect: "employee-handbook",
    file: "staff_handbook_2024.pdf",
    pages: 48,
    title: "Employee Handbook",
    body: [
      "Employee Handbook",
      "Welcome to the company. This handbook explains what you can expect from",
      "us and what we expect from you.",
      "Code of conduct: we treat colleagues and customers with respect.",
      "Dress code: smart casual, with site rules taking precedence in the yard.",
      "Annual leave: 25 days plus public holidays; sick leave is set out in",
      "section 6 together with reporting requirements.",
      "Your first three months are a probationary period.",
      "The disciplinary procedure and grievance procedure are in section 9,",
      "and our equal opportunity commitments are in section 10.",
      "Working hours are 9:00 to 17:30, Monday to Friday.",
    ],
  },
  {
    expect: "risk-assessment",
    file: "enterprise_risk_register.pdf",
    pages: 12,
    title: "Risk Assessment Report",
    body: [
      "Risk Assessment Report",
      "Enterprise risk register for Northwind Trading Ltd, reviewed quarterly.",
      "Methodology: each risk is scored for likelihood and impact on a five",
      "point scale, before and after controls, and assigned a risk owner.",
      "The risk heat map on page 3 summarises the top twelve risks.",
      "R-04 Supply concentration: inherent risk high; mitigation plan agreed",
      "with procurement; residual risk medium, within our risk appetite.",
      "R-07 Warehouse fire: risk rating severe; sprinkler upgrade underway.",
      "Control effectiveness is tested by internal audit on rotation.",
    ],
  },
  {
    expect: "compliance-document",
    file: "information_security_policy.pdf",
    pages: 18,
    title: "Information Security Policy",
    body: [
      "Information Security Policy",
      "Policy owner: Head of IT Security.    Effective date: 1 May 2024.",
      "Scope: this policy applies to all staff, contractors and systems and",
      "forms part of our information security management system.",
      "Access is granted on the principle of least privilege and reviewed",
      "quarterly, as set out in the access control policy.",
      "Information is handled according to the data classification policy;",
      "the acceptable use policy governs personal use of company systems.",
      "The password policy requires a unique passphrase per system.",
      "This document follows a twelve month policy review cycle.",
    ],
  },
  {
    expect: "questionnaire",
    file: "vendor_security_questionnaire.pdf",
    pages: 9,
    title: "Vendor Security Questionnaire",
    body: [
      "Vendor Security Questionnaire",
      "To be completed by the supplier as part of our vendor risk management",
      "and due diligence questionnaire process.",
      "Please answer yes or no in the response column, adding detail where",
      "relevant to your data handling practices.",
      "Section 3: do you maintain a list of subprocessors, and are they bound",
      "by equivalent contractual obligations?",
      "Section 5: describe any compensating control where a requirement is",
      "not met in full.",
      "This questionnaire is based on the standardized information gathering",
      "format and should take about an hour to complete.",
    ],
  },
  {
    expect: "immunization-record",
    file: "immunization_record_reyes.pdf",
    title: "Immunization Record",
    body: [
      "Immunization Record",
      "Patient name: Alex Reyes    Date of birth: 04/12/2016",
      "Vaccine    Date administered    Administered by    Lot number",
      "DTaP (dose 5)    03/22/2021    Dr. N. Okafor    AC41B",
      "MMR (dose 2)    03/22/2021    Dr. N. Okafor    KL98D",
      "Varicella (dose 2)    03/22/2021    Dr. N. Okafor    MM31A",
      "Hepatitis B (dose 3)    11/02/2017    Dr. N. Okafor    KT77C",
      "Tdap booster due: 2028.",
      "This record was printed from the state immunisation history registry.",
    ],
  },
  {
    expect: "medical-invoice",
    file: "eob_march_2024.pdf",
    title: "Explanation of Benefits",
    body: [
      "Explanation of Benefits",
      "This is not a bill. Keep this statement for your records.",
      "Member: Morgan Reyes    Claim number: 88-4412-07",
      "Provider: Lakeside Family Medicine    Date of service: 03/14/2024",
      "Amount billed: $240.00    Allowed amount: $132.00",
      "Plan paid: $105.60    Coinsurance: $26.40    Copay: $0.00",
      "Patient responsibility: $26.40",
      "Applied to deductible: $0.00    Out-of-pocket maximum met: no.",
      "Your provider may bill you for the patient responsibility shown above.",
    ],
  },
  {
    expect: "discharge-summary",
    file: "discharge_summary_hale.pdf",
    pages: 3,
    title: "Discharge Summary",
    body: [
      "Discharge Summary",
      "Patient: Thomas Hale    NHS number: 943 476 5919",
      "Date of admission: 2 June 2024    Date of discharge: 6 June 2024",
      "Discharge diagnosis: community acquired pneumonia.",
      "Hospital course: the patient responded well to intravenous antibiotics",
      "and was stepped down to oral therapy on day two.",
      "Medications on discharge: amoxicillin 500mg three times daily for five",
      "days; continue regular inhalers.",
      "Condition at discharge: stable, mobilising independently; discharged home.",
      "Follow-up arrangements: chest x-ray in six weeks. Copy to GP.",
    ],
  },
  {
    expect: "insurance-certificate",
    file: "acord_25_certificate.pdf",
    title: "Certificate of Liability Insurance",
    body: [
      "Certificate of Liability Insurance",
      "This certificate is issued as a matter of information only and confers",
      "no rights upon the certificate holder.",
      "Insured: Lakeshore Logistics LLC, 400 Main Street, Cleveland, OH.",
      "Commercial general liability: each occurrence $1,000,000; general",
      "aggregate $2,000,000. Policy number GL-8841-22, ACORD 25 form.",
      "Certificate holder: Meridian Supply Co is named as additional insured",
      "with respect to work performed under contract 2024-118.",
      "Should any of the above described policies be cancelled before the",
      "expiration date thereof, notice will be delivered in accordance with",
      "the policy provisions.",
    ],
  },
  {
    expect: "thesis",
    file: "reyes_phd_thesis.pdf",
    pages: 186,
    title: "Consensus Protocols for Unreliable Networks",
    body: [
      "Consensus Protocols for Unreliable Networks",
      "A thesis submitted in partial fulfilment of the requirements for the",
      "degree of Doctor of Philosophy.",
      "School of Computing, University of Leeds, September 2024.",
      "Thesis supervisor: Professor A. Whitmore.",
      "I hereby declare that this thesis is my own work and has not been",
      "submitted for any other degree; see the declaration of authorship.",
      "Acknowledgements: I thank my supervisor and the systems group.",
      "Abstract: we study agreement under message loss and partition.",
    ],
  },
  {
    expect: "assignment-brief",
    file: "problem_set_4.pdf",
    title: "Problem Set 4",
    body: [
      "Problem Set 4",
      "MATH 2210 Linear Algebra    Due date: Friday 24 May at 5pm",
      "Answer all questions. Show your work for full credit; unsupported",
      "answers receive no marks.",
      "Total marks: 40.",
      "Question 1 (8 marks): find the eigenvalues of the matrix A below.",
      "Question 2 (12 marks): prove that similar matrices share a determinant.",
      "Submit your solutions as a single PDF through the course portal.",
      "Late submissions will lose 10% per day up to three days.",
    ],
  },
  {
    expect: "registration-form",
    file: "student_enrollment_form.pdf",
    title: "Student Enrollment Form",
    body: [
      "Student Enrollment Form",
      "Section A - pupil details: full name, date of birth, year group applied",
      "for, and current or previous school attended.",
      "Section B - parent/guardian details and emergency contacts, including",
      "at least two adults we may call during the school day.",
      "Section C - home language survey: which language is spoken most at home?",
      "Section D - proof of residency: please attach a recent council tax bill",
      "or tenancy agreement showing your home address.",
      "Return the completed admission form to the school office by 15 June.",
    ],
  },
  {
    expect: "lesson-plan",
    file: "lesson_plan_fractions.pdf",
    title: "Lesson Plan",
    body: [
      "Lesson Plan - Year 5 Mathematics - Comparing Fractions",
      "Lesson objective: pupils can compare fractions with unlike denominators.",
      "Success criteria: I can find a common denominator; I can order three",
      "fractions; I can explain my reasoning to a partner.",
      "Key vocabulary: numerator, denominator, equivalent, common multiple.",
      "Starter activity (5 min): match equivalent fraction cards in pairs.",
      "Main activity (30 min): guided practice, then independent questions.",
      "Differentiation: number lines for support; extension into improper",
      "fractions for rapid graspers. Assessment for learning: exit ticket",
      "with three ordering problems collected as the plenary.",
    ],
  },
  {
    expect: "mortgage-document",
    file: "closing_disclosure.pdf",
    pages: 5,
    title: "Closing Disclosure",
    body: [
      "Closing Disclosure",
      "This form is a statement of final loan terms and closing costs.",
      "Borrower: Morgan Reyes    Property: 118 Fern Road, Austin, TX",
      "Loan amount: $312,000    Loan term: 30 years    Fixed rate: 6.25%",
      "Loan-to-value: 80%. Your loan has no prepayment penalty.",
      "Projected payments include amounts held in your escrow account for",
      "property taxes and homeowner's insurance.",
      "The amortization schedule in the appendix shows principal and interest",
      "over the life of the loan; this note is secured by a deed of trust.",
      "Signed at closing alongside the promissory note.",
    ],
  },
  {
    expect: "deed",
    file: "warranty_deed_recorded.pdf",
    title: "Warranty Deed",
    body: [
      "Warranty Deed",
      "Recorded at the request of Travis County Title Co.",
      "The grantor, Evelyn Marsh, a single person, for good and valuable",
      "consideration, grants and conveys to the grantee, Morgan Reyes, the",
      "following described real property in fee simple:",
      "Legal description: Lot 14, Block C, Fernwood Addition, according to the",
      "plat recorded in Volume 88, Page 12, plat records of Travis County.",
      "Filed for record with the county recorder on 21 June 2024.",
    ],
  },
  {
    expect: "property-listing",
    file: "14_fern_road_brochure.pdf",
    title: "14 Fern Road, Bristol",
    body: [
      "14 Fern Road, Bristol",
      "Guide price 425,000. Offers in excess of the guide will be considered.",
      "A well presented three bedroom semi with a south facing garden, fitted",
      "kitchen, and off-street parking for two cars.",
      "Approximately 1,180 sq ft of accommodation over two floors.",
      "Council tax band D. EPC rating C.",
      "Viewing strictly by appointment through the vendor's estate agent.",
      "Open house Saturday 10:00 to 12:00.",
    ],
  },
  {
    expect: "inspection-report",
    file: "home_inspection_fern_rd.pdf",
    pages: 32,
    title: "Home Inspection Report",
    body: [
      "Home Inspection Report",
      "Property: 118 Fern Road, Austin, TX    Inspected: 14 June 2024",
      "Each system is given a condition rating: satisfactory, marginal, or",
      "defective, with photographs in the appendix.",
      "Roof covering: architectural shingle, marginal; several lifted tabs.",
      "Electrical: two bathroom receptacles lack GFCI protection; recommend",
      "evaluation by a licensed electrician.",
      "Crawl space: minor moisture staining at the north wall; downspouts",
      "discharge against the foundation and should be extended.",
      "A summary of deficiencies appears on the final page.",
    ],
  },
  {
    expect: "hoa-document",
    file: "hoa_annual_assessment.pdf",
    title: "Fernwood Homeowners Association",
    body: [
      "Fernwood Homeowners Association",
      "Annual assessment notice for 2024-2025.",
      "Dear owner, the board has approved the budget and the annual assessment",
      "of $640, payable in two instalments; HOA dues fund insurance, common",
      "areas maintenance and the reserve fund.",
      "A special assessment of $150 was approved for pool resurfacing.",
      "Reminder: exterior changes require architectural review before work",
      "begins, per the CC&Rs.",
      "Questions may be directed to the managing agent, Brookside Community",
      "Management.",
    ],
  },
  {
    expect: "application-form",
    file: "planning_application_2024.pdf",
    title: "Planning Application",
    body: [
      "Planning Application",
      "Application for planning permission under the Town and Country Planning",
      "Act 1990.",
      "Proposal: erection of a single storey rear extension and detached",
      "garden studio at 14 Fern Road.",
      "The proposed development falls within the Fernwood conservation area;",
      "a heritage statement accompanies this application.",
      "Please include a site plan at 1:1250 showing the boundary in red.",
      "Case officer use only: application reference and date received.",
      "The planning officer will contact you if further information is needed.",
    ],
  },
  {
    expect: "government-notice",
    file: "foi_response_2024_0441.pdf",
    title: "Freedom of Information Request",
    body: [
      "Freedom of Information Request - Response",
      "Our reference: FOI 2024/0441",
      "Thank you for your request for information about road maintenance",
      "spending. Your request has been handled under the Freedom of",
      "Information Act 2000.",
      "We have located records responsive to your request; extracts are",
      "enclosed. Some material is withheld under section 43, and this",
      "exemption is subject to a public interest test, which we concluded",
      "favours withholding.",
      "You have the right to an internal review, and thereafter may complain",
      "to the Information Commissioner's Office.",
    ],
  },
  {
    expect: "visa-document",
    file: "i797_approval_notice.pdf",
    title: "U.S. Citizenship and Immigration Services",
    body: [
      "U.S. Citizenship and Immigration Services",
      "I-797A, Notice of Action",
      "Case type: I-129, petition for a nonimmigrant worker.",
      "Receipt number: WAC-24-118-50441    Beneficiary: Reyes, Morgan",
      "The petition has been approved. The beneficiary's alien registration",
      "number and the attached I-94 record the new period of admission.",
      "Immigration status: H-1B, valid to 30 September 2027.",
      "Please contact USCIS if any information on this notice is incorrect.",
    ],
  },
  {
    expect: "license",
    file: "premises_licence_ph0441.pdf",
    title: "Premises Licence",
    body: [
      "Premises Licence",
      "Granted under the Licensing Act 2003 by Bristol City Council as the",
      "licensing authority.",
      "Licence number: PL-0441    Premises: The Harbour Cafe, 112 Station Road.",
      "The permit holder is hereby licensed to sell alcohol for consumption on",
      "the premises between 11:00 and 23:00 daily.",
      "The licence is granted subject to the following conditions: CCTV shall",
      "be maintained, and a refusals log kept.",
      "This permit must be displayed prominently at the premises.",
    ],
  },
  {
    expect: "public-notice",
    file: "notice_public_hearing_zoning.pdf",
    title: "Notice of Public Hearing",
    body: [
      "Notice of Public Hearing",
      "Notice is hereby given that the Fernwood Town Council will hold a",
      "public hearing on Tuesday 16 July 2024 at 7:00 pm in the council",
      "chamber, 1 Civic Square.",
      "The purpose of the hearing is to receive comment on the proposed",
      "amendment to the zoning bylaw for the Station Road corridor.",
      "All interested persons may appear and be heard, and written comments",
      "may be filed with the clerk before the hearing.",
      "Published by authority of the town clerk.",
    ],
  },
  {
    expect: "analytics-report",
    file: "labour_market_bulletin.pdf",
    pages: 18,
    title: "Statistical Bulletin",
    body: [
      "Statistical Bulletin",
      "Labour market overview, UK: July 2024.",
      "Source: Office for National Statistics.",
      "The employment rate was 74.6%, up 0.2 percentage points quarter on",
      "quarter and broadly flat year on year, seasonally adjusted.",
      "Estimates are subject to sampling error; confidence intervals are",
      "shown in the accompanying data tables.",
      "Next publication date: 13 August 2024.",
      "These figures are designated national statistics.",
    ],
  },
  {
    expect: "grant-agreement",
    file: "notice_of_award_r01.pdf",
    title: "Notice of Award",
    body: [
      "Notice of Award",
      "Federal award identification number: R01-HL-158812.",
      "Recipient: University of Leeds    Award amount: $412,000.",
      "Assistance listing number: 93.837.",
      "Period of performance: 1 September 2024 to 31 August 2027.",
      "This award is subject to the terms and conditions of the grant,",
      "including the reporting requirements in Section IV.",
      "Grant number and document number must be quoted on all drawdown",
      "requests. Authorized organizational representative: Dr P. Shah.",
    ],
  },
  {
    expect: "tender-document",
    file: "itt_fleet_services.pdf",
    pages: 42,
    title: "Invitation to Tender",
    body: [
      "Invitation to Tender",
      "Provision of fleet maintenance services, reference ITT-2024-081.",
      "Section 2, instructions to tenderers: tenders must be submitted through",
      "the e-procurement portal; the submission deadline is 12:00 noon on",
      "30 August 2024. Clarification questions close ten days earlier.",
      "Section 3 sets out the scope of requirements, including response times",
      "and workshop standards.",
      "Award will be to the most economically advantageous tender against the",
      "evaluation criteria: 60% quality, 40% price.",
      "A pre-qualification questionnaire must accompany each submission.",
    ],
  },
  {
    expect: "sales-proposal",
    file: "tender_response_fleet.pdf",
    pages: 36,
    title: "Tender Response",
    body: [
      "Tender Response",
      "Provision of fleet maintenance services, reference ITT-2024-081.",
      "We are pleased to submit our tender in response to your invitation.",
      "Our technical response demonstrates full coverage of the scope, and the",
      "compliance matrix at Appendix A confirms we are fully compliant with",
      "every mandatory requirement.",
      "The pricing schedule at Appendix B sets out fixed rates for the first",
      "two years.",
      "Our proposed approach pairs a dedicated account manager with a mobile",
      "technician team based within eight miles of your depot.",
    ],
  },
  {
    expect: "supply-order",
    file: "purchase_requisition_2214.pdf",
    title: "Purchase Requisition",
    body: [
      "Purchase Requisition",
      "Requisition number: REQ-2214    Requisition date: 3 July 2024",
      "Requested by: Facilities    Budget holder: J. Okafor",
      "Cost centre: FAC-110    Budget code: 5400-EQ",
      "Justification for purchase: replacement of the workshop compressor,",
      "which failed its service inspection.",
      "Preferred supplier: Brightline Industrial Supplies.",
      "Item: 90L belt-drive compressor    Qty: 1    Estimated cost: 1,140.00",
      "Approval routing: budget holder, then procurement.",
    ],
  },
  {
    expect: "grant-application",
    file: "community_fund_application.pdf",
    pages: 9,
    title: "Grant Application",
    body: [
      "Grant Application",
      "Funding opportunity: Community Facilities Fund 2024.",
      "Applicant organisation: Fernwood Sports Association, registered",
      "charity 1148812.",
      "Project summary: refurbish the pavilion kitchen and accessible toilet.",
      "Amount requested: 24,500. We are applying for 70% of project costs,",
      "with match funding of 10,500 secured from club reserves.",
      "Outcomes and milestones: works complete by March 2025; open kitchen",
      "sessions for four community groups per week from April.",
      "Declaration signed by two trustees.",
    ],
  },
  {
    expect: "technical-drawing",
    file: "GA-1104_rev_C.pdf",
    title: "General Arrangement",
    body: [
      "General Arrangement - Conveyor Frame Assembly",
      "Drawing number GA-1104    Revision C    Scale 1:10    Sheet 1 of 2",
      "Third angle projection. Do not scale. Work to figured dimensions only.",
      "All dimensions in millimetres unless noted otherwise.",
      "Break all sharp edges 0.5 x 45 degrees.",
      "Material: S275 structural steel, hot dip galvanised after fabrication.",
      "Drawn by: MR    Checked by: TH    Approved: 21/06/2024",
      "Issued for construction.",
    ],
  },
  {
    expect: "bill-of-materials",
    file: "bom_ctrl_board_a3.pdf",
    title: "Bill of Material",
    body: [
      "Bill of Material - Controller Board, Assembly CTRL-0301 Rev A3",
      "Top level assembly: CTRL-0301    Qty per assembly shown per unit.",
      "Ref designator    Manufacturer part number    Description    Qty",
      "C1-C8    GRM188R71C104KA01    100nF 0402 X7R    8",
      "R12    ERJ-3EKF1002V    10k 0603 1%    1",
      "U4    STM32G071KBU6    MCU, 64k flash    1",
      "J2    Do not populate - programming header, test builds only.",
      "Reference designator order follows the assembly drawing.",
    ],
  },
  {
    expect: "safety-procedure",
    file: "sop_014_lockout.pdf",
    title: "Standard Operating Procedure",
    body: [
      "Standard Operating Procedure SOP-014: Conveyor Lockout and Cleaning",
      "Purpose: safe isolation of the packing conveyor for scheduled cleaning.",
      "A permit to work is required before starting; the shift supervisor",
      "delivers a toolbox talk covering this procedure at the start of shift.",
      "Personal protective equipment: cut-resistant gloves and safety glasses.",
      "Sequence of work: isolate at the local breaker, apply personal lock and",
      "tag, verify zero energy, then clean per the schedule.",
      "Control measures: an exclusion zone is marked while guards are off.",
      "First aid arrangements are posted at the workshop entrance.",
    ],
  },
  {
    expect: "test-report",
    file: "mill_cert_heat_88412.pdf",
    title: "Mill Test Certificate",
    body: [
      "Mill Test Certificate",
      "Certificate number: MTC-2024-1180    Standard: EN 10204 3.1",
      "Product: S355J2 structural plate, 12mm.    Heat number: 88412.",
      "Cast number: 88412-2.",
      "Chemical composition (%): C 0.16, Si 0.35, Mn 1.42, P 0.012, S 0.008.",
      "Mechanical properties: yield strength 372 MPa, tensile strength",
      "528 MPa, elongation 24%.",
      "Charpy impact at -20C: 41J average, batch tested.",
      "We certify the material supplied conforms to the order requirements.",
    ],
  },
  {
    expect: "quality-report",
    file: "fai_report_ctrl0301.pdf",
    title: "First Article Inspection Report",
    body: [
      "First Article Inspection Report",
      "Part: mounting bracket BRK-2210 Rev B    Inspection lot: 24-0611",
      "Purpose: dimensional inspection of the first production article against",
      "the drawing, using the sampling plan in QP-07.",
      "Characteristic 4: hole spacing 42.00 +/- 0.10, measured 42.06, pass.",
      "Characteristic 9: flatness 0.20 max, measured 0.31, out of tolerance.",
      "Disposition: non-conformance NC-118 raised; use-as-is rejected; rework",
      "and re-present for final inspection.",
      "Inspected by: T. Hale    Acceptance criteria: drawing plus QP-07.",
    ],
  },
  {
    expect: "return-authorization",
    file: "rma_return_label.pdf",
    title: "Return Merchandise Authorization",
    body: [
      "Return Merchandise Authorization",
      "RMA number: RMA-88412    Order: 2024-1180",
      "Return reason: wrong size.",
      "Return instructions: pack the item in its original packaging, include",
      "this sheet, and affix this label to the outside of the box.",
      "The enclosed prepaid return label covers shipping; drop the parcel at",
      "any service point within 30 days.",
      "Refunds are processed by the returns department within five working",
      "days of receipt.",
    ],
  },
  {
    expect: "presentation",
    file: "qbr_slides_q2.pdf",
    pages: 22,
    meta: { producer: "Microsoft PowerPoint for Microsoft 365" },
    title: "Quarterly Business Review",
    body: [
      "Quarterly Business Review",
      "Agenda: performance recap, customer health, roadmap, open actions.",
      "In this presentation we cover Q2 results and the outlook for Q3.",
      "Key takeaways: renewals held at 96%, onboarding time halved, and the",
      "new reporting module is the most requested add-on.",
      "Customer health: two accounts at risk, recovery plans in flight.",
      "Q&A",
      "Thank you for your attention.",
    ],
  },
  {
    expect: "brochure",
    file: "spring_offers_flyer.pdf",
    title: "Fernwood Garden Services",
    body: [
      "Fernwood Garden Services",
      "Why choose us? Fully insured, local, and rated 4.9 across 300 reviews.",
      "Spring tidy-ups, hedge cutting, lawn treatment plans and patio cleaning.",
      "Features and benefits: fixed prices, no contract, satisfaction",
      "guaranteed on every visit.",
      "Limited time offer: 20% off your first lawn treatment.",
      "Book your free consultation today - call us today on 0117 946 0000 or",
      "visit our website for a free quote.",
      "Bring this flyer to receive the discount. No obligation.",
    ],
  },
  {
    expect: "business-plan",
    file: "business_plan_2024.pdf",
    pages: 26,
    title: "Business Plan",
    body: [
      "Business Plan",
      "Harbour Roastery Ltd, 2024 to 2027.",
      "Executive summary: a speciality coffee roastery supplying cafes across",
      "the south west, expanding into direct subscriptions.",
      "Company description: founded 2021; roastery and training room in Bristol.",
      "Market analysis: the regional speciality segment is growing 11% a year;",
      "our target market is independent cafes within 90 minutes.",
      "SWOT analysis and competitive landscape are set out in section 4.",
      "Financial projections: revenue of 640k in year one rising to 1.1m in",
      "year three, with break-even analysis at month 14.",
      "Funding requirements: 180k for a second roaster and packing line.",
      "Revenue model: wholesale contracts plus consumer subscriptions.",
    ],
  },
  {
    expect: "organization-chart",
    file: "org_chart_july.pdf",
    title: "Organisation Chart",
    body: [
      "Organisation Chart - Northwind Trading Ltd, July 2024",
      "This chart shows reporting lines and department structure after the",
      "June reorganisation; headcount is shown in brackets for each team.",
      "Chief Executive",
      "Operations Director - direct reports: warehouse manager, fleet",
      "manager, facilities lead. The warehouse manager reports to the",
      "Operations Director with a team of 24.",
      "Finance Director - direct reports: financial controller, payroll lead.",
      "The reporting structure for the interim data team is under review.",
    ],
  },
  {
    expect: "technical-specification",
    file: "srs_dispatch_v2.pdf",
    pages: 34,
    title: "Software Requirements Specification",
    body: [
      "Software Requirements Specification",
      "Dispatch Planning System, version 2.0. This document specifies the",
      "functional requirements and non-functional requirements for the",
      "dispatch planner used by the operations team.",
      "Intended audience: developers, testers and the product owner.",
      "Normative references: RFC 2119 key words; see terms and definitions.",
      "FR-12: the system shall comply with the routing rules in Appendix C.",
      "NFR-3: page loads shall complete within two seconds at the 95th",
      "percentile.",
      "Revision history and acceptance criteria appear at the end of this",
      "document.",
    ],
  },
  {
    expect: "patent",
    file: "US10884412.pdf",
    pages: 24,
    title: "United States Patent",
    body: [
      "United States Patent",
      "Patent number: US 10,884,412 B2    Date of patent: Jan 5, 2021",
      "Field of the invention: the present invention relates to modular",
      "conveyor systems for warehouse automation.",
      "Background of the invention: existing pickers require fixed rails.",
      "Summary of the invention: a drive unit with a detachable guide.",
      "Brief description of the drawings: FIG. 1 shows the drive unit;",
      "FIG. 2 shows the guide in a released position.",
      "In one embodiment, the preferred embodiment uses a magnetic coupling",
      "distinguishing over the prior art. References cited appear on the",
      "cover page.",
      "What is claimed is: 1. A conveyor drive unit comprising a housing...",
    ],
  },
  {
    expect: "api-documentation",
    file: "dispatch_api_reference.pdf",
    pages: 58,
    title: "API Reference",
    body: [
      "API Reference",
      "Dispatch Planning API, version 2.3. See the changelog and release",
      "notes for differences from 2.2, including known issues.",
      "Authentication: pass your API key in the Authorization header. The",
      "sandbox base URL is http://localhost:8080 when using the emulator.",
      "POST /routes - create a route. Query parameters: dryRun (boolean).",
      "The request body accepts a JSON route plan; the response body returns",
      "the planned stops with ETAs.",
      "Configuration: set the DISPATCH_ENV environment variable, or use the",
      "configuration file described in the developer guide. A command line",
      "client is available for scripting.",
    ],
  },
  {
    expect: "license-agreement",
    file: "license_certificate_pro.pdf",
    title: "License Certificate",
    body: [
      "License Certificate",
      "Product: FlowChart Studio Professional    License type: perpetual",
      "license with twelve months of updates.",
      "Licensed to: Northwind Trading Ltd    Number of seats: 25",
      "License key: XXXXX-XXXXX-XXXXX-88412    Serial number: 118812",
      "Maintenance expires: 31 July 2025.",
      "How to activate: open Help, choose Enter activation code, and paste",
      "the license key above. Activation instructions for offline machines",
      "are on the reverse.",
      "Keep this certificate for your records.",
    ],
  },
  {
    expect: "gift-certificate",
    file: "gift_voucher_50.pdf",
    title: "Gift Voucher",
    body: [
      "Gift Voucher",
      "The Harbour Cafe",
      "This voucher entitles the bearer to fifty pounds toward food and drink.",
      "Voucher code: HC-4412-GIFT    Value: 50.00",
      "To redeem, present this voucher at the till; redeemable at our Station",
      "Road cafe only.",
      "Valid until 30 June 2025. Not redeemable for cash; no cash value if",
      "lost or expired.",
      "From: Aunt Priya    To: Sam - happy graduation!",
    ],
  },
  {
    expect: "confirmation-letter",
    file: "appointment_confirmation_dental.pdf",
    title: "Appointment Confirmation",
    body: [
      "Appointment Confirmation",
      "Dear Morgan Reyes,",
      "Your appointment has been confirmed with Dr Okafor at Fernwood Dental.",
      "Appointment date: Tuesday 23 July 2024    Appointment time: 09:40",
      "Please arrive ten minutes early with a list of current medications.",
      "If you are unable to attend, you can cancel or reschedule up to 24",
      "hours in advance without charge; to reschedule call 0117 946 0001.",
      "Failure to attend without notice may incur a fee.",
      "We look forward to seeing you.",
    ],
  },
  {
    expect: "waybill",
    file: "bill_of_lading_88412.pdf",
    title: "Bill of Lading",
    body: [
      "Straight Bill of Lading",
      "Carrier: Lakeshore Logistics LLC    Pro number: 8841-2214",
      "Shipper: Brightline Packaging Ltd, Unit 4, Riverside Estate, Leeds.",
      "Consignee: Northwind Trading Ltd, 12 Dock Street, Hull.",
      "6 pallets, corrugated cartons, 1,420 kg, freight charges collect.",
      "Received in apparent good order for carriage subject to the conditions",
      "on the reverse.",
      "Shipper signature: J. Mills    Driver: T. Hale    Trailer: 4471",
    ],
  },
  {
    expect: "incident-report",
    file: "accident_report_yard.pdf",
    title: "Accident Report",
    body: [
      "Accident Report",
      "Reference: AR-2024-0611    Location: Northwind Trading, dispatch yard.",
      "Date and time: 11 June 2024, 14:20.",
      "Description: a reversing forklift struck a pallet stack; a case fell",
      "and bruised an operative's shoulder. First aid was given on site and",
      "the operative attended hospital as a precaution.",
      "Reporting officer: S. Whitfield, shift supervisor.",
      "A copy of the police report was requested for the insurer, and the",
      "root cause analysis is scheduled for Friday's safety meeting.",
      "Witnesses: two, statements attached. Severity level: minor.",
    ],
  },
  {
    expect: "certificate",
    file: "birth_certificate_reyes.pdf",
    title: "Certificate of Live Birth",
    body: [
      "Certificate of Live Birth",
      "Registration district: Travis County, Texas.",
      "This is to certify that the following particulars are recorded in the",
      "register of births.",
      "Child: Alex Jordan Reyes    Date of birth: 4 December 2016",
      "Place of birth: Austin, Texas.",
      "Parents: Morgan Reyes and Casey Reyes.",
      "Registered: 18 December 2016    Registrar: E. Marsh",
      "Certified to be a true copy of an entry in the register.",
    ],
  },
  {
    expect: "regulatory-filing",
    file: "articles_of_incorporation_acme.pdf",
    pages: 4,
    title: "Articles of Incorporation",
    body: [
      "Articles of Incorporation",
      "of Acme Robotics, Inc., filed with the Secretary of State of Delaware.",
      "First: the name of the corporation is Acme Robotics, Inc.",
      "Second: the registered office is 1209 Orange Street, Wilmington.",
      "Third: the corporation is authorized to issue 10,000,000 shares of",
      "common stock with a par value of $0.0001 per share.",
      "Fourth: the name and mailing address of the incorporator are stated",
      "below. Upon filing, the certificate of incorporation becomes effective.",
      "In witness whereof, the incorporator has executed these articles on",
      "12 July 2024.",
    ],
  },
  {
    expect: "invoice",
    file: "qb_invoice_1181.pdf",
    meta: { producer: "Intuit QuickBooks Online" },
    title: "Invoice",
    body: [
      "Invoice",
      "Harbour Roastery Ltd",
      "Invoice number: 1181    Invoice date: 2 August 2024",
      "Bill to: The Harbour Cafe, 112 Station Road.",
      "House espresso 6kg ... 96.00",
      "Filter subscription (August) ... 48.00",
      "Total: 144.00. Payment terms: net 30.",
    ],
  },
  {
    expect: "payslip",
    file: "adp_earnings_statement.pdf",
    meta: { producer: "ADP, LLC" },
    title: "Earnings Statement",
    body: [
      "Earnings Statement",
      "Northwind Trading Ltd    Pay period: 01/07/2024 to 31/07/2024",
      "Pay date: 31 July 2024    Employee: T. Hale",
      "Gross pay: 2,860.00",
      "Total deductions: 642.10, including income tax and pension.",
      "Net pay: 2,217.90",
      "Year to date gross: 20,020.00    Tax code: 1257L",
    ],
  },
  {
    expect: "tax-return",
    file: "turbotax_2023_return.pdf",
    pages: 14,
    meta: { producer: "Intuit TurboTax 2023" },
    title: "U.S. Individual Income Tax Return",
    body: [
      "Form 1040: U.S. Individual Income Tax Return, tax year 2023.",
      "Filing status: married filing jointly.",
      "Wages from W-2 box 1: 96,400. Interest income: 412.",
      "Adjusted gross income: 96,812.",
      "Standard deduction: 27,700. Taxable income: 69,112.",
      "Total tax: 7,864. Federal income tax withheld: 8,120.",
      "Refund: 256. Routing and account numbers as provided.",
    ],
  },
  {
    expect: "expense-report",
    file: "concur_expense_july.pdf",
    meta: { producer: "SAP Concur" },
    title: "Expense Report",
    body: [
      "Expense Report",
      "Employee: S. Whitfield    Report: July client visits",
      "Business purpose: quarterly reviews with three northern accounts.",
      "12 July - rail, Leeds to Hull, 34.50, receipts attached.",
      "12 July - lunch with client, 28.20.",
      "18 July - mileage claimed: 96 miles at 0.45 per mile, 43.20.",
      "Per diem (two days): 50.00.",
      "Total reimbursable: 155.90.",
      "Approved by cost center FAC-110 manager.",
    ],
  },
  {
    expect: "",
    file: "angebot_gartenpflege.pdf",
    title: "Angebot Gartenpflege",
    body: [
      "Angebot fur die Gartenpflege",
      "Sehr geehrte Frau Weber, vielen Dank fur Ihre Anfrage.",
      "Gerne unterbreiten wir Ihnen das folgende Angebot fur die regelmassige",
      "Pflege Ihres Gartens mit einem monatlichen Besuch unseres Teams.",
      "Der Preis betragt 120 Euro pro Monat und die Rechnung wird jeweils am",
      "Anfang des Monats gestellt. Das Angebot ist bis Ende August gultig und",
      "wir freuen uns sehr auf Ihre Ruckmeldung.",
      "Mit freundlichen Grussen, Fernwood Gartenservice GmbH",
    ],
  },
];

describe("heuristic engine broad corpus", () => {
  it.each(CASES.map((c) => [c.expect || `nothing (${c.file})`, c] as const))(
    "labels a %s correctly",
    (_label, c) => {
      const r = run(c);
      const detail = `expected ${c.expect || "no label"}, got [${r.labels.join(", ")}] (confidence ${r.confidence}, score ${r.score})`;
      if (c.expect === "") {
        expect(r.labels, detail).toEqual([]);
      } else {
        expect(r.labels[0], detail).toBe(c.expect);
      }
    },
  );
});
