package stirling.software.saas.payg.cancellation;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import stirling.software.proprietary.model.Team;
import stirling.software.proprietary.security.model.User;
import stirling.software.proprietary.security.repository.TeamRepository;
import stirling.software.saas.payg.cancellation.CancellationEdgeClient.Result;
import stirling.software.saas.payg.cancellation.CancellationEdgeClient.Target;
import stirling.software.saas.payg.cancellation.SubscriptionCancellationService.CancelRequest;
import stirling.software.saas.payg.cancellation.SubscriptionCancellationService.ContactRequest;
import stirling.software.saas.payg.policy.PaygTeamExtensions;
import stirling.software.saas.payg.repository.PaygTeamExtensionsRepository;
import stirling.software.saas.payg.stripe.StripeSubscriptionDao;
import stirling.software.saas.payg.stripe.StripeSubscriptionDao.SubscriptionState;
import stirling.software.saas.repository.SaasTeamExtensionsRepository;

class SubscriptionCancellationServiceTest {

    private static final Instant END = Instant.parse("2026-11-14T00:00:00Z");

    private final PaygTeamExtensionsRepository paygExtensions =
            mock(PaygTeamExtensionsRepository.class);
    private final SaasTeamExtensionsRepository teamExtensions =
            mock(SaasTeamExtensionsRepository.class);
    private final TeamRepository teams = mock(TeamRepository.class);
    private final StripeSubscriptionDao subscriptions = mock(StripeSubscriptionDao.class);
    private final CancellationEdgeClient edge = mock(CancellationEdgeClient.class);
    private final ChurnAlertPoster alerts = mock(ChurnAlertPoster.class);
    private JdbcTemplate jdbc;
    private SubscriptionCancellationService service;
    private final User leader = new User();

    @BeforeEach
    void team() {
        jdbc =
                new JdbcTemplate(
                        new DriverManagerDataSource(
                                "jdbc:h2:mem:"
                                        + UUID.randomUUID()
                                        + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                                "sa",
                                ""));
        jdbc.execute("CREATE SCHEMA stirling_pdf");
        jdbc.execute(
                "CREATE TABLE stirling_pdf.subscription_cancellation_event (id BIGINT"
                        + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, team_id BIGINT, actor_user_id BIGINT,"
                        + " product TEXT, subscription_id TEXT, action TEXT, reason TEXT,"
                        + " stripe_feedback TEXT, detail TEXT, competitor TEXT, offer_shown TEXT,"
                        + " ends_at TIMESTAMP WITH TIME ZONE, created_at TIMESTAMP WITH TIME ZONE"
                        + " DEFAULT CURRENT_TIMESTAMP)");
        PaygTeamExtensions ext = new PaygTeamExtensions();
        ext.setStripeCustomerId("cus_team");
        ext.setPaygSubscriptionId("sub_processor");
        when(paygExtensions.findById(42L)).thenReturn(Optional.of(ext));
        when(subscriptions.findTeamState(42L))
                .thenReturn(
                        Optional.of(new SubscriptionState("sub_team", "active", false, null, END)));
        when(subscriptions.findState("sub_processor"))
                .thenReturn(
                        Optional.of(
                                new SubscriptionState(
                                        "sub_processor", "active", false, null, END)));
        Team team = new Team();
        team.setName("Acme");
        when(teams.findById(42L)).thenReturn(Optional.of(team));
        leader.setId(7L);
        leader.setEmail("alex@acme.example");
        service =
                new SubscriptionCancellationService(
                        paygExtensions, teamExtensions, teams, subscriptions, edge, alerts, jdbc);
    }

    private List<Map<String, Object>> events() {
        return jdbc.queryForList(
                "SELECT product, action, reason, stripe_feedback, competitor FROM"
                        + " stirling_pdf.subscription_cancellation_event ORDER BY id");
    }

    @Test
    void statusReadsEachProductFromTheMirror() {
        assertThat(service.status(42))
                .extracting(v -> v.product() + ":" + v.subscriptionId() + ":" + v.periodEnd())
                .containsExactly(
                        "team:sub_team:2026-11-14T00:00:00Z",
                        "processor:sub_processor:2026-11-14T00:00:00Z");
    }

    @Test
    @SuppressWarnings("unchecked")
    void cancellingSendsTheReasonAndLogsOnlyWhatChanged() {
        when(edge.change(eq("cancel"), eq("cus_team"), anyList(), any(), anyString(), anyString()))
                .thenReturn(
                        List.of(
                                new Result(
                                        "team",
                                        "sub_team",
                                        "active",
                                        true,
                                        END.toString(),
                                        END.toString(),
                                        true)));

        var views =
                service.cancel(
                        42,
                        leader,
                        new CancelRequest(
                                "team", "switched_service", "Bundled", "Acrobat", "call"));

        ArgumentCaptor<List<Target>> targets = ArgumentCaptor.forClass(List.class);
        verify(edge)
                .change(
                        eq("cancel"),
                        eq("cus_team"),
                        targets.capture(),
                        eq(CancelReason.SWITCHED_SERVICE),
                        eq("Switching to: Acrobat\nBundled"),
                        eq("alex@acme.example"));
        assertThat(targets.getValue()).containsExactly(new Target("team", "sub_team"));
        assertThat(views.getFirst().cancelling()).isTrue();
        assertThat(views.getFirst().endsAt()).isEqualTo(END.toString());
        assertThat(views.get(1).cancelling()).isFalse();
        assertThat(events())
                .containsExactly(
                        Map.of(
                                "PRODUCT", "team",
                                "ACTION", "cancelled",
                                "REASON", "switched_service",
                                "STRIPE_FEEDBACK", "switched_service",
                                "COMPETITOR", "Acrobat"));
    }

    @Test
    void aCancelNeedsAReasonAndOtherNeedsWords() {
        assertThatThrownBy(
                        () ->
                                service.cancel(
                                        42,
                                        leader,
                                        new CancelRequest("team", null, null, null, null)))
                .extracting(e -> ((CancellationException) e).code())
                .isEqualTo("reason_required");
        assertThatThrownBy(
                        () ->
                                service.cancel(
                                        42,
                                        leader,
                                        new CancelRequest("team", "other", " ", null, null)))
                .extracting(e -> ((CancellationException) e).code())
                .isEqualTo("detail_required");
        verifyNoInteractions(edge);
    }

    @Test
    void nothingLiveToCancelIsNotFound() {
        when(subscriptions.findTeamState(42L)).thenReturn(Optional.empty());
        assertThatThrownBy(
                        () ->
                                service.cancel(
                                        42,
                                        leader,
                                        new CancelRequest("team", "unused", null, null, null)))
                .extracting(e -> ((CancellationException) e).status())
                .isEqualTo(HttpStatus.NOT_FOUND);
    }

    @Test
    void resumeWithdrawsEveryScheduledCancelAndLogsIt() {
        when(edge.change(eq("resume"), eq("cus_team"), anyList(), isNull(), isNull(), anyString()))
                .thenReturn(
                        List.of(
                                new Result(
                                        "team",
                                        "sub_team",
                                        "active",
                                        false,
                                        null,
                                        END.toString(),
                                        true),
                                new Result(
                                        "processor",
                                        "sub_processor",
                                        "active",
                                        false,
                                        null,
                                        END.toString(),
                                        false)));
        service.resume(42, leader, "both");
        assertThat(events()).extracting(e -> e.get("ACTION")).containsExactly("resumed");
    }

    @Test
    void aContactGoesToTheChurnChannelWithoutTouchingStripe() {
        when(alerts.post(anyString())).thenReturn(true);
        service.contact(
                42,
                leader,
                new ContactRequest("team", "too_expensive", "Anything <!channel>?", null));
        ArgumentCaptor<String> text = ArgumentCaptor.forClass(String.class);
        verify(alerts).post(text.capture());
        assertThat(text.getValue())
                .contains("*At risk:* Acme (team 42)")
                .contains("Reason: It costs too much")
                .contains("Reply to: alex@acme.example")
                .contains("> Anything &lt;!channel&gt;?");
        verifyNoInteractions(edge);
        assertThat(events()).extracting(e -> e.get("ACTION")).containsExactly("contacted");
    }

    @Test
    void contactsAreCappedAndAnUndeliveredOneSaysSo() {
        when(alerts.post(anyString())).thenReturn(true);
        ContactRequest hi = new ContactRequest("team", null, "hi", null);
        for (int i = 0; i < SubscriptionCancellationService.DAILY_CONTACT_LIMIT; i++) {
            service.contact(42, leader, hi);
        }
        assertThatThrownBy(() -> service.contact(42, leader, hi))
                .extracting(e -> ((CancellationException) e).code())
                .isEqualTo("contact_limit");

        when(alerts.post(anyString())).thenReturn(false);
        jdbc.update("DELETE FROM stirling_pdf.subscription_cancellation_event");
        assertThatThrownBy(() -> service.contact(42, leader, hi))
                .extracting(e -> ((CancellationException) e).code())
                .isEqualTo("message_not_delivered");
        assertThat(events()).isEmpty();
        verify(edge, never()).change(any(), any(), any(), any(), any(), any());
    }
}
