package stirling.software.saas.service;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Timestamp;
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Set;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

import stirling.software.saas.service.TeamMemberCapacityService.MakeActiveResult;
import stirling.software.saas.service.TeamMemberCapacityService.Member;

/** Team 42: leader 1 and members 2-8; member n last signed in n hours ago. */
class TeamMemberCapacityServiceTest {

    private JdbcTemplate jdbc;
    private TeamMemberCapacityService service;

    @BeforeEach
    void team() {
        DriverManagerDataSource db =
                new DriverManagerDataSource(
                        "jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                        "sa",
                        "");
        jdbc = new JdbcTemplate(db);
        jdbc.execute("CREATE SCHEMA auth");
        jdbc.execute("CREATE SCHEMA stirling_pdf");
        jdbc.execute(
                "CREATE TABLE auth.users (id UUID PRIMARY KEY, last_sign_in_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute(
                "CREATE TABLE stirling_pdf.users (user_id BIGINT PRIMARY KEY, supabase_auth_id UUID)");
        jdbc.execute(
                "CREATE TABLE stirling_pdf.team_memberships (membership_id BIGINT GENERATED BY DEFAULT AS IDENTITY"
                        + " PRIMARY KEY, team_id BIGINT, user_id BIGINT, role VARCHAR(50),"
                        + " capacity_disabled_at TIMESTAMP WITH TIME ZONE,"
                        + " capacity_pinned_at TIMESTAMP WITH TIME ZONE)");
        jdbc.execute(
                "CREATE TABLE stirling_pdf.saas_team_extensions (team_id BIGINT PRIMARY KEY,"
                        + " max_seats INTEGER, capacity_applied_seats INTEGER)");
        jdbc.execute(
                "CREATE TABLE stirling_pdf.linked_instance (team_id BIGINT, seat_count INTEGER,"
                        + " revoked_at TIMESTAMP)");
        jdbc.update("INSERT INTO stirling_pdf.saas_team_extensions VALUES (42, 100, NULL)");
        for (int n = 1; n <= 8; n++) {
            UUID id = UUID.randomUUID();
            jdbc.update(
                    "INSERT INTO auth.users VALUES (?, ?)",
                    id,
                    Timestamp.from(Instant.now().minus(Duration.ofHours(n))));
            jdbc.update("INSERT INTO stirling_pdf.users VALUES (?, ?)", n, id);
            jdbc.update(
                    "INSERT INTO stirling_pdf.team_memberships (team_id, user_id, role)"
                            + " VALUES (42, ?, ?)",
                    n,
                    n == 1 ? "LEADER" : "MEMBER");
        }
        service = new TeamMemberCapacityService(jdbc, new DataSourceTransactionManager(db));
    }

    private void seats(int maxSeats) {
        jdbc.update("UPDATE stirling_pdf.saas_team_extensions SET max_seats = ?", maxSeats);
    }

    private List<Long> disabled() {
        return service.disabledUserIds(42).stream().sorted().toList();
    }

    @Test
    void aDroppedAllowanceKeepsTheLeaderAndTheMostRecentSignIns() {
        assertThat(disabled()).isEmpty();
        seats(5);
        assertThat(service.isDisabled(42, 6)).isTrue();
        assertThat(service.isDisabled(42, 5)).isFalse();
        assertThat(disabled()).containsExactly(6L, 7L, 8L);
        seats(100);
        assertThat(disabled()).isEmpty();
    }

    @Test
    void aDisabledMemberSigningInNeverPushesOutSomeoneWithAccess() {
        disabled();
        seats(5);
        disabled();
        jdbc.update(
                "UPDATE auth.users SET last_sign_in_at = ? WHERE id ="
                        + " (SELECT supabase_auth_id FROM stirling_pdf.users WHERE user_id = 8)",
                Timestamp.from(Instant.now()));
        assertThat(disabled()).containsExactly(6L, 7L, 8L);
        // A freed place goes to the most recent sign-in among the disabled.
        jdbc.update("DELETE FROM stirling_pdf.team_memberships WHERE user_id = 2");
        service.refillAfterCommit(42);
        assertThat(disabled()).containsExactly(6L, 7L);
    }

    @Test
    void aRefillWaitsForTheDepartureToCommit() {
        disabled();
        seats(5);
        disabled();
        jdbc.update("DELETE FROM stirling_pdf.team_memberships WHERE user_id = 2");
        List<TransactionSynchronization> pending;
        TransactionSynchronizationManager.initSynchronization();
        try {
            service.refillAfterCommit(42);
            pending = TransactionSynchronizationManager.getSynchronizations();
        } finally {
            TransactionSynchronizationManager.clearSynchronization();
        }
        assertThat(disabled()).containsExactly(6L, 7L, 8L);
        pending.forEach(TransactionSynchronization::afterCommit);
        assertThat(disabled()).containsExactly(7L, 8L);
    }

    @Test
    void makeActiveSwapsOnlyANonLeaderWithAccessAndTheChoiceSticks() {
        disabled();
        seats(5);
        disabled();
        assertThat(service.makeActive(42, 7, null)).isEqualTo(MakeActiveResult.NO_PLACE);
        assertThat(service.makeActive(42, 7, 1L)).isEqualTo(MakeActiveResult.REPLACE_INVALID);
        assertThat(service.makeActive(42, 7, 6L)).isEqualTo(MakeActiveResult.REPLACE_INVALID);
        assertThat(service.makeActive(42, 2, 3L)).isEqualTo(MakeActiveResult.NOT_DISABLED);
        assertThat(service.makeActive(42, 7, 2L)).isEqualTo(MakeActiveResult.ACTIVATED);
        assertThat(disabled()).containsExactly(2L, 6L, 8L);
        // A later drop keeps the leader's pick ahead of a more recent sign-in.
        seats(100);
        disabled();
        seats(4);
        assertThat(disabled()).doesNotContain(7L);
    }

    @Test
    void teamsAlreadyOverTheirAllowanceLoseNobodyUntilItDrops() {
        seats(5);
        assertThat(disabled()).isEmpty();
        seats(6);
        assertThat(disabled()).isEmpty();
    }

    @Test
    void linkedDeploymentsTakePlacesAndOneIsFlooredToTheFreeAllowance() {
        disabled();
        jdbc.update("INSERT INTO stirling_pdf.linked_instance VALUES (42, 2, NULL)");
        // 5 places, 2 used by the deployment, 1 back for the linked owner: 4 cloud members stay.
        seats(1);
        assertThat(disabled()).containsExactly(5L, 6L, 7L, 8L);
    }

    @Test
    void anUnappliedMigrationFailsOpen() {
        jdbc.execute("ALTER TABLE stirling_pdf.team_memberships DROP COLUMN capacity_disabled_at");
        assertThat(service.isDisabled(42, 6)).isFalse();
        assertThat(service.disabledUserIds(42)).isEmpty();
        assertThat(service.makeActive(42, 6, null)).isEqualTo(MakeActiveResult.UNAVAILABLE);
    }

    @Test
    void leadersKeepAPlaceEvenPastTheAllowance() {
        Instant now = Instant.now();
        List<Member> members =
                List.of(
                        new Member(1, 1, true, null, null, null),
                        new Member(2, 2, true, null, null, null),
                        new Member(3, 3, false, null, null, now));
        assertThat(TeamMemberCapacityService.keepers(members, 1)).isEqualTo(Set.of(1L, 2L));
    }
}
