caffeine.jcache {
  default {
    policy {
      maximum = 500
      expire-after-write = 15m
    }
    statistics-enabled = true
  }

  policies {
    policy {
      maximum = 500
      expire-after-write = 30m
    }
    statistics-enabled = true
  }

  policy-sources {
    policy {
      maximum = 500
      expire-after-write = 30m
    }
    statistics-enabled = true
  }

  policy-assets {
    policy {
      maximum = 500
      expire-after-write = 1h
    }
    statistics-enabled = true
  }

  integration-configs {
    policy {
      maximum = 200
      expire-after-write = 1h
    }
    statistics-enabled = true
  }

  teams {
    policy {
      maximum = 1000
      expire-after-write = 15m
    }
    statistics-enabled = true
  }

  user-license-settings {
    policy {
      maximum = 2000
      expire-after-write = 1h
    }
    statistics-enabled = true
  }

  users {
    policy {
      maximum = 5000
      expire-after-write = 5m
    }
    statistics-enabled = true
  }

  saas-pricing-policies {
    policy {
      maximum = 100
      expire-after-write = 24h
    }
    statistics-enabled = true
  }

  saas-legal-consents {
    policy {
      maximum = 5000
      expire-after-write = 1h
    }
    statistics-enabled = true
  }

  saas-subscriptions {
    policy {
      maximum = 5000
      expire-after-write = 15m
    }
    statistics-enabled = true
  }

  saas-user-extensions {
    policy {
      maximum = 5000
      expire-after-write = 5m
    }
    statistics-enabled = true
  }

  saas-team-extensions {
    policy {
      maximum = 1000
      expire-after-write = 15m
    }
    statistics-enabled = true
  }
}
