// Auto-generated by generate_template_thumbnails.py
export type TemplateCatalogEntry = {
  docType: string
  templateCount: number
  templates: string[]
}

export const templateCatalog: TemplateCatalogEntry[] = [
  { docType: 'academic_articles', templateCount: 1, templates: ['default'] },
  { docType: 'academic_journals', templateCount: 1, templates: ['default'] },
  { docType: 'assignments', templateCount: 1, templates: ['default'] },
  { docType: 'books', templateCount: 1, templates: ['default'] },
  { docType: 'business_cards', templateCount: 1, templates: ['default'] },
  { docType: 'business_reports', templateCount: 1, templates: ['default'] },
  { docType: 'calendars', templateCount: 1, templates: ['default'] },
  { docType: 'conference_posters', templateCount: 1, templates: ['default'] },
  { docType: 'cover_letters', templateCount: 1, templates: ['default'] },
  { docType: 'cvs_and_resumes', templateCount: 1, templates: ['default'] },
  { docType: 'essays', templateCount: 1, templates: ['default'] },
  { docType: 'formal_letters', templateCount: 1, templates: ['default'] },
  { docType: 'invoices', templateCount: 1, templates: ['default'] },
  { docType: 'laboratory_books', templateCount: 1, templates: ['default'] },
  { docType: 'laboratory_reports', templateCount: 1, templates: ['default'] },
  { docType: 'miscellaneous', templateCount: 1, templates: ['default'] },
  { docType: 'newsletters', templateCount: 1, templates: ['default'] },
  { docType: 'presentations', templateCount: 1, templates: ['default'] },
  { docType: 'recipes', templateCount: 1, templates: ['default'] },
  { docType: 'signs', templateCount: 1, templates: ['default'] },
  { docType: 'theses', templateCount: 1, templates: ['default'] },
  { docType: 'title_pages', templateCount: 1, templates: ['default'] }
]
