#!/usr/bin/env python3
"""Generate Python tool models from the Java backend's OpenAPI spec (SwaggerDoc.json).

Uses datamodel-code-generator to convert OpenAPI request schemas to Pydantic models.
Run via:
    task engine:tool-models
or directly:
    python engine/scripts/generate_tool_models.py --spec SwaggerDoc.json
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

from datamodel_code_generator import DataModelType, PythonVersion, generate
from datamodel_code_generator.format import DatetimeClassType

TOOL_MODELS_HEADER = """\
# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by scripts/generate_tool_models.py from Java OpenAPI spec (SwaggerDoc.json).
# ruff: noqa: N815
"""

# Only tool endpoints under these path prefixes are included.
ALLOWED_PATH_PREFIXES = (
    "/api/v1/general/",
    "/api/v1/misc/",
    "/api/v1/security/",
    "/api/v1/convert/",
)

# Fields inherited from PDFFile base class — not tool parameters.
BASE_CLASS_FIELDS = frozenset({"fileInput", "fileId"})


# ---------------------------------------------------------------------------
# OpenAPI helpers
# ---------------------------------------------------------------------------


def _is_tool_endpoint(path: str) -> bool:
    return any(path.startswith(prefix) for prefix in ALLOWED_PATH_PREFIXES)


def _resolve_ref(spec: dict[str, Any], ref: str) -> dict[str, Any]:
    """Resolve a $ref pointer like '#/components/schemas/Foo'."""
    parts = ref.lstrip("#/").split("/")
    node: Any = spec
    for part in parts:
        node = node[part]
    return node


def _collect_properties(spec: dict[str, Any], schema: dict[str, Any]) -> dict[str, Any]:
    """Recursively collect properties from a schema, resolving $ref and allOf."""
    if "$ref" in schema:
        schema = _resolve_ref(spec, schema["$ref"])
    if "allOf" in schema:
        merged: dict[str, Any] = {}
        for sub in schema["allOf"]:
            merged.update(_collect_properties(spec, sub))
        return merged
    return dict(schema.get("properties", {}))


def _get_request_schema(spec: dict[str, Any], path_item: dict[str, Any]) -> dict[str, Any] | None:
    post = path_item.get("post")
    if not post:
        return None
    content = post.get("requestBody", {}).get("content", {})
    for media_type in ("multipart/form-data", "application/json"):
        if media_type in content:
            return content[media_type].get("schema")
    return None


# ---------------------------------------------------------------------------
# Naming
# ---------------------------------------------------------------------------


def _path_to_enum_name(path: str) -> str:
    """'/api/v1/misc/compress-pdf' → 'COMPRESS_PDF'."""
    segment = path.rstrip("/").rsplit("/", 1)[-1]
    return segment.replace("-", "_").upper()


def _path_to_class_name(path: str) -> str:
    """'/api/v1/misc/compress-pdf' → 'CompressPdfParams'."""
    segment = path.rstrip("/").rsplit("/", 1)[-1]
    parts = segment.split("-")
    return "".join(p.capitalize() for p in parts) + "Params"


# ---------------------------------------------------------------------------
# Per-endpoint schema → Pydantic code via datamodel-code-generator
# ---------------------------------------------------------------------------


def _build_json_schema_for_endpoint(
    spec: dict[str, Any],
    properties: dict[str, Any],
    class_name: str,
) -> dict[str, Any]:
    """Build a standalone JSON Schema object for one endpoint's parameters."""
    # Resolve any $ref in individual properties and strip file fields
    clean_props: dict[str, Any] = {}
    for name, prop in properties.items():
        if name in BASE_CLASS_FIELDS:
            continue
        resolved = prop
        if "$ref" in resolved:
            resolved = _resolve_ref(spec, resolved["$ref"])
        # Skip binary/file upload fields
        if resolved.get("type") == "string" and resolved.get("format") == "binary":
            continue
        clean_props[name] = resolved

    return {
        "title": class_name,
        "type": "object",
        "properties": clean_props,
    }


def _generate_model_code(schema: dict[str, Any], class_name: str) -> str:
    """Use datamodel-code-generator to produce a Pydantic model from a JSON Schema."""
    schema_json = json.dumps(schema)
    code = generate(
        input_=schema_json,
        input_file_type="jsonschema",
        output_model_type=DataModelType.PydanticV2BaseModel,
        target_python_version=PythonVersion.PY_313,
        snake_case_field=True,
        use_annotated=True,
        use_field_description=False,
        use_schema_description=False,
        class_name=class_name,
        base_class="stirling.models.base.ApiModel",
        use_default=True,
        datetime_class=DatetimeClassType.Datetime,
    )
    return code or ""


# ---------------------------------------------------------------------------
# Extraction and assembly
# ---------------------------------------------------------------------------


class ToolSpec:
    def __init__(self, path: str, enum_name: str, class_name: str, model_code: str):
        self.path = path
        self.enum_name = enum_name
        self.class_name = class_name
        self.model_code = model_code


def extract_tools(spec: dict[str, Any]) -> list[ToolSpec]:
    tools: list[ToolSpec] = []
    used_enum: set[str] = set()
    used_class: set[str] = set()

    for path, path_item in sorted(spec.get("paths", {}).items()):
        if not _is_tool_endpoint(path):
            continue
        schema = _get_request_schema(spec, path_item)
        if schema is None:
            continue
        properties = _collect_properties(spec, schema)
        if not properties:
            continue

        enum_name = _path_to_enum_name(path)
        class_name = _path_to_class_name(path)

        # Deduplicate names
        base = enum_name
        n = 2
        while enum_name in used_enum:
            enum_name = f"{base}_{n}"
            n += 1
        used_enum.add(enum_name)

        base = class_name
        n = 2
        while class_name in used_class:
            class_name = f"{base[:-6]}{n}Params"
            n += 1
        used_class.add(class_name)

        json_schema = _build_json_schema_for_endpoint(spec, properties, class_name)

        # Skip endpoints that have no tool parameters after filtering
        if not json_schema["properties"]:
            continue

        model_code = _generate_model_code(json_schema, class_name)
        tools.append(ToolSpec(path, enum_name, class_name, model_code))

    return tools


def _extract_class_body(code: str, class_name: str) -> str:
    """Extract just the class body (fields) from generated code, skipping imports/base."""
    # Find the class definition
    pattern = rf"^class {re.escape(class_name)}\(.*?\):\n((?:(?:    .+|)\n)*)"
    match = re.search(pattern, code, re.MULTILINE)
    if match:
        body = match.group(1).rstrip("\n")
        if body.strip():
            return body
    return "    pass"


def write_models_module(out_path: Path, tools: list[ToolSpec]) -> None:
    lines: list[str] = [TOOL_MODELS_HEADER]
    lines.append("from __future__ import annotations\n\n")
    lines.append("from enum import StrEnum\n")
    lines.append("from typing import Any, Literal\n\n")

    # Scan generated code for additional imports we need (e.g. Annotated, Field)
    all_code = "\n".join(t.model_code for t in tools)
    extra_imports: list[str] = []
    if "Annotated" in all_code:
        extra_imports.append("Annotated")
    if "from pydantic import" in all_code:
        pydantic_imports = set()
        for line in all_code.splitlines():
            m = re.match(r"from pydantic import (.+)", line)
            if m:
                for name in m.group(1).split(","):
                    name = name.strip()
                    if name:
                        pydantic_imports.add(name)
        if pydantic_imports:
            extra_imports.append(f"from pydantic import {', '.join(sorted(pydantic_imports))}")

    lines.append("from stirling.models.base import ApiModel\n")

    # Add any pydantic imports the generated code needs
    for imp in extra_imports:
        if imp.startswith("from "):
            lines.append(f"{imp}\n")

    lines.append("\n")

    # Model classes
    for tool in tools:
        body = _extract_class_body(tool.model_code, tool.class_name)
        lines.append(f"\nclass {tool.class_name}(ApiModel):\n")
        lines.append(body + "\n")

    lines.append("\n")

    # ParamToolModel union
    if tools:
        union = " | ".join(t.class_name for t in tools)
        lines.append(f"\ntype ParamToolModel = {union}\n")
        lines.append("type ParamToolModelType = type[ParamToolModel]\n")
    else:
        lines.append("\ntype ParamToolModel = ApiModel\n")
        lines.append("type ParamToolModelType = type[ParamToolModel]\n")

    lines.append("\n")

    # ToolEndpoint enum
    lines.append("\nclass ToolEndpoint(StrEnum):\n")
    for tool in tools:
        lines.append(f"    {tool.enum_name} = {tool.path!r}\n")

    lines.append("\n\n# Backward-compatible alias\n")
    lines.append("OperationId = ToolEndpoint\n\n")

    # OPERATIONS dict
    lines.append("\nOPERATIONS: dict[ToolEndpoint, ParamToolModelType] = {\n")
    for tool in tools:
        lines.append(f"    ToolEndpoint.{tool.enum_name}: {tool.class_name},\n")
    lines.append("}\n")

    out_path.write_text("".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Python tool models from Java OpenAPI spec")
    parser.add_argument("--spec", default="", help="Path to SwaggerDoc.json")
    parser.add_argument("--output", default="", help="Path to output tool_models.py")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]  # engine/
    project_root = repo_root.parent

    spec_path = Path(args.spec) if args.spec else project_root / "SwaggerDoc.json"
    if not spec_path.exists():
        print(f"ERROR: OpenAPI spec not found at {spec_path}")
        print("Run './gradlew generateOpenApiDocs' first to generate SwaggerDoc.json")
        raise SystemExit(1)

    output_path = Path(args.output) if args.output else repo_root / "src/stirling/models/tool_models.py"

    with open(spec_path) as f:
        spec = json.load(f)

    tools = extract_tools(spec)
    write_models_module(output_path, tools)
    print(f"Generated {len(tools)} tool models from {spec_path.name}")
    for tool in tools:
        print(f"  {tool.enum_name}: {tool.path} → {tool.class_name}")


if __name__ == "__main__":
    main()
