"""Core label id -> English Wikipedia articles naming that document type.

The article title in each language is the term that language actually uses for the
document, sourced rather than guessed. weight is what the term proves: a word only
ever found on that document type scores high, a general one scores low.
"""
# (label, [(english wikipedia title, weight, zone)])
CONCEPTS = [
    ("invoice", [("Invoice", 26, "title"), ("Value-added tax", 10, "any")]),
    ("receipt", [("Receipt", 24, "title")]),
    ("credit-note", [("Credit note", 24, "title")]),
    ("purchase-order", [("Purchase order", 22, "title")]),
    ("packing-slip", [("Packing slip", 22, "title")]),
    ("bank-statement", [("Bank statement", 26, "title")]),
    ("payslip", [("Paycheck", 24, "title"), ("Payroll", 16, "title")]),
    ("expense-report", [("Expense report", 22, "title")]),
    ("financial-statement", [("Financial statement", 22, "title"), ("Balance sheet", 14, "any")]),
    ("tax-return", [("Tax return", 24, "title")]),
    ("tax-form", [("Tax form", 20, "title")]),
    ("contract", [("Contract", 14, "title")]),
    ("employment-contract", [("Employment contract", 26, "title")]),
    ("lease-agreement", [("Lease", 20, "title"), ("Landlord", 10, "any"), ("Security deposit", 12, "any")]),
    ("nda", [("Non-disclosure agreement", 26, "title")]),
    ("terms-and-conditions", [("Terms of service", 24, "title")]),
    ("privacy-policy", [("Privacy policy", 26, "title"), ("General Data Protection Regulation", 12, "any")]),
    ("power-of-attorney", [("Power of attorney", 24, "title")]),
    ("affidavit", [("Affidavit", 22, "title")]),
    ("will", [("Will and testament", 22, "title")]),
    ("deed", [("Deed", 18, "title")]),
    ("mortgage-document", [("Mortgage loan", 20, "title")]),
    ("insurance-policy", [("Insurance policy", 24, "title"), ("Deductible", 10, "any")]),
    ("resume", [("Curriculum vitae", 26, "title"), ("Résumé", 22, "title")]),
    ("cover-letter", [("Cover letter", 22, "title")]),
    ("reference-letter", [("Letter of recommendation", 22, "title")]),
    ("job-description", [("Job description", 22, "title")]),
    ("timesheet", [("Timesheet", 22, "title")]),
    ("certificate", [("Academic certificate", 18, "title"), ("Diploma", 18, "title")]),
    ("transcript", [("Transcript (education)", 20, "title")]),
    ("thesis", [("Thesis", 22, "title")]),
    ("research-paper", [("Academic publishing", 12, "any")]),
    ("patent", [("Patent", 20, "title")]),
    ("prescription", [("Medical prescription", 22, "title"), ("Pharmacy", 12, "any")]),
    ("medical-report", [("Medical record", 20, "title"), ("Diagnosis", 12, "any")]),
    ("immunization-record", [("Vaccination", 14, "any")]),
    ("questionnaire", [("Questionnaire", 22, "title")]),
    ("warranty-document", [("Warranty", 20, "title")]),
    ("user-guide", [("Owner's manual", 24, "title")]),
    ("safety-data-sheet", [("Safety data sheet", 26, "title")]),
    ("technical-drawing", [("Technical drawing", 22, "title")]),
    ("bill-of-materials", [("Bill of materials", 22, "title")]),
    ("press-release", [("Press release", 24, "title")]),
    ("newsletter", [("Newsletter", 18, "title")]),
    ("brochure", [("Brochure", 18, "title")]),
    ("business-plan", [("Business plan", 22, "title")]),
    ("white-paper", [("White paper", 20, "title")]),
    ("meeting-minutes", [("Minutes", 20, "title")]),
    ("meeting-agenda", [("Agenda (meeting)", 18, "title")]),
    ("memo", [("Memorandum", 18, "title")]),
    ("invitation", [("Wedding invitation", 16, "title")]),
    ("ticket", [("Ticket (admission)", 20, "title")]),
    ("itinerary", [("Itinerary", 20, "title")]),
    ("waybill", [("Waybill", 22, "title")]),
    ("customs-declaration", [("Customs declaration", 24, "title")]),
    ("visa-document", [("Visa (document)", 20, "title")]),
    ("utility-bill", [("Electricity meter", 14, "any")]),
    ("menu", [("Menu", 18, "title")]),
    ("recipe", [("Recipe", 20, "title")]),
    ("presentation", [("Presentation", 14, "title")]),
    ("report", [("Report", 10, "title")]),
    ("letter", [("Letter (message)", 10, "title")]),
    ("form", [("Form (document)", 12, "title")]),
    ("license", [("License", 14, "title")]),
    ("public-notice", [("Public notice", 18, "title")]),
    ("court-filing", [("Pleading", 18, "title")]),
    ("legal-notice", [("Cease and desist", 20, "title")]),
    ("audit-report", [("Audit", 14, "any")]),
    ("risk-assessment", [("Risk assessment", 22, "title")]),
    ("incident-report", [("Incident report", 22, "title")]),
    ("inspection-report", [("Inspection", 12, "any")]),
    ("property-listing", [("Real estate", 10, "any")]),
    ("grant-agreement", [("Grant (money)", 14, "any")]),
    ("tender-document", [("Call for bids", 20, "title")]),
    ("booking-confirmation", [("Reservation", 16, "title")]),
    ("subscription-confirmation", [("Subscription business model", 12, "any")]),
    ("donation-receipt", [("Donation", 12, "any")]),
    ("email-thread", [("Email", 10, "any")]),
    ("book-ebook", [("Table of contents", 8, "any")]),
    ("magazine-article", [("Magazine", 12, "any")]),
    ("course-syllabus", [("Syllabus", 22, "title")]),
    ("lesson-plan", [("Lesson plan", 22, "title")]),
    ("employee-handbook", [("Employee handbook", 22, "title")]),
    ("performance-review", [("Performance appraisal", 22, "title")]),
    ("offer-letter", [("Recruitment", 10, "any")]),
    ("statement-of-work", [("Statement of work", 22, "title")]),
    ("service-agreement", [("Service-level agreement", 20, "title")]),
    ("purchase-agreement", [("Sales contract", 20, "title")]),
    ("loan-agreement", [("Loan agreement", 22, "title")]),
    ("shareholder-agreement", [("Shareholders' agreement", 22, "title")]),
    ("settlement-agreement", [("Settlement (litigation)", 20, "title")]),
    ("legal-opinion", [("Legal opinion", 20, "title")]),
    ("subpoena", [("Subpoena", 22, "title")]),
    ("consent-form", [("Informed consent", 20, "title")]),
    ("discharge-summary", [("Hospital discharge", 22, "title")]),
    ("lab-report", [("Medical laboratory", 14, "any")]),
    ("referral-letter", [("Referral (medicine)", 20, "title")]),
    ("insurance-claim", [("Insurance claim", 22, "title")]),
    ("insurance-certificate", [("Certificate of insurance", 20, "title")]),
    ("government-notice", [("Administrative act", 16, "any")]),
    ("regulatory-filing", [("Regulatory compliance", 12, "any")]),
    ("compliance-document", [("Compliance requirements", 12, "any")]),
    ("quality-report", [("Quality control", 12, "any")]),
    ("test-report", [("Calibration", 14, "any")]),
    ("safety-procedure", [("Occupational safety and health", 12, "any")]),
    ("datasheet", [("Datasheet", 20, "title")]),
    ("technical-specification", [("Specification (technical standard)", 18, "title")]),
    ("api-documentation", [("API", 10, "any")]),
    ("license-agreement", [("End-user license agreement", 22, "title")]),
    ("grant-application", [("Grant writing", 14, "any")]),
    ("sales-proposal", [("Proposal (business)", 18, "title")]),
    ("proposal", [("Request for proposal", 18, "title")]),
    ("budget", [("Budget", 16, "title")]),
    ("quote", []),
    ("delivery-note", []),
    ("order-confirmation", [("Sales order", 20, "title")]),
    ("remittance-advice", [("Remittance advice", 22, "title")]),
    ("statement-of-account", [("Account statement", 20, "title")]),
    ("application-form", [("Application for employment", 16, "title")]),
    ("registration-form", [("Registration form", 20, "title")]),
    ("gift-certificate", [("Gift card", 18, "title")]),
    ("confirmation-letter", [("Acknowledgement (data networks)", 0, "any")]),
    ("return-authorization", [("Product return", 18, "title")]),
    ("organization-chart", [("Organizational chart", 22, "title")]),
    ("case-study", [("Case study", 18, "title")]),
    ("board-report", [("Board of directors", 12, "any")]),
    ("pitch-deck", []),
    ("investment-summary", [("Investment", 10, "any")]),
    ("letter-of-intent", [("Letter of intent", 22, "title")]),
    ("quarterly-report", [("Quarterly report", 20, "title")]),
    ("analytics-report", [("Web analytics", 12, "any")]),
    ("appraisal-report", [("Real estate appraisal", 20, "title")]),
    ("tax-statement", [("Tax assessment", 20, "title")]),
    ("benefits-summary", [("Employee benefits", 16, "any")]),
    ("hoa-document", [("Homeowner association", 20, "title")]),
    ("grade-report", [("Report card", 22, "title")]),
    ("assignment-brief", [("Homework", 14, "any")]),
    ("supply-order", [("Requisition", 18, "title")]),
]
# Signal pattern groups, same sourcing.
SIGNALS = [
    ("toc", "Table of contents"),
    ("references", "Bibliography"),
    ("signature", "Signature"),
]

# Corrections and additions a reader verified against the generated output. Kept
# here rather than edited into the packs so the review is visible and repeatable:
# re-running the generator does not lose them.
#   label -> language -> [(text, weight, zone)]
OVERRIDES = {
    "invoice": {
        # Wikipedia's ja langlink for "Invoice" resolves to 送り状, a delivery slip.
        "ja": [("請求書", 26, "title")],
        # инвойс is foreign-trade usage; a domestic Russian invoice says this.
        "ru": [("счёт-фактура", 24, "title"), ("счёт на оплату", 20, "title")],
        "zh": [("發票", 24, "title")],
    },
    "contract": {
        "ja": [("契約書", 22, "title")],
        "zh": [("合同", 22, "title"), ("合約", 22, "title")],
    },
    "resume": {
        "es": [("currículum vitae", 24, "title"), ("currículum", 20, "title")],
        "it": [("curriculum vitae", 24, "title")],
        "nl": [("curriculum vitae", 24, "title")],
        "pl": [("życiorys", 20, "title")],
    },
}
