// Define all possible tool IDs as source of truth
export const TOOL_IDS = [
  'certSign',
  'sign',
  'addPassword',
  'removePassword',
  'removePages',
  'removeBlanks',
  'removeAnnotations',
  'removeImage',
  'changePermissions',
  'watermark',
  'sanitize',
  'autoSplitPDF',
  'autoSizeSplitPDF',
  'split',
  'merge',
  'convert',
  'ocr',
  'addImage',
  'rotate',
  'scannerImageSplit',
  'editTableOfContents',
  'scannerEffect',
  'autoRename',
  'pageLayout',
  'scalePages',
  'adjustContrast',
  'crop',
  'pdfToSinglePage',
  'multiTool',
  'repair',
  'compare',
  'addPageNumbers',
  'redact',
  'flatten',
  'removeCertSign',
  'unlockPDFForms',
  'compress',
  'extractPages',
  'reorganizePages',
  'extractImages',
  'addStamp',
  'addAttachments',
  'changeMetadata',
  'overlayPdfs',
  'getPdfInfo',
  'validateSignature',
  'read',
  'automate',
  'replaceColor',
  'showJS',
  'devApi',
  'devFolderScanning',
  'devSsoGuide',
  'devAirgapped',
  'bookletImposition',
] as const;

// Tool identity - what PDF operation we're performing (type-safe)
export type ToolId = typeof TOOL_IDS[number];

// Type guard using the same source of truth
export const isValidToolId = (value: string): value is ToolId => {
  return TOOL_IDS.includes(value as ToolId);
};
