import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";
import type { OpenAPI3, SchemaObject, TransformNodeOptions } from "openapi-typescript";
import ts from "typescript";

type OpenApiDocument = OpenAPI3 & {
  paths?: Record<string, Record<string, OpenApiOperation>>;
  components?: {
    schemas?: Record<string, unknown>;
  };
};

type OpenApiOperation = {
  operationId?: string;
  summary?: string;
  description?: string;
  requestBody?: {
    required?: boolean;
    content?: Record<string, { schema?: { $ref?: string } }>;
  };
};

type OperationMetadata = {
  operationId: string;
  path: string;
  method: string;
  summary?: string;
  description?: string;
  requestBodyContentType?: string;
  requestSchemaName?: string;
  requestBodyRequired: boolean;
};

const FRONTEND_DIR = path.resolve(process.cwd());
const REPO_ROOT = path.resolve(FRONTEND_DIR, "..");
const OPENAPI_PATH = path.join(REPO_ROOT, "SwaggerDoc.json");
const OUTPUT_DIR = path.join(FRONTEND_DIR, "src", "core", "generated");
const OUTPUT_PATH = path.join(OUTPUT_DIR, "openapi.ts");

const GENERATED_HEADER = `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by frontend/scripts/generate-openapi-types.ts using openapi-typescript from ../../SwaggerDoc.json.
`;

async function main(): Promise<void> {
  const checkMode = process.argv.includes("--check");
  const raw = await readFile(OPENAPI_PATH, "utf8");
  const document = JSON.parse(raw) as OpenApiDocument;

  const generatedTypes = await renderOpenApiTypes(document);
  const current = await readFile(OUTPUT_PATH, "utf8").catch(() => null);

  if (checkMode) {
    if (current !== generatedTypes) {
      console.error(`Generated OpenAPI types are out of date: ${OUTPUT_PATH}`);
      process.exitCode = 1;
    }
    return;
  }

  await mkdir(OUTPUT_DIR, { recursive: true });
  await writeFile(OUTPUT_PATH, generatedTypes, "utf8");
}

async function renderOpenApiTypes(document: OpenApiDocument): Promise<string> {
  const ast = await openapiTS(document, {
    alphabetize: true,
    transform(schemaObject: SchemaObject, _options: TransformNodeOptions) {
      if (schemaObject.format === "binary") {
        return ts.factory.createTypeReferenceNode(ts.factory.createIdentifier("File"));
      }
      return undefined;
    },
  });

  const operations = collectOperations(document).sort((left, right) =>
    left.operationId.localeCompare(right.operationId)
  );
  const schemaNames = Object.keys(document.components?.schemas ?? {}).sort();

  const helperLines: string[] = [];
  helperLines.push("");
  for (const schemaName of schemaNames) {
    helperLines.push(`export type ${schemaName} = components['schemas'][${JSON.stringify(schemaName)}];`);
  }
  helperLines.push("");
  helperLines.push(`export type ApiOperationId = ${operations.map((operation) => `'${operation.operationId}'`).join(" | ")};`);
  helperLines.push("");
  helperLines.push("export const API_OPERATION_IDS = [");
  for (const operation of operations) {
    helperLines.push(`  '${operation.operationId}',`);
  }
  helperLines.push("] as const satisfies readonly ApiOperationId[];");
  helperLines.push("");
  helperLines.push("export interface ApiSchemaByName {");
  for (const schemaName of schemaNames) {
    helperLines.push(`  ${quoteProperty(schemaName)}: ${schemaName};`);
  }
  helperLines.push("}");
  helperLines.push("");
  helperLines.push("export interface ApiOperationRequestById {");
  for (const operation of operations) {
    helperLines.push(`  ${quoteProperty(operation.operationId)}: ${operation.requestSchemaName ?? "never"};`);
  }
  helperLines.push("}");
  helperLines.push("");
  helperLines.push("export interface ApiOperationMetadata {");
  helperLines.push("  path: string;");
  helperLines.push("  method: string;");
  helperLines.push("  summary?: string;");
  helperLines.push("  description?: string;");
  helperLines.push("  requestBodyContentType?: string;");
  helperLines.push("  requestSchemaName?: keyof ApiSchemaByName;");
  helperLines.push("  requestBodyRequired: boolean;");
  helperLines.push("}");
  helperLines.push("");
  helperLines.push("export const API_OPERATION_METADATA: Record<ApiOperationId, ApiOperationMetadata> = {");
  for (const operation of operations) {
    helperLines.push(`  ${quoteProperty(operation.operationId)}: {`);
    helperLines.push(`    path: '${escapeString(operation.path)}',`);
    helperLines.push(`    method: '${escapeString(operation.method)}',`);
    if (operation.summary) {
      helperLines.push(`    summary: '${escapeString(operation.summary)}',`);
    }
    if (operation.description) {
      helperLines.push(`    description: '${escapeString(operation.description)}',`);
    }
    if (operation.requestBodyContentType) {
      helperLines.push(`    requestBodyContentType: '${escapeString(operation.requestBodyContentType)}',`);
    }
    if (operation.requestSchemaName) {
      helperLines.push(`    requestSchemaName: '${escapeString(operation.requestSchemaName)}',`);
    }
    helperLines.push(`    requestBodyRequired: ${String(operation.requestBodyRequired)},`);
    helperLines.push("  },");
  }
  helperLines.push("};");
  helperLines.push("");

  return `${GENERATED_HEADER}${astToString(ast)}\n${helperLines.join("\n")}`;
}

function collectOperations(document: OpenApiDocument): OperationMetadata[] {
  const operations: OperationMetadata[] = [];

  for (const [apiPath, pathItem] of Object.entries(document.paths ?? {})) {
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!operation.operationId) {
        continue;
      }

      const [requestBodyContentType, mediaType] = Object.entries(operation.requestBody?.content ?? {})[0] ?? [];
      operations.push({
        operationId: operation.operationId,
        path: apiPath,
        method,
        summary: operation.summary,
        description: operation.description,
        requestBodyContentType,
        requestSchemaName: getRefName(mediaType?.schema?.$ref),
        requestBodyRequired: operation.requestBody?.required ?? false,
      });
    }
  }

  return operations;
}

function getRefName(ref: string | undefined): string | undefined {
  return ref?.split("/").at(-1);
}

function quoteProperty(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function escapeString(value: string): string {
  return value
    .replaceAll("\\", "\\\\")
    .replaceAll("'", "\\'")
    .replaceAll("\r", "\\r")
    .replaceAll("\n", "\\n");
}

void main();
