// AUTO-GENERATED by editor/scripts/generate-icon-registry.mjs — do not edit.
// Source: src/core/icons/svg/stirling/*.svg
// Regenerate with: task frontend:prepare:icons
// Lucide icons are ISC; the notice is in src/core/icons/LICENSE-lucide.txt

/*! @license Icons in this file whose geometry is not entirely ours.
 * 
 * file-pdf:
 * The page outline and corner fold is Lucide geometry (ISC). Full notice and the exact paths:
 * src/core/icons/LICENSE-lucide.txt, which must stay with this file.
 * 
 * users-plus:
 * The person body and second head arc is Lucide geometry (ISC). Full notice and the exact paths:
 * src/core/icons/LICENSE-lucide.txt, which must stay with this file.
 */

import type { IconEntry } from "@app/icons/types";

export const STIRLING_ICONS = {
  "annotation-off": { viewBox: "0 0 24 24", mono: true, nodes: [["path",{"d":"M3 17c1.5-3.5 3.2-3.5 4.5 0s3 3.5 4.5 0 3.2-3.5 4.5 0"}],["path",{"d":"M16.5 4.5 21 9"}],["path",{"d":"M21 4.5 16.5 9"}]] },
  "api": { viewBox: "0 0 24 24", mono: true, nodes: [["path",{"d":"M8.5 4C6.5 4 6 5 6 6.5v2.3C6 10.4 5.4 11.2 4 11.5v1c1.4.3 2 1.1 2 2.7v2.3C6 19 6.5 20 8.5 20"}],["path",{"d":"M15.5 4c2 0 2.5 1 2.5 2.5v2.3c0 1.6.6 2.4 2 2.7v1c-1.4.3-2 1.1-2 2.7v2.3c0 1.5-.5 2.5-2.5 2.5"}]] },
  "editor": { viewBox: "0 0 24 24", mono: true, nodes: [["path",{"d":"M12 20h9"}],["path",{"d":"M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4z"}]] },
  "file-html": { viewBox: "0 0 24 24", mono: true, nodes: [["rect",{"x":"2","y":"4.5","width":"20","height":"15","rx":"2.5"}],["g",{"strokeWidth":"1.3"},[["path",{"d":"M5 9v6"}],["path",{"d":"M7.3 9v6"}],["path",{"d":"M5 12h2.3"}],["path",{"d":"M9.15 9h2.1"}],["path",{"d":"M10.2 9v6"}],["path",{"d":"M13.1 15V9l1.3 2.6 1.3-2.6v6"}],["path",{"d":"M17.55 9v6h1.4"}]]]] },
  "file-pdf": { viewBox: "0 0 24 24", mono: true, nodes: [["path",{"d":"M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"}],["path",{"d":"M14 2v5a1 1 0 0 0 1 1h5"}],["g",{"strokeWidth":"1.3"},[["path",{"d":"M6.1 18.4v-5"}],["path",{"d":"M6.1 13.4h1.1a1.2 1.2 0 0 1 0 2.4H6.1"}],["path",{"d":"M10.5 18.4v-5"}],["path",{"d":"M10.5 13.4h0.8a2.5 2.5 0 0 1 0 5h-0.8"}],["path",{"d":"M15.6 18.4v-5"}],["path",{"d":"M15.6 13.4h2"}],["path",{"d":"M15.6 15.9h1.6"}]]]] },
  "ftp": { viewBox: "0 0 24 24", mono: true, nodes: [["rect",{"x":"4","y":"13","width":"16","height":"7","rx":"1.5"}],["path",{"d":"M7.5 16.5h.01"}],["path",{"d":"M11 16.5h.01"}],["path",{"d":"M9 4.5h6l-2-2M15 8.5H9l2 2"}]] },
  "line-weight": { viewBox: "0 0 24 24", mono: true, nodes: [["path",{"d":"M4 6.5h16","strokeWidth":"1.25"}],["path",{"d":"M4 12h16","strokeWidth":"2.5"}],["path",{"d":"M4 18h16","strokeWidth":"4"}]] },
  "move-item-down": { viewBox: "0 0 24 24", mono: true, nodes: [["rect",{"x":"3.5","y":"3.5","width":"8","height":"7","rx":"1.5"}],["path",{"d":"M7.5 14v6"}],["path",{"d":"m4.5 17 3 3 3-3"}],["path",{"d":"M15 17.5h5.5"}],["path",{"d":"M15 13.5h5.5"}]] },
  "radio-checked": { viewBox: "0 0 24 24", mono: true, nodes: [["circle",{"cx":"12","cy":"12","r":"9"}],["circle",{"cx":"12","cy":"12","r":"5","fill":"currentColor","stroke":"none"}]] },
  "remove-selection": { viewBox: "0 0 24 24", mono: true, nodes: [["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2.5","strokeDasharray":"4 3.2"}],["path",{"d":"M9 9l6 6"}],["path",{"d":"M15 9l-6 6"}]] },
  "select-all": { viewBox: "0 0 24 24", mono: true, nodes: [["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2.5","strokeDasharray":"4 3.2"}],["rect",{"x":"8.25","y":"8.25","width":"7.5","height":"7.5","rx":"1.25"}]] },
  "sftp": { viewBox: "0 0 24 24", mono: true, nodes: [["rect",{"x":"4","y":"13","width":"16","height":"7","rx":"1.5"}],["path",{"d":"M7.5 16.5h.01"}],["path",{"d":"M11 16.5h.01"}],["path",{"d":"M12 10V3.5"}],["path",{"d":"m8.5 6.5 3.5-3 3.5 3"}]] },
  "single-page": { viewBox: "0 0 24 24", mono: true, nodes: [["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2.5"}],["path",{"d":"M10.25 9.75 12.75 8v8"}]] },
  "users-plus": { viewBox: "0 0 24 24", mono: true, nodes: [["path",{"d":"M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"}],["path",{"d":"M16 3.128a4 4 0 0 1 0 7.744"}],["circle",{"cx":"9","cy":"7","r":"4"}],["path",{"d":"M20.4 14.4v4.8"}],["path",{"d":"M18 16.8h4.8"}]] },
  "watermark": { viewBox: "0 0 24 24", mono: true, nodes: [["rect",{"x":"3","y":"3","width":"18","height":"18","rx":"2.5"}],["path",{"d":"M7.5 16 12 11.5"}],["path",{"d":"M11 16.5 16.5 11"}],["path",{"d":"M14.5 16.5 17 14"}]] },
} as const satisfies Record<string, IconEntry>;
