/**
 * Generates the committed frontend tool API types (toolApiTypes.ts) from the
 * Java backend's OpenAPI spec, so the frontend's request shapes stay in step
 * with the backend.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { compile, type JSONSchema } from "json-schema-to-typescript";
import { format } from "oxfmt";

// Formatting config shared with the repo's oxfmt CLI, so generated output
// matches `task frontend:format:check`. Resolved relative to this script so it
// works regardless of the working directory.
const OXFMT_CONFIG_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../.oxfmtrc.json",
);

// The API namespaces whose endpoints are real, callable tools. `/api/v1/filter/`
// (pipeline-only) and `/api/v1/ai/tools/` (not in the spec) are intentionally
// excluded. Extend this list when other namespaces become tools.
const ALLOWED_PATH_PREFIXES = [
  "/api/v1/general/",
  "/api/v1/misc/",
  "/api/v1/security/",
  "/api/v1/convert/",
];

// File plumbing, not user parameters: `fileInput` is the uploaded document and
// `fileId` a server-side handle. Stripped from every generated request model.
// Named file fields (stampImage, attachments, ...) are real parameters and kept.
const BASE_FILE_FIELDS = new Set(["fileInput", "fileId"]);

// The shared "upload a file or provide a file ID" wrapper schema and its two
// branches. An endpoint whose body is exactly this has no parameters, so it must
// resolve to an empty model. It needs separate handling because the wrapper is a
// `oneOf`, which survives the flat-field stripping above and would otherwise leak
// the file fields into the output.
const FILE_WRAPPER_COMPONENTS = new Set([
  "PDFFile",
  "PDFFileUpload",
  "PDFFileRef",
]);

const COMPONENT_REF_PREFIX = "#/components/schemas/";

const FILE_HEADER = [
  "// AUTO-GENERATED FILE. DO NOT EDIT.",
  "// Generated by editor/scripts/generate-tool-api-types.mts from the Java OpenAPI spec",
  "// (SwaggerDoc.json). Regenerate with: task frontend:tool-models",
  "// Tools that take only a file input have no parameters; their model is Record<string, never>.",
].join("\n");

type Json = Record<string, unknown>;

interface DiscoveredTool {
  path: string;
  className: string;
}

function isObject(value: unknown): value is Json {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Recursively sort object keys so the output is byte-stable regardless of the
 * key ordering springdoc happens to emit.
 */
function deepSortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(deepSortKeys);
  if (isObject(value)) {
    const sorted: Json = {};
    for (const key of Object.keys(value).sort()) {
      sorted[key] = deepSortKeys(value[key]);
    }
    return sorted;
  }
  return value;
}

function pascalCase(segment: string): string {
  return segment
    .split(/[-_/]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/** Fallback class name for an inline request body (no $ref to name it after). */
function pathToClassName(path: string): string {
  const relevant = path.replace(/^\/api\/v1\//, "");
  return `${pascalCase(relevant)}Request`;
}

function dedupe(name: string, used: Set<string>): string {
  let candidate = name;
  let n = 2;
  while (used.has(candidate)) candidate = `${name}${n++}`;
  used.add(candidate);
  return candidate;
}

/** The request body schema for a POST endpoint (multipart wins, then JSON), or null. */
function requestBodySchema(pathItem: Json): Json | null {
  const post = pathItem.post;
  if (!isObject(post)) return null;
  const requestBody = post.requestBody;
  if (!isObject(requestBody)) return null;
  const content = requestBody.content;
  if (!isObject(content)) return null;
  for (const mediaType of ["multipart/form-data", "application/json"]) {
    const entry = content[mediaType];
    if (isObject(entry) && isObject(entry.schema)) return entry.schema;
  }
  return null;
}

/**
 * A POST endpoint's query parameters as a property map plus the required ones.
 * Some tools take inputs on the query string alongside the multipart body (e.g.
 * merge-pdfs' `fileOrder`), so a complete model has to fold them in. Ref-valued
 * param schemas are inlined later by rewriteRefs.
 */
function queryParameters(pathItem: Json): { props: Json; required: string[] } {
  const props: Json = {};
  const required: string[] = [];
  const post = pathItem.post;
  if (!isObject(post) || !Array.isArray(post.parameters))
    return { props, required };
  for (const param of post.parameters) {
    if (
      !isObject(param) ||
      param.in !== "query" ||
      typeof param.name !== "string"
    )
      continue;
    if (!isObject(param.schema)) continue;
    const schema = structuredClone(param.schema) as Json;
    if (!("description" in schema) && typeof param.description === "string") {
      schema.description = param.description;
    }
    props[param.name] = schema;
    if (param.required === true) required.push(param.name);
  }
  return { props, required };
}

/**
 * Rewrite every `#/components/schemas/X` ref to `#/definitions/X` in place (the
 * form json-schema-to-typescript expects) and collect the referenced component
 * names so the caller can inline them.
 */
function rewriteRefs(node: unknown, found: Set<string>): void {
  if (Array.isArray(node)) {
    for (const item of node) rewriteRefs(item, found);
    return;
  }
  if (!isObject(node)) return;
  const ref = node.$ref;
  if (typeof ref === "string" && ref.startsWith(COMPONENT_REF_PREFIX)) {
    const name = ref.slice(COMPONENT_REF_PREFIX.length);
    node.$ref = `#/definitions/${name}`;
    found.add(name);
  }
  for (const value of Object.values(node)) rewriteRefs(value, found);
}

/** Keep only fields the client must send: drop those with a default or already stripped. */
function computeRequired(schema: Json, properties: Json): string[] {
  const required = Array.isArray(schema.required)
    ? (schema.required as string[])
    : [];
  return required.filter((name) => {
    const prop = properties[name];
    return name in properties && !(isObject(prop) && "default" in prop);
  });
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      spec: { type: "string" },
      output: { type: "string" },
      check: { type: "boolean", default: false },
    },
  });
  if (!values.spec || !values.output) {
    throw new Error(
      "Usage: generate-tool-api-types.mts --spec <SwaggerDoc.json> --output <file.ts> [--check]",
    );
  }
  const specPath = resolve(values.spec);
  const outputPath = resolve(values.output);

  const spec = JSON.parse(readFileSync(specPath, "utf-8")) as Json;
  const paths = isObject(spec.paths) ? spec.paths : {};
  const components =
    isObject(spec.components) && isObject(spec.components.schemas)
      ? spec.components.schemas
      : {};

  const tools: DiscoveredTool[] = [];
  const definitions: Record<string, Json> = {};
  const usedClassNames = new Set<string>();
  const pendingComponents = new Set<string>();
  const skipped: string[] = [];

  for (const path of Object.keys(paths).sort()) {
    if (
      path.includes("{") ||
      !ALLOWED_PATH_PREFIXES.some((p) => path.startsWith(p))
    )
      continue;
    const pathItem = paths[path];
    if (!isObject(pathItem)) continue;
    const bodySchema = requestBodySchema(pathItem);
    if (!bodySchema) {
      if (isObject(pathItem.post)) skipped.push(path);
      continue;
    }

    // Resolve the request model into a fresh, mutable clone so we never mutate the shared spec.
    const ref = bodySchema.$ref;
    const refComponent =
      typeof ref === "string" && ref.startsWith(COMPONENT_REF_PREFIX)
        ? ref.slice(COMPONENT_REF_PREFIX.length)
        : null;
    let className: string;
    let modelSchema: Json;
    if (refComponent && FILE_WRAPPER_COMPONENTS.has(refComponent)) {
      // File-only endpoint: model it as an empty object so it becomes
      // Record<string, never> rather than the wrapper's file union. Named after
      // the path since the wrapper schema is shared. Query params still fold in
      // below.
      className = pathToClassName(path);
      modelSchema = { type: "object", properties: {} };
    } else if (refComponent) {
      const component = components[refComponent];
      if (!isObject(component)) continue;
      className = refComponent;
      modelSchema = structuredClone(component) as Json;
    } else {
      className = pathToClassName(path);
      modelSchema = structuredClone(bodySchema) as Json;
    }

    // A component shared by several endpoints (e.g. GeneralFile) is only defined once.
    if (!(className in definitions)) {
      const uniqueName = dedupe(className, usedClassNames);
      className = uniqueName;
      const bodyProps: Json = isObject(modelSchema.properties)
        ? (structuredClone(modelSchema.properties) as Json)
        : {};
      const query = queryParameters(pathItem);
      // Body wins over query on a name collision.
      const properties: Json = { ...query.props, ...bodyProps };
      for (const field of BASE_FILE_FIELDS) delete properties[field];
      modelSchema.properties = properties;
      const required = new Set(computeRequired(modelSchema, properties));
      for (const name of query.required) {
        const prop = properties[name];
        if (name in properties && !(isObject(prop) && "default" in prop)) {
          required.add(name);
        }
      }
      if (required.size > 0) modelSchema.required = [...required];
      else delete modelSchema.required;
      modelSchema.title = className;
      rewriteRefs(modelSchema, pendingComponents);
      definitions[className] = modelSchema;
    }

    tools.push({ path, className });
  }

  // Transitively inline every referenced component into `definitions`, rewriting its refs too.
  const queue = [...pendingComponents];
  while (queue.length > 0) {
    const name = queue.pop() as string;
    if (name in definitions) continue;
    const component = components[name];
    if (!isObject(component)) continue;
    const cloned = structuredClone(component) as Json;
    cloned.title = name;
    const nested = new Set<string>();
    rewriteRefs(cloned, nested);
    definitions[name] = cloned;
    for (const next of nested) if (!(next in definitions)) queue.push(next);
  }

  await compileAndWrite(
    tools,
    definitions,
    outputPath,
    values.check ?? false,
    skipped,
  );
}

async function compileAndWrite(
  tools: DiscoveredTool[],
  definitions: Record<string, Json>,
  outputPath: string,
  check: boolean,
  skipped: string[],
): Promise<void> {
  // json-schema-to-typescript only emits a named, exported interface per schema
  // if something references it, so wrap every model in one root object. The root
  // interface itself is stripped from the output afterwards.
  const rootName = "__ToolApiRootAutogen";
  const uniqueClassNames = [...new Set(tools.map((t) => t.className))];
  const rootSchema: JSONSchema = {
    title: rootName,
    type: "object",
    additionalProperties: false,
    properties: Object.fromEntries(
      uniqueClassNames.map((name) => [name, { $ref: `#/definitions/${name}` }]),
    ),
    definitions: definitions as Record<string, JSONSchema>,
  };

  // Canonicalize key order so a reordering in SwaggerDoc.json can never change
  // the generated file (which would flake the committed-types CI check).
  const canonicalRoot = deepSortKeys(rootSchema) as JSONSchema;

  const compiled = await compile(canonicalRoot, rootName, {
    bannerComment: "",
    additionalProperties: false,
    declareExternallyReferenced: true,
    unreachableDefinitions: false,
    strictIndexSignatures: true,
    format: false,
  });

  // Drop the root wrapper interface, then rewrite empty models (file-only tools)
  // to `Record<string, never>` - the precise, lint-clean type for an object with
  // no properties (json-schema-to-typescript always emits `{}` interfaces here).
  const models = compiled
    .replace(new RegExp(`export interface ${rootName} \\{[^}]*\\}`), "")
    .replace(
      /export interface (\w+) \{\s*\}/g,
      "export type $1 = Record<string, never>;",
    )
    .trim();

  const endpointUnion = tools
    .map((t) => `  | ${JSON.stringify(t.path)}`)
    .join("\n");
  const paramsEntries = tools
    .map((t) => `  ${JSON.stringify(t.path)}: ${t.className};`)
    .join("\n");
  const endpointList = tools
    .map((t) => `  ${JSON.stringify(t.path)},`)
    .join("\n");

  const footer = [
    "/** Endpoint path for a generated tool operation (the operation identity across languages). */",
    `export type ToolEndpoint =\n${endpointUnion};`,
    "",
    "/** Backend request-parameter model for each tool endpoint. */",
    `export interface ToolApiParams {\n${paramsEntries}\n}`,
    "",
    "/** Every generated tool endpoint, for iteration. */",
    `export const TOOL_ENDPOINTS = [\n${endpointList}\n] as const satisfies readonly ToolEndpoint[];`,
    "",
    "/** Union of every generated tool request model. */",
    `export type ToolApiRequest = ToolApiParams[ToolEndpoint];`,
  ].join("\n");

  const body = `${FILE_HEADER}\n\n${models}\n\n${footer}\n`;
  const oxfmtConfig = JSON.parse(readFileSync(OXFMT_CONFIG_PATH, "utf-8"));
  const { code: formatted, errors } = await format(
    outputPath,
    body,
    oxfmtConfig,
  );
  if (errors.length > 0) {
    throw new Error(
      `oxfmt failed to format ${outputPath}:\n${errors.map((error) => error.message).join("\n")}`,
    );
  }

  if (check) {
    let current = "";
    try {
      current = readFileSync(outputPath, "utf-8");
    } catch {
      // Missing file counts as out of date.
    }
    if (current !== formatted) {
      throw new Error(
        `${outputPath} is out of date. Run 'task frontend:tool-models' and commit the result.`,
      );
    }
    console.log(`Up to date: ${tools.length} tool endpoints.`);
    return;
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, formatted, "utf-8");
  console.log(`Generated ${tools.length} tool endpoints -> ${outputPath}`);
  if (skipped.length > 0) {
    console.log(
      `Skipped ${skipped.length} POST endpoint(s) with no request body: ${skipped.join(", ")}`,
    );
  }
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
