/**
 * Generate TypeScript tool API types from the Java backend's OpenAPI spec (SwaggerDoc.json).
 *
 * The TypeScript counterpart of engine/scripts/generate_tool_models.py. Both turn the same
 * OpenAPI spec into per-operation request models so their language stays in sync with the
 * backend. They deliberately differ in one way: the Python generator strips file/binary fields
 * and reinterprets "required" because it feeds an AI that never handles file bytes. The frontend
 * DOES send files (including named file fields such as `stampImage`), so the models here are
 * complete and faithful to the spec, filtered only at the endpoint level to the real tool APIs.
 *
 * Heavy lifting (JSON Schema -> TS) is done by the off-the-shelf `json-schema-to-typescript`;
 * this script only tweaks the input (discover tool endpoints, inline component refs) and the
 * output (append the ToolEndpoint union + ToolApiParams map), mirroring the Python approach.
 *
 * Run via: task frontend:api-types   (pass --check to verify the committed file is up to date)
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { parseArgs } from "node:util";
import { compile, type JSONSchema } from "json-schema-to-typescript";
import * as prettier from "prettier";

// Namespaces exposed as callable tools. Mirrors engine ToolDiscovery.ALLOWED_PATH_PREFIXES and
// InternalApiClient's allowlist. `/api/v1/filter/` is pipeline-only, and `/api/v1/ai/tools/` is
// hand-maintained (see the agent-tool escape hatch, cf. engine agent_tool_models.py); neither is
// generated here. Extend this list when those become relevant.
const ALLOWED_PATH_PREFIXES = [
  "/api/v1/general/",
  "/api/v1/misc/",
  "/api/v1/security/",
  "/api/v1/convert/",
];

// Universal file plumbing, never a user-configurable parameter: `fileInput` is the document
// stream the pipeline feeds; `fileId` is a server-side handle. Stripped from the top-level tool
// request models only. Named file fields (stampImage, attachments, ...) are kept.
const BASE_FILE_FIELDS = new Set(["fileInput", "fileId"]);

const COMPONENT_REF_PREFIX = "#/components/schemas/";

const FILE_HEADER = [
  "// AUTO-GENERATED FILE. DO NOT EDIT.",
  "// Generated by editor/scripts/generate-tool-api-types.mts from the Java OpenAPI spec",
  "// (SwaggerDoc.json). Regenerate with: task frontend:api-types",
  "// Tools that take only a file input have no parameters; their model is Record<string, never>.",
].join("\n");

type Json = Record<string, unknown>;

interface DiscoveredTool {
  path: string;
  className: string;
}

function isObject(value: unknown): value is Json {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function pascalCase(segment: string): string {
  return segment
    .split(/[-_/]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/** Fallback class name for an inline request body (no $ref to name it after). */
function pathToClassName(path: string): string {
  const relevant = path.replace(/^\/api\/v1\//, "");
  return `${pascalCase(relevant)}Request`;
}

function dedupe(name: string, used: Set<string>): string {
  let candidate = name;
  let n = 2;
  while (used.has(candidate)) candidate = `${name}${n++}`;
  used.add(candidate);
  return candidate;
}

/** The request body schema for a POST endpoint (multipart wins, then JSON), or null. */
function requestBodySchema(pathItem: Json): Json | null {
  const post = pathItem.post;
  if (!isObject(post)) return null;
  const requestBody = post.requestBody;
  if (!isObject(requestBody)) return null;
  const content = requestBody.content;
  if (!isObject(content)) return null;
  for (const mediaType of ["multipart/form-data", "application/json"]) {
    const entry = content[mediaType];
    if (isObject(entry) && isObject(entry.schema)) return entry.schema;
  }
  return null;
}

/**
 * Query parameters declared on a POST endpoint, as a property map plus the names of the required
 * ones. A few tools (e.g. merge-pdfs' `fileOrder`) take inputs on the query string alongside the
 * multipart body, so a complete model must include them. Mirrors the Python generator's query
 * handling. Query param schemas may be `$ref`s; those are inlined later by rewriteRefs.
 */
function queryParameters(pathItem: Json): { props: Json; required: string[] } {
  const props: Json = {};
  const required: string[] = [];
  const post = pathItem.post;
  if (!isObject(post) || !Array.isArray(post.parameters))
    return { props, required };
  for (const param of post.parameters) {
    if (
      !isObject(param) ||
      param.in !== "query" ||
      typeof param.name !== "string"
    )
      continue;
    if (!isObject(param.schema)) continue;
    const schema = structuredClone(param.schema) as Json;
    if (!("description" in schema) && typeof param.description === "string") {
      schema.description = param.description;
    }
    props[param.name] = schema;
    if (param.required === true) required.push(param.name);
  }
  return { props, required };
}

/**
 * Walk a schema, rewriting every `#/components/schemas/X` ref to `#/definitions/X` in place and
 * collecting each component name encountered so the caller can inline it. Mirrors the Python
 * generator's `_rewrite_refs`.
 */
function rewriteRefs(node: unknown, found: Set<string>): void {
  if (Array.isArray(node)) {
    for (const item of node) rewriteRefs(item, found);
    return;
  }
  if (!isObject(node)) return;
  const ref = node.$ref;
  if (typeof ref === "string" && ref.startsWith(COMPONENT_REF_PREFIX)) {
    const name = ref.slice(COMPONENT_REF_PREFIX.length);
    node.$ref = `#/definitions/${name}`;
    found.add(name);
  }
  for (const value of Object.values(node)) rewriteRefs(value, found);
}

/** Drop `required` entries that have a default (the client need not send them) or were stripped. */
function computeRequired(schema: Json, properties: Json): string[] {
  const required = Array.isArray(schema.required)
    ? (schema.required as string[])
    : [];
  return required.filter((name) => {
    const prop = properties[name];
    return name in properties && !(isObject(prop) && "default" in prop);
  });
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      spec: { type: "string" },
      output: { type: "string" },
      check: { type: "boolean", default: false },
    },
  });
  if (!values.spec || !values.output) {
    throw new Error(
      "Usage: generate-tool-api-types.mts --spec <SwaggerDoc.json> --output <file.ts> [--check]",
    );
  }
  const specPath = resolve(values.spec);
  const outputPath = resolve(values.output);

  const spec = JSON.parse(readFileSync(specPath, "utf-8")) as Json;
  const paths = isObject(spec.paths) ? spec.paths : {};
  const components =
    isObject(spec.components) && isObject(spec.components.schemas)
      ? spec.components.schemas
      : {};

  const tools: DiscoveredTool[] = [];
  const definitions: Record<string, Json> = {};
  const usedClassNames = new Set<string>();
  const pendingComponents = new Set<string>();
  const skipped: string[] = [];

  for (const path of Object.keys(paths).sort()) {
    if (
      path.includes("{") ||
      !ALLOWED_PATH_PREFIXES.some((p) => path.startsWith(p))
    )
      continue;
    const pathItem = paths[path];
    if (!isObject(pathItem)) continue;
    const bodySchema = requestBodySchema(pathItem);
    if (!bodySchema) {
      if (isObject(pathItem.post)) skipped.push(path);
      continue;
    }

    // Resolve the request model into a fresh, mutable clone so we never mutate the shared spec.
    const ref = bodySchema.$ref;
    let className: string;
    let modelSchema: Json;
    if (typeof ref === "string" && ref.startsWith(COMPONENT_REF_PREFIX)) {
      const componentName = ref.slice(COMPONENT_REF_PREFIX.length);
      const component = components[componentName];
      if (!isObject(component)) continue;
      className = componentName;
      modelSchema = structuredClone(component) as Json;
    } else {
      className = pathToClassName(path);
      modelSchema = structuredClone(bodySchema) as Json;
    }

    // A component shared by several endpoints (e.g. GeneralFile) is only defined once.
    if (!(className in definitions)) {
      const uniqueName = dedupe(className, usedClassNames);
      className = uniqueName;
      const bodyProps: Json = isObject(modelSchema.properties)
        ? (structuredClone(modelSchema.properties) as Json)
        : {};
      const query = queryParameters(pathItem);
      // Body wins over query on name collision (matches the Python generator).
      const properties: Json = { ...query.props, ...bodyProps };
      for (const field of BASE_FILE_FIELDS) delete properties[field];
      modelSchema.properties = properties;
      const required = new Set(computeRequired(modelSchema, properties));
      for (const name of query.required) {
        const prop = properties[name];
        if (name in properties && !(isObject(prop) && "default" in prop)) {
          required.add(name);
        }
      }
      if (required.size > 0) modelSchema.required = [...required];
      else delete modelSchema.required;
      modelSchema.title = className;
      rewriteRefs(modelSchema, pendingComponents);
      definitions[className] = modelSchema;
    }

    tools.push({ path, className });
  }

  // Transitively inline every referenced component into `definitions`, rewriting its refs too.
  const queue = [...pendingComponents];
  while (queue.length > 0) {
    const name = queue.pop() as string;
    if (name in definitions) continue;
    const component = components[name];
    if (!isObject(component)) continue;
    const cloned = structuredClone(component) as Json;
    cloned.title = name;
    const nested = new Set<string>();
    rewriteRefs(cloned, nested);
    definitions[name] = cloned;
    for (const next of nested) if (!(next in definitions)) queue.push(next);
  }

  await compileAndWrite(
    tools,
    definitions,
    outputPath,
    values.check ?? false,
    skipped,
  );
}

async function compileAndWrite(
  tools: DiscoveredTool[],
  definitions: Record<string, Json>,
  outputPath: string,
  check: boolean,
  skipped: string[],
): Promise<void> {
  // A wrapper object whose properties reference every model, so json-schema-to-typescript emits
  // each as a named, exported interface. The wrapper interface itself is stripped afterwards.
  const rootName = "__ToolApiRootAutogen";
  const uniqueClassNames = [...new Set(tools.map((t) => t.className))];
  const rootSchema: JSONSchema = {
    title: rootName,
    type: "object",
    additionalProperties: false,
    properties: Object.fromEntries(
      uniqueClassNames.map((name) => [name, { $ref: `#/definitions/${name}` }]),
    ),
    definitions: definitions as Record<string, JSONSchema>,
  };

  const compiled = await compile(rootSchema, rootName, {
    bannerComment: "",
    additionalProperties: false,
    declareExternallyReferenced: true,
    unreachableDefinitions: false,
    strictIndexSignatures: true,
    format: false,
  });

  // Drop the wrapper interface (its lines are simple `Name: Type;` with no nested braces), then
  // rewrite empty models (tools that take only a file) to `Record<string, never>`. The library
  // has no option to avoid empty interfaces, and `Record<string, never>` is the precise, lint-clean
  // type for "an object with no properties" -- so the output needs no lint exceptions.
  const models = compiled
    .replace(new RegExp(`export interface ${rootName} \\{[^}]*\\}`), "")
    .replace(
      /export interface (\w+) \{\s*\}/g,
      "export type $1 = Record<string, never>;",
    )
    .trim();

  const endpointUnion = tools
    .map((t) => `  | ${JSON.stringify(t.path)}`)
    .join("\n");
  const paramsEntries = tools
    .map((t) => `  ${JSON.stringify(t.path)}: ${t.className};`)
    .join("\n");
  const endpointList = tools
    .map((t) => `  ${JSON.stringify(t.path)},`)
    .join("\n");

  const footer = [
    "/** Endpoint path for a generated tool operation (the operation identity across languages). */",
    `export type ToolEndpoint =\n${endpointUnion};`,
    "",
    "/** Backend request-parameter model for each tool endpoint. */",
    `export interface ToolApiParams {\n${paramsEntries}\n}`,
    "",
    "/** Every generated tool endpoint, for iteration. */",
    `export const TOOL_ENDPOINTS = [\n${endpointList}\n] as const satisfies readonly ToolEndpoint[];`,
    "",
    "/** Union of every generated tool request model. */",
    `export type ToolApiRequest = ToolApiParams[ToolEndpoint];`,
  ].join("\n");

  const body = `${FILE_HEADER}\n\n${models}\n\n${footer}\n`;
  const prettierConfig = await prettier.resolveConfig(outputPath);
  const formatted = await prettier.format(body, {
    ...prettierConfig,
    parser: "typescript",
  });

  if (check) {
    let current = "";
    try {
      current = readFileSync(outputPath, "utf-8");
    } catch {
      // Missing file counts as out of date.
    }
    if (current !== formatted) {
      throw new Error(
        `${outputPath} is out of date. Run 'task frontend:api-types' and commit the result.`,
      );
    }
    console.log(`Up to date: ${tools.length} tool endpoints.`);
    return;
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, formatted, "utf-8");
  console.log(`Generated ${tools.length} tool endpoints -> ${outputPath}`);
  if (skipped.length > 0) {
    console.log(
      `Skipped ${skipped.length} POST endpoint(s) with no request body: ${skipped.join(", ")}`,
    );
  }
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
