# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by scripts/generate_tool_models.py from Java OpenAPI spec (SwaggerDoc.json).
# ruff: noqa: E501

from __future__ import annotations

from enum import StrEnum

from pydantic import RootModel

from stirling.models.base import ApiModel


class AddAttachmentsParams(ApiModel):
    attachments: list[bytes] | None = None
    convert_to_pdf_a3b: bool | None = None


class AddCommentsParams(ApiModel):
    comments: str | None = None


class AddImageParams(ApiModel):
    every_page: bool | None = None
    x: float | None = None
    y: float | None = None


class AddPageNumbersParams(ApiModel):
    custom_margin: str | None = None
    custom_text: str | None = None
    font_color: str | None = None
    font_size: float | None = None
    font_type: str | None = None
    pages_to_number: str | None = None
    position: int | None = None
    starting_number: int | None = None
    zero_pad: int | None = None


class AddPasswordParams(ApiModel):
    key_length: int | None = None
    owner_password: str | None = None
    password: str | None = None
    prevent_assembly: bool | None = None
    prevent_extract_content: bool | None = None
    prevent_extract_for_accessibility: bool | None = None
    prevent_fill_in_form: bool | None = None
    prevent_modify: bool | None = None
    prevent_modify_annotations: bool | None = None
    prevent_printing: bool | None = None
    prevent_printing_faithful: bool | None = None


class AddStampParams(ApiModel):
    alphabet: str | None = None
    custom_color: str | None = None
    custom_margin: str | None = None
    font_size: float | None = None
    opacity: float | None = None
    override_x: float | None = None
    override_y: float | None = None
    page_numbers: str | None = None
    position: int | None = None
    rotation: float | None = None
    stamp_text: str | None = None
    stamp_type: str | None = None


class AddWatermarkParams(ApiModel):
    alphabet: str | None = None
    convert_pdf_to_image: bool | None = None
    custom_color: str | None = None
    font_size: float | None = None
    height_spacer: int | None = None
    opacity: float | None = None
    rotation: float | None = None
    watermark_text: str | None = None
    watermark_type: str | None = None
    width_spacer: int | None = None


class AutoRedactParams(ApiModel):
    convert_pdf_to_image: bool | None = None
    custom_padding: float | None = None
    list_of_text: str | None = None
    redact_color: str | None = None
    use_regex: bool | None = None
    whole_word_search: bool | None = None


class AutoRenameParams(ApiModel):
    use_first_text_as_fallback: bool | None = None


class AutoSplitPdfParams(ApiModel):
    duplex_mode: bool | None = None


class BookletImpositionParams(ApiModel):
    add_border: bool | None = None
    add_gutter: bool | None = None
    double_sided: bool | None = None
    duplex_pass: str | None = None
    flip_on_short_edge: bool | None = None
    gutter_size: float | None = None
    pages_per_sheet: int | None = None
    spine_location: str | None = None


class CbrToPdfParams(ApiModel):
    optimize_for_ebook: bool | None = None


class CbzToPdfParams(ApiModel):
    optimize_for_ebook: bool | None = None


class CertSignParams(ApiModel):
    cert_type: str | None = None
    location: str | None = None
    name: str | None = None
    page_number: int | None = None
    password: str | None = None
    reason: str | None = None
    show_logo: bool | None = None
    show_signature: bool | None = None


class CompressPdfParams(ApiModel):
    expected_output_size: str | None = None
    grayscale: bool | None = None
    line_art: bool | None = None
    line_art_edge_level: int | None = None
    line_art_threshold: float | None = None
    linearize: bool | None = None
    normalize: bool | None = None
    optimize_level: int | None = None


class CropParams(ApiModel):
    auto_crop: bool | None = None
    height: float | None = None
    remove_data_outside_crop: bool | None = None
    width: float | None = None
    x: float | None = None
    y: float | None = None


class DeleteAttachmentParams(ApiModel):
    attachment_name: str | None = None


class EbookToPdfParams(ApiModel):
    embed_all_fonts: bool | None = None
    include_page_numbers: bool | None = None
    include_table_of_contents: bool | None = None
    optimize_for_ebook: bool | None = None


class EditTableOfContentsParams(ApiModel):
    bookmark_data: str | None = None
    replace_existing: bool | None = None


class EditTextParams(ApiModel):
    edits: str | None = None
    page_numbers: str | None = None
    whole_word_search: bool | None = None


class EmlToPdfParams(ApiModel):
    download_html: bool | None = None
    include_all_recipients: bool | None = None
    include_attachments: bool | None = None
    max_attachment_size_mb: int | None = None


class ExtractImageScansParams(ApiModel):
    angle_threshold: int | None = None
    border_size: int | None = None
    min_area: int | None = None
    min_contour_area: int | None = None
    tolerance: int | None = None


class ExtractImagesParams(ApiModel):
    format: str | None = None


class FlattenParams(ApiModel):
    flatten_only_forms: bool | None = None
    render_dpi: int | None = None


class HtmlToPdfParams(ApiModel):
    zoom: float | None = None


class ImgToPdfParams(ApiModel):
    auto_rotate: bool | None = None
    color_type: str | None = None
    fit_option: str | None = None


class MergePdfsParams(ApiModel):
    client_file_ids: str | None = None
    file_order: str | None = None
    generate_toc: bool | None = None
    remove_cert_sign: bool | None = None
    sort_type: str | None = None


class MultiPageLayoutParams(ApiModel):
    add_border: bool | None = None
    arrangement: str | None = None
    border_width: int | None = None
    bottom_margin: int | None = None
    cols: int | None = None
    inner_margin: int | None = None
    left_margin: int | None = None
    mode: str | None = None
    orientation: str | None = None
    pages_per_sheet: int | None = None
    reading_direction: str | None = None
    right_margin: int | None = None
    rows: int | None = None
    top_margin: int | None = None


class OcrPdfParams(ApiModel):
    clean: bool | None = None
    clean_final: bool | None = None
    deskew: bool | None = None
    languages: list[str] | None = None
    ocr_render_type: str | None = None
    ocr_type: str | None = None
    remove_images_after: bool | None = None
    sidecar: bool | None = None


class OverlayPdfsParams(ApiModel):
    counts: list[int] | None = None
    overlay_files: list[bytes] | None = None
    overlay_mode: str | None = None
    overlay_position: int | None = None


class PdfToCbrParams(ApiModel):
    dpi: int | None = None


class PdfToCbzParams(ApiModel):
    dpi: int | None = None


class PdfToCsvParams(ApiModel):
    page_numbers: str | None = None


class OutputFormat(StrEnum):
    epub = "EPUB"
    azw3 = "AZW3"


class TargetDevice(StrEnum):
    tablet_phone_images = "TABLET_PHONE_IMAGES"
    kindle_eink_text = "KINDLE_EINK_TEXT"


class PdfToEpubParams(ApiModel):
    detect_chapters: bool | None = None
    output_format: OutputFormat | None = None
    target_device: TargetDevice | None = None


class PdfToImgParams(ApiModel):
    color_type: str | None = None
    dpi: int | None = None
    image_format: str | None = None
    include_annotations: bool | None = None
    page_numbers: str | None = None
    single_or_multiple: str | None = None


class PdfToPdfaParams(ApiModel):
    output_format: str | None = None
    strict: bool | None = None


class PdfToPresentationParams(ApiModel):
    output_format: str | None = None


class PdfToTextEditorParams(ApiModel):
    lightweight: bool | None = None


class PdfToTextParams(ApiModel):
    output_format: str | None = None


class PdfToVectorParams(ApiModel):
    output_format: str | None = None


class PdfToWordParams(ApiModel):
    output_format: str | None = None


class PdfToXlsxParams(ApiModel):
    page_numbers: str | None = None


class RearrangePagesParams(ApiModel):
    custom_mode: str | None = None
    page_numbers: str | None = None


class RedactExecuteParams(ApiModel):
    image_boxes: str | None = None
    ranges: str | None = None
    redact_image_pages: str | None = None
    regex_patterns: str | None = None
    style: str | None = None
    text_values: str | None = None
    wipe_pages: str | None = None


class RedactParams(ApiModel):
    convert_pdf_to_image: bool | None = None
    page_numbers: str | None = None
    page_redaction_color: str | None = None
    redactions: str | None = None


class RemoveBlanksParams(ApiModel):
    threshold: int | None = None
    white_percent: float | None = None


class RemovePagesParams(ApiModel):
    page_numbers: str | None = None


class RemovePasswordParams(ApiModel):
    password: str | None = None


class RenameAttachmentParams(ApiModel):
    attachment_name: str | None = None
    new_name: str | None = None


class HighContrastColorCombination(StrEnum):
    white_text_on_black = "WHITE_TEXT_ON_BLACK"
    black_text_on_white = "BLACK_TEXT_ON_WHITE"
    yellow_text_on_black = "YELLOW_TEXT_ON_BLACK"
    green_text_on_black = "GREEN_TEXT_ON_BLACK"


class ReplaceAndInvertOption(StrEnum):
    high_contrast_color = "HIGH_CONTRAST_COLOR"
    custom_color = "CUSTOM_COLOR"
    full_inversion = "FULL_INVERSION"
    color_space_conversion = "COLOR_SPACE_CONVERSION"


class ReplaceInvertPdfParams(ApiModel):
    back_ground_color: str | None = None
    high_contrast_color_combination: HighContrastColorCombination | None = None
    replace_and_invert_option: ReplaceAndInvertOption | None = None
    text_color: str | None = None


class RotatePdfParams(ApiModel):
    angle: int | None = None


class SanitizePdfParams(ApiModel):
    remove_embedded_files: bool | None = None
    remove_fonts: bool | None = None
    remove_java_script: bool | None = None
    remove_links: bool | None = None
    remove_metadata: bool | None = None
    remove_xmp_metadata: bool | None = None


class ScalePagesParams(ApiModel):
    orientation: str | None = None
    page_size: str | None = None
    scale_factor: float | None = None


class Colorspace(StrEnum):
    grayscale = "grayscale"
    color = "color"


class Quality(StrEnum):
    low = "low"
    medium = "medium"
    high = "high"


class Rotation(StrEnum):
    none = "none"
    slight = "slight"
    moderate = "moderate"
    severe = "severe"


class ScannerEffectParams(ApiModel):
    advanced_enabled: bool | None = None
    blur: float | None = None
    border: int | None = None
    brightness: float | None = None
    colorspace: Colorspace | None = None
    contrast: float | None = None
    noise: float | None = None
    quality: Quality | None = None
    resolution: int | None = None
    rotate: int | None = None
    rotate_variance: int | None = None
    rotation: Rotation | None = None
    yellowish: bool | None = None


class SendEmailParams(ApiModel):
    body: str | None = None
    subject: str | None = None
    to: str | None = None


class WorkflowType(StrEnum):
    signing = "SIGNING"
    review = "REVIEW"
    approval = "APPROVAL"


class SessionsParams(ApiModel):
    document_name: str | None = None
    due_date: str | None = None
    message: str | None = None
    owner_email: str | None = None
    participant_emails: list[str] | None = None
    participant_user_ids: list[int] | None = None
    workflow_metadata: str | None = None
    workflow_type: WorkflowType | None = None


class SplitBySizeOrCountParams(ApiModel):
    split_type: int | None = None
    split_value: str | None = None


class SplitForPosterPrintParams(ApiModel):
    page_size: str | None = None
    right_to_left: bool | None = None
    x_factor: int | None = None
    y_factor: int | None = None


class SplitPagesParams(ApiModel):
    page_numbers: str | None = None


class SplitPdfByChaptersParams(ApiModel):
    allow_duplicates: bool | None = None
    bookmark_level: int | None = None
    include_metadata: bool | None = None


class SplitPdfBySectionsParams(ApiModel):
    horizontal_divisions: int | None = None
    merge: bool | None = None
    page_numbers: str | None = None
    split_mode: str | None = None
    vertical_divisions: int | None = None


class SvgToPdfParams(ApiModel):
    combine_into_single_pdf: bool | None = None


class TimestampPdfParams(ApiModel):
    tsa_url: str | None = None


class UpdateMetadataParams(ApiModel):
    all_request_params: str | None = None
    author: str | None = None
    creation_date: str | None = None
    creator: str | None = None
    delete_all: bool | None = None
    keywords: str | None = None
    modification_date: str | None = None
    producer: str | None = None
    subject: str | None = None
    title: str | None = None
    trapped: str | None = None


class UrlToPdfParams(ApiModel):
    url_input: str | None = None


class ValidateCertificateParams(ApiModel):
    cert_type: str | None = None
    password: str | None = None


class VectorToPdfParams(ApiModel):
    prepress: bool | None = None


class Model(
    RootModel[
        CbrToPdfParams
        | CbzToPdfParams
        | EbookToPdfParams
        | EmlToPdfParams
        | HtmlToPdfParams
        | ImgToPdfParams
        | PdfToCbrParams
        | PdfToCbzParams
        | PdfToCsvParams
        | PdfToEpubParams
        | PdfToImgParams
        | PdfToPdfaParams
        | PdfToPresentationParams
        | PdfToTextParams
        | PdfToTextEditorParams
        | PdfToVectorParams
        | PdfToWordParams
        | PdfToXlsxParams
        | SvgToPdfParams
        | UrlToPdfParams
        | VectorToPdfParams
        | BookletImpositionParams
        | CropParams
        | EditTableOfContentsParams
        | EditTextParams
        | MergePdfsParams
        | MultiPageLayoutParams
        | OverlayPdfsParams
        | RearrangePagesParams
        | RemovePagesParams
        | RotatePdfParams
        | ScalePagesParams
        | SendEmailParams
        | SplitBySizeOrCountParams
        | SplitForPosterPrintParams
        | SplitPagesParams
        | SplitPdfByChaptersParams
        | SplitPdfBySectionsParams
        | AddAttachmentsParams
        | AddCommentsParams
        | AddImageParams
        | AddPageNumbersParams
        | AddStampParams
        | AutoRenameParams
        | AutoSplitPdfParams
        | CompressPdfParams
        | DeleteAttachmentParams
        | ExtractImageScansParams
        | ExtractImagesParams
        | FlattenParams
        | OcrPdfParams
        | RemoveBlanksParams
        | RenameAttachmentParams
        | ReplaceInvertPdfParams
        | ScannerEffectParams
        | UpdateMetadataParams
        | AddPasswordParams
        | AddWatermarkParams
        | AutoRedactParams
        | CertSignParams
        | SessionsParams
        | ValidateCertificateParams
        | RedactParams
        | RedactExecuteParams
        | RemovePasswordParams
        | SanitizePdfParams
        | TimestampPdfParams
    ]
):
    root: (
        CbrToPdfParams
        | CbzToPdfParams
        | EbookToPdfParams
        | EmlToPdfParams
        | HtmlToPdfParams
        | ImgToPdfParams
        | PdfToCbrParams
        | PdfToCbzParams
        | PdfToCsvParams
        | PdfToEpubParams
        | PdfToImgParams
        | PdfToPdfaParams
        | PdfToPresentationParams
        | PdfToTextParams
        | PdfToTextEditorParams
        | PdfToVectorParams
        | PdfToWordParams
        | PdfToXlsxParams
        | SvgToPdfParams
        | UrlToPdfParams
        | VectorToPdfParams
        | BookletImpositionParams
        | CropParams
        | EditTableOfContentsParams
        | EditTextParams
        | MergePdfsParams
        | MultiPageLayoutParams
        | OverlayPdfsParams
        | RearrangePagesParams
        | RemovePagesParams
        | RotatePdfParams
        | ScalePagesParams
        | SendEmailParams
        | SplitBySizeOrCountParams
        | SplitForPosterPrintParams
        | SplitPagesParams
        | SplitPdfByChaptersParams
        | SplitPdfBySectionsParams
        | AddAttachmentsParams
        | AddCommentsParams
        | AddImageParams
        | AddPageNumbersParams
        | AddStampParams
        | AutoRenameParams
        | AutoSplitPdfParams
        | CompressPdfParams
        | DeleteAttachmentParams
        | ExtractImageScansParams
        | ExtractImagesParams
        | FlattenParams
        | OcrPdfParams
        | RemoveBlanksParams
        | RenameAttachmentParams
        | ReplaceInvertPdfParams
        | ScannerEffectParams
        | UpdateMetadataParams
        | AddPasswordParams
        | AddWatermarkParams
        | AutoRedactParams
        | CertSignParams
        | SessionsParams
        | ValidateCertificateParams
        | RedactParams
        | RedactExecuteParams
        | RemovePasswordParams
        | SanitizePdfParams
        | TimestampPdfParams
    )


type ParamToolModel = (
    CbrToPdfParams
    | CbzToPdfParams
    | EbookToPdfParams
    | EmlToPdfParams
    | HtmlToPdfParams
    | ImgToPdfParams
    | PdfToCbrParams
    | PdfToCbzParams
    | PdfToCsvParams
    | PdfToEpubParams
    | PdfToImgParams
    | PdfToPdfaParams
    | PdfToPresentationParams
    | PdfToTextParams
    | PdfToTextEditorParams
    | PdfToVectorParams
    | PdfToWordParams
    | PdfToXlsxParams
    | SvgToPdfParams
    | UrlToPdfParams
    | VectorToPdfParams
    | BookletImpositionParams
    | CropParams
    | EditTableOfContentsParams
    | EditTextParams
    | MergePdfsParams
    | MultiPageLayoutParams
    | OverlayPdfsParams
    | RearrangePagesParams
    | RemovePagesParams
    | RotatePdfParams
    | ScalePagesParams
    | SendEmailParams
    | SplitBySizeOrCountParams
    | SplitForPosterPrintParams
    | SplitPagesParams
    | SplitPdfByChaptersParams
    | SplitPdfBySectionsParams
    | AddAttachmentsParams
    | AddCommentsParams
    | AddImageParams
    | AddPageNumbersParams
    | AddStampParams
    | AutoRenameParams
    | AutoSplitPdfParams
    | CompressPdfParams
    | DeleteAttachmentParams
    | ExtractImageScansParams
    | ExtractImagesParams
    | FlattenParams
    | OcrPdfParams
    | RemoveBlanksParams
    | RenameAttachmentParams
    | ReplaceInvertPdfParams
    | ScannerEffectParams
    | UpdateMetadataParams
    | AddPasswordParams
    | AddWatermarkParams
    | AutoRedactParams
    | CertSignParams
    | SessionsParams
    | ValidateCertificateParams
    | RedactParams
    | RedactExecuteParams
    | RemovePasswordParams
    | SanitizePdfParams
    | TimestampPdfParams
)
type ParamToolModelType = type[ParamToolModel]


class ToolEndpoint(StrEnum):
    CBR_TO_PDF = "/api/v1/convert/cbr/pdf"
    CBZ_TO_PDF = "/api/v1/convert/cbz/pdf"
    EBOOK_TO_PDF = "/api/v1/convert/ebook/pdf"
    EML_TO_PDF = "/api/v1/convert/eml/pdf"
    HTML_TO_PDF = "/api/v1/convert/html/pdf"
    IMG_TO_PDF = "/api/v1/convert/img/pdf"
    PDF_TO_CBR = "/api/v1/convert/pdf/cbr"
    PDF_TO_CBZ = "/api/v1/convert/pdf/cbz"
    PDF_TO_CSV = "/api/v1/convert/pdf/csv"
    PDF_TO_EPUB = "/api/v1/convert/pdf/epub"
    PDF_TO_IMG = "/api/v1/convert/pdf/img"
    PDF_TO_PDFA = "/api/v1/convert/pdf/pdfa"
    PDF_TO_PRESENTATION = "/api/v1/convert/pdf/presentation"
    PDF_TO_TEXT = "/api/v1/convert/pdf/text"
    PDF_TO_TEXT_EDITOR = "/api/v1/convert/pdf/text-editor"
    PDF_TO_VECTOR = "/api/v1/convert/pdf/vector"
    PDF_TO_WORD = "/api/v1/convert/pdf/word"
    PDF_TO_XLSX = "/api/v1/convert/pdf/xlsx"
    SVG_TO_PDF = "/api/v1/convert/svg/pdf"
    URL_TO_PDF = "/api/v1/convert/url/pdf"
    VECTOR_TO_PDF = "/api/v1/convert/vector/pdf"
    BOOKLET_IMPOSITION = "/api/v1/general/booklet-imposition"
    CROP = "/api/v1/general/crop"
    EDIT_TABLE_OF_CONTENTS = "/api/v1/general/edit-table-of-contents"
    EDIT_TEXT = "/api/v1/general/edit-text"
    MERGE_PDFS = "/api/v1/general/merge-pdfs"
    MULTI_PAGE_LAYOUT = "/api/v1/general/multi-page-layout"
    OVERLAY_PDFS = "/api/v1/general/overlay-pdfs"
    REARRANGE_PAGES = "/api/v1/general/rearrange-pages"
    REMOVE_PAGES = "/api/v1/general/remove-pages"
    ROTATE_PDF = "/api/v1/general/rotate-pdf"
    SCALE_PAGES = "/api/v1/general/scale-pages"
    SEND_EMAIL = "/api/v1/general/send-email"
    SPLIT_BY_SIZE_OR_COUNT = "/api/v1/general/split-by-size-or-count"
    SPLIT_FOR_POSTER_PRINT = "/api/v1/general/split-for-poster-print"
    SPLIT_PAGES = "/api/v1/general/split-pages"
    SPLIT_PDF_BY_CHAPTERS = "/api/v1/general/split-pdf-by-chapters"
    SPLIT_PDF_BY_SECTIONS = "/api/v1/general/split-pdf-by-sections"
    ADD_ATTACHMENTS = "/api/v1/misc/add-attachments"
    ADD_COMMENTS = "/api/v1/misc/add-comments"
    ADD_IMAGE = "/api/v1/misc/add-image"
    ADD_PAGE_NUMBERS = "/api/v1/misc/add-page-numbers"
    ADD_STAMP = "/api/v1/misc/add-stamp"
    AUTO_RENAME = "/api/v1/misc/auto-rename"
    AUTO_SPLIT_PDF = "/api/v1/misc/auto-split-pdf"
    COMPRESS_PDF = "/api/v1/misc/compress-pdf"
    DELETE_ATTACHMENT = "/api/v1/misc/delete-attachment"
    EXTRACT_IMAGE_SCANS = "/api/v1/misc/extract-image-scans"
    EXTRACT_IMAGES = "/api/v1/misc/extract-images"
    FLATTEN = "/api/v1/misc/flatten"
    OCR_PDF = "/api/v1/misc/ocr-pdf"
    REMOVE_BLANKS = "/api/v1/misc/remove-blanks"
    RENAME_ATTACHMENT = "/api/v1/misc/rename-attachment"
    REPLACE_INVERT_PDF = "/api/v1/misc/replace-invert-pdf"
    SCANNER_EFFECT = "/api/v1/misc/scanner-effect"
    UPDATE_METADATA = "/api/v1/misc/update-metadata"
    ADD_PASSWORD = "/api/v1/security/add-password"
    ADD_WATERMARK = "/api/v1/security/add-watermark"
    AUTO_REDACT = "/api/v1/security/auto-redact"
    CERT_SIGN = "/api/v1/security/cert-sign"
    SESSIONS = "/api/v1/security/cert-sign/sessions"
    VALIDATE_CERTIFICATE = "/api/v1/security/cert-sign/validate-certificate"
    REDACT = "/api/v1/security/redact"
    REDACT_EXECUTE = "/api/v1/security/redact-execute"
    REMOVE_PASSWORD = "/api/v1/security/remove-password"
    SANITIZE_PDF = "/api/v1/security/sanitize-pdf"
    TIMESTAMP_PDF = "/api/v1/security/timestamp-pdf"


OPERATIONS: dict[ToolEndpoint, ParamToolModelType] = {
    ToolEndpoint.CBR_TO_PDF: CbrToPdfParams,
    ToolEndpoint.CBZ_TO_PDF: CbzToPdfParams,
    ToolEndpoint.EBOOK_TO_PDF: EbookToPdfParams,
    ToolEndpoint.EML_TO_PDF: EmlToPdfParams,
    ToolEndpoint.HTML_TO_PDF: HtmlToPdfParams,
    ToolEndpoint.IMG_TO_PDF: ImgToPdfParams,
    ToolEndpoint.PDF_TO_CBR: PdfToCbrParams,
    ToolEndpoint.PDF_TO_CBZ: PdfToCbzParams,
    ToolEndpoint.PDF_TO_CSV: PdfToCsvParams,
    ToolEndpoint.PDF_TO_EPUB: PdfToEpubParams,
    ToolEndpoint.PDF_TO_IMG: PdfToImgParams,
    ToolEndpoint.PDF_TO_PDFA: PdfToPdfaParams,
    ToolEndpoint.PDF_TO_PRESENTATION: PdfToPresentationParams,
    ToolEndpoint.PDF_TO_TEXT: PdfToTextParams,
    ToolEndpoint.PDF_TO_TEXT_EDITOR: PdfToTextEditorParams,
    ToolEndpoint.PDF_TO_VECTOR: PdfToVectorParams,
    ToolEndpoint.PDF_TO_WORD: PdfToWordParams,
    ToolEndpoint.PDF_TO_XLSX: PdfToXlsxParams,
    ToolEndpoint.SVG_TO_PDF: SvgToPdfParams,
    ToolEndpoint.URL_TO_PDF: UrlToPdfParams,
    ToolEndpoint.VECTOR_TO_PDF: VectorToPdfParams,
    ToolEndpoint.BOOKLET_IMPOSITION: BookletImpositionParams,
    ToolEndpoint.CROP: CropParams,
    ToolEndpoint.EDIT_TABLE_OF_CONTENTS: EditTableOfContentsParams,
    ToolEndpoint.EDIT_TEXT: EditTextParams,
    ToolEndpoint.MERGE_PDFS: MergePdfsParams,
    ToolEndpoint.MULTI_PAGE_LAYOUT: MultiPageLayoutParams,
    ToolEndpoint.OVERLAY_PDFS: OverlayPdfsParams,
    ToolEndpoint.REARRANGE_PAGES: RearrangePagesParams,
    ToolEndpoint.REMOVE_PAGES: RemovePagesParams,
    ToolEndpoint.ROTATE_PDF: RotatePdfParams,
    ToolEndpoint.SCALE_PAGES: ScalePagesParams,
    ToolEndpoint.SEND_EMAIL: SendEmailParams,
    ToolEndpoint.SPLIT_BY_SIZE_OR_COUNT: SplitBySizeOrCountParams,
    ToolEndpoint.SPLIT_FOR_POSTER_PRINT: SplitForPosterPrintParams,
    ToolEndpoint.SPLIT_PAGES: SplitPagesParams,
    ToolEndpoint.SPLIT_PDF_BY_CHAPTERS: SplitPdfByChaptersParams,
    ToolEndpoint.SPLIT_PDF_BY_SECTIONS: SplitPdfBySectionsParams,
    ToolEndpoint.ADD_ATTACHMENTS: AddAttachmentsParams,
    ToolEndpoint.ADD_COMMENTS: AddCommentsParams,
    ToolEndpoint.ADD_IMAGE: AddImageParams,
    ToolEndpoint.ADD_PAGE_NUMBERS: AddPageNumbersParams,
    ToolEndpoint.ADD_STAMP: AddStampParams,
    ToolEndpoint.AUTO_RENAME: AutoRenameParams,
    ToolEndpoint.AUTO_SPLIT_PDF: AutoSplitPdfParams,
    ToolEndpoint.COMPRESS_PDF: CompressPdfParams,
    ToolEndpoint.DELETE_ATTACHMENT: DeleteAttachmentParams,
    ToolEndpoint.EXTRACT_IMAGE_SCANS: ExtractImageScansParams,
    ToolEndpoint.EXTRACT_IMAGES: ExtractImagesParams,
    ToolEndpoint.FLATTEN: FlattenParams,
    ToolEndpoint.OCR_PDF: OcrPdfParams,
    ToolEndpoint.REMOVE_BLANKS: RemoveBlanksParams,
    ToolEndpoint.RENAME_ATTACHMENT: RenameAttachmentParams,
    ToolEndpoint.REPLACE_INVERT_PDF: ReplaceInvertPdfParams,
    ToolEndpoint.SCANNER_EFFECT: ScannerEffectParams,
    ToolEndpoint.UPDATE_METADATA: UpdateMetadataParams,
    ToolEndpoint.ADD_PASSWORD: AddPasswordParams,
    ToolEndpoint.ADD_WATERMARK: AddWatermarkParams,
    ToolEndpoint.AUTO_REDACT: AutoRedactParams,
    ToolEndpoint.CERT_SIGN: CertSignParams,
    ToolEndpoint.SESSIONS: SessionsParams,
    ToolEndpoint.VALIDATE_CERTIFICATE: ValidateCertificateParams,
    ToolEndpoint.REDACT: RedactParams,
    ToolEndpoint.REDACT_EXECUTE: RedactExecuteParams,
    ToolEndpoint.REMOVE_PASSWORD: RemovePasswordParams,
    ToolEndpoint.SANITIZE_PDF: SanitizePdfParams,
    ToolEndpoint.TIMESTAMP_PDF: TimestampPdfParams,
}
