import type { Meta, StoryObj } from "@storybook/react-vite";
import { DeveloperDocs } from "@portal/views/DeveloperDocs";

// Renders the real docs manifest (generated by scripts/sync-portal-docs.mts), so
// this story is a live view of the auto-built Documentation browser. The view
// fills its container's height (independent sidebar/content scroll), so the
// decorator gives it a viewport-height frame.
const meta: Meta<typeof DeveloperDocs> = {
  title: "Portal/DeveloperDocs/View",
  component: DeveloperDocs,
  parameters: { layout: "fullscreen" },
  decorators: [
    (Story) => (
      <div style={{ height: "100vh" }}>
        <Story />
      </div>
    ),
  ],
};
export default meta;

type Story = StoryObj<typeof DeveloperDocs>;

export const Default: Story = {};
