package stirling.software.proprietary.security.model;

import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDateTime;

import org.junit.jupiter.api.Test;

class JwtSigningKeyTest {

    @Test
    void testDefaultConstructor() {
        JwtSigningKey key = new JwtSigningKey();
        
        assertNull(key.getId());
        assertNull(key.getKeyId());
        assertNull(key.getPublicKey());
        assertEquals("RS256", key.getAlgorithm());
        assertNull(key.getCreatedAt());
        assertTrue(key.getIsActive());
    }

    @Test
    void testParameterizedConstructor() {
        String keyId = "test-key-123";
        String publicKey = "test-public-key-content";
        String algorithm = "RS256";
        
        JwtSigningKey key = new JwtSigningKey(keyId, publicKey, algorithm);
        
        assertNull(key.getId()); // Auto-generated by JPA
        assertEquals(keyId, key.getKeyId());
        assertEquals(publicKey, key.getPublicKey());
        assertEquals(algorithm, key.getAlgorithm());
        assertNotNull(key.getCreatedAt());
        assertTrue(key.getIsActive());
        
        // Verify created time is recent (within last few seconds)
        assertTrue(key.getCreatedAt().isAfter(LocalDateTime.now().minusSeconds(5)));
        assertTrue(key.getCreatedAt().isBefore(LocalDateTime.now().plusSeconds(1)));
    }

    @Test
    void testSettersAndGetters() {
        JwtSigningKey key = new JwtSigningKey();
        
        Long id = 1L;
        String keyId = "test-key-456";
        String publicKey = "public-key-content";
        String algorithm = "RS512";
        LocalDateTime now = LocalDateTime.now();
        Boolean isActive = false;
        
        key.setId(id);
        key.setKeyId(keyId);
        key.setPublicKey(publicKey);
        key.setAlgorithm(algorithm);
        key.setCreatedAt(now);
        key.setIsActive(isActive);
        
        assertEquals(id, key.getId());
        assertEquals(keyId, key.getKeyId());
        assertEquals(publicKey, key.getPublicKey());
        assertEquals(algorithm, key.getAlgorithm());
        assertEquals(now, key.getCreatedAt());
        assertEquals(isActive, key.getIsActive());
    }

    @Test
    void testEqualsAndHashCode() {
        JwtSigningKey key1 = new JwtSigningKey("key-123", "public-key", "RS256");
        key1.setId(1L);
        
        JwtSigningKey key2 = new JwtSigningKey("key-456", "other-public-key", "RS512");
        key2.setId(1L);
        
        JwtSigningKey key3 = new JwtSigningKey("key-789", "another-public-key", "RS256");
        key3.setId(2L);
        
        // Objects with same ID should be equal (based on @EqualsAndHashCode.Include on id)
        assertEquals(key1, key2);
        assertEquals(key1.hashCode(), key2.hashCode());
        
        // Objects with different ID should not be equal
        assertNotEquals(key1, key3);
        assertNotEquals(key1.hashCode(), key3.hashCode());
    }

    @Test
    void testToString() {
        JwtSigningKey key = new JwtSigningKey("test-key", "public-key", "RS256");
        key.setId(1L);
        
        String toString = key.toString();
        
        // Should include fields marked with @ToString.Include
        assertTrue(toString.contains("1")); // id
        assertTrue(toString.contains("test-key")); // keyId
        assertTrue(toString.contains("true")); // isActive
        assertFalse(toString.contains("public-key")); // publicKey should not be in toString
    }

    @Test
    void testAlgorithmDefault() {
        JwtSigningKey key = new JwtSigningKey("key-id", "public-key", null);
        
        // When null is passed to constructor, it should be null (constructor doesn't set default)
        assertNull(key.getAlgorithm());
        
        // Default value is only set through field initialization for no-arg constructor
        JwtSigningKey defaultKey = new JwtSigningKey();
        assertEquals("RS256", defaultKey.getAlgorithm());
    }

    @Test
    void testIsActiveDefault() {
        JwtSigningKey key = new JwtSigningKey("key-id", "public-key", "RS256");
        
        assertTrue(key.getIsActive());
    }
}