// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by editor/scripts/generate-tool-api-types.mts from the Java OpenAPI spec
// (SwaggerDoc.json). Regenerate with: task frontend:tool-models

/**
 * What each tool endpoint accepts and produces, so a chain can be checked while it is being
 * edited rather than by running it. Declared in Java with `@ToolIO`; see
 * `utils/toolIOCompat` for the compatibility rules that read this table.
 */

import { type ToolEndpoint } from "@app/types/toolApiTypes";

/** The kind of file a tool consumes or produces. `ANY` accepts or produces anything; `NONE` means no file at all. */
export type ToolFormat =
  | "PDF"
  | "PDF_ENCRYPTED"
  | "IMAGE"
  | "ZIP"
  | "WORD"
  | "PPT"
  | "EXCEL"
  | "CSV"
  | "HTML"
  | "XML"
  | "JSON"
  | "TEXT"
  | "MARKDOWN"
  | "JAVASCRIPT"
  | "EBOOK"
  | "EMAIL"
  | "POSTSCRIPT"
  | "PCL"
  | "XPS"
  | "VIDEO"
  | "CBZ"
  | "CBR"
  | "ANY"
  | "NONE";

/** Every format, for iteration. */
export const TOOL_FORMATS = [
  "PDF",
  "PDF_ENCRYPTED",
  "IMAGE",
  "ZIP",
  "WORD",
  "PPT",
  "EXCEL",
  "CSV",
  "HTML",
  "XML",
  "JSON",
  "TEXT",
  "MARKDOWN",
  "JAVASCRIPT",
  "EBOOK",
  "EMAIL",
  "POSTSCRIPT",
  "PCL",
  "XPS",
  "VIDEO",
  "CBZ",
  "CBR",
  "ANY",
  "NONE",
] as const satisfies readonly ToolFormat[];

/** How many files go in and come out. A multi-output tool returns its results zipped, and the caller unpacks them. */
export type ToolArity = "SISO" | "SIMO" | "MISO" | "MIMO";

/** One condition on a request parameter, guarding a {@link ToolIOCase}. */
export interface ToolIOWhen {
  param: string;
  matches: string[];
}

/** An output that applies when every condition in `when` holds. */
export interface ToolIOCase {
  when: ToolIOWhen[];
  produces: ToolFormat;
  arity: ToolArity;
}

/** What one endpoint accepts and produces. */
export interface ToolIOSpec {
  accepts: ToolFormat[];
  produces: ToolFormat;
  arity: ToolArity;
  cases?: ToolIOCase[];
}

/**
 * What each endpoint accepts and produces, keyed by {@link ToolEndpoint} so the paths live in
 * exactly one place. Partial: endpoints that manage a session, a device or a stored resource
 * rather than transform a document declare nothing.
 */
export type ToolIOTable = Partial<Record<ToolEndpoint, ToolIOSpec>>;

export const TOOL_IO: ToolIOTable = {
  "/api/v1/convert/cbr/pdf": {
    accepts: ["CBR"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/convert/cbz/pdf": {
    accepts: ["CBZ"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/convert/ebook/pdf": {
    accepts: ["EBOOK"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/convert/eml/pdf": {
    accepts: ["EMAIL"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/convert/file/pdf": {
    accepts: ["ANY"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/convert/html/pdf": {
    accepts: ["HTML", "ZIP"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/convert/img/pdf": {
    accepts: ["IMAGE"],
    produces: "PDF",
    arity: "MISO",
  },
  "/api/v1/convert/markdown/pdf": {
    accepts: ["MARKDOWN", "ZIP"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/convert/pdf/cbr": {
    accepts: ["PDF"],
    produces: "CBR",
    arity: "SISO",
  },
  "/api/v1/convert/pdf/cbz": {
    accepts: ["PDF"],
    produces: "CBZ",
    arity: "SISO",
  },
  "/api/v1/convert/pdf/csv": {
    accepts: ["PDF"],
    produces: "CSV",
    arity: "SIMO",
  },
  "/api/v1/convert/pdf/epub": {
    accepts: ["PDF"],
    produces: "EBOOK",
    arity: "SISO",
  },
  "/api/v1/convert/pdf/html": {
    accepts: ["PDF"],
    produces: "ZIP",
    arity: "SISO",
  },
  "/api/v1/convert/pdf/img": {
    accepts: ["PDF"],
    produces: "IMAGE",
    arity: "SIMO",
    cases: [
      {
        when: [{ param: "singleOrMultiple", matches: ["single"] }],
        produces: "IMAGE",
        arity: "SISO",
      },
    ],
  },
  "/api/v1/convert/pdf/markdown": {
    accepts: ["PDF"],
    produces: "MARKDOWN",
    arity: "SISO",
  },
  "/api/v1/convert/pdf/pdfa": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/convert/pdf/presentation": {
    accepts: ["PDF"],
    produces: "PPT",
    arity: "SISO",
  },
  "/api/v1/convert/pdf/text": {
    accepts: ["PDF"],
    produces: "TEXT",
    arity: "SISO",
    cases: [
      {
        when: [{ param: "outputFormat", matches: ["rtf"] }],
        produces: "WORD",
        arity: "SISO",
      },
    ],
  },
  "/api/v1/convert/pdf/vector": {
    accepts: ["PDF"],
    produces: "IMAGE",
    arity: "SISO",
    cases: [
      {
        when: [{ param: "outputFormat", matches: ["ps"] }],
        produces: "POSTSCRIPT",
        arity: "SISO",
      },
      {
        when: [{ param: "outputFormat", matches: ["pcl"] }],
        produces: "PCL",
        arity: "SISO",
      },
      {
        when: [{ param: "outputFormat", matches: ["xps"] }],
        produces: "XPS",
        arity: "SISO",
      },
    ],
  },
  "/api/v1/convert/pdf/word": {
    accepts: ["PDF"],
    produces: "WORD",
    arity: "SISO",
  },
  "/api/v1/convert/pdf/xlsx": {
    accepts: ["PDF"],
    produces: "EXCEL",
    arity: "SISO",
  },
  "/api/v1/convert/pdf/xml": {
    accepts: ["PDF"],
    produces: "XML",
    arity: "SISO",
  },
  "/api/v1/convert/svg/pdf": {
    accepts: ["IMAGE"],
    produces: "PDF",
    arity: "MIMO",
    cases: [
      {
        when: [{ param: "combineIntoSinglePdf", matches: ["true"] }],
        produces: "PDF",
        arity: "MISO",
      },
    ],
  },
  "/api/v1/convert/url/pdf": {
    accepts: ["NONE"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/convert/vector/pdf": {
    accepts: ["POSTSCRIPT"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/filter/filter-contains-image": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/filter/filter-contains-text": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/filter/filter-file-size": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/filter/filter-page-count": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/filter/filter-page-rotation": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/filter/filter-page-size": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/booklet-imposition": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/crop": { accepts: ["PDF"], produces: "PDF", arity: "SISO" },
  "/api/v1/general/edit-table-of-contents": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/edit-text": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/extract-bookmarks": {
    accepts: ["PDF"],
    produces: "JSON",
    arity: "SISO",
  },
  "/api/v1/general/merge-pdfs": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "MISO",
  },
  "/api/v1/general/multi-page-layout": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/overlay-pdfs": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "MISO",
  },
  "/api/v1/general/pdf-to-single-page": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/rearrange-pages": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/remove-image-pdf": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/remove-pages": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/rotate-pdf": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/scale-pages": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/general/split-by-size-or-count": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SIMO",
  },
  "/api/v1/general/split-for-poster-print": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SIMO",
  },
  "/api/v1/general/split-pages": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SIMO",
  },
  "/api/v1/general/split-pdf-by-chapters": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SIMO",
  },
  "/api/v1/general/split-pdf-by-sections": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SIMO",
  },
  "/api/v1/misc/add-attachments": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/add-comments": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/add-image": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/add-page-numbers": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/add-stamp": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/auto-rename": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/auto-rotate-pdf": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
    cases: [
      {
        when: [{ param: "dryRun", matches: ["true"] }],
        produces: "JSON",
        arity: "SISO",
      },
    ],
  },
  "/api/v1/misc/auto-split-pdf": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SIMO",
  },
  "/api/v1/misc/compress-pdf": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/decompress-pdf": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/delete-attachment": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/extract-attachments": {
    accepts: ["PDF"],
    produces: "ZIP",
    arity: "SISO",
  },
  "/api/v1/misc/extract-image-scans": {
    accepts: ["PDF"],
    produces: "IMAGE",
    arity: "SIMO",
  },
  "/api/v1/misc/extract-images": {
    accepts: ["PDF"],
    produces: "IMAGE",
    arity: "SIMO",
  },
  "/api/v1/misc/flatten": { accepts: ["PDF"], produces: "PDF", arity: "SISO" },
  "/api/v1/misc/list-attachments": {
    accepts: ["PDF"],
    produces: "JSON",
    arity: "SISO",
  },
  "/api/v1/misc/ocr-pdf": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
    cases: [
      {
        when: [{ param: "sidecar", matches: ["true"] }],
        produces: "ZIP",
        arity: "SISO",
      },
    ],
  },
  "/api/v1/misc/remove-blanks": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SIMO",
  },
  "/api/v1/misc/rename-attachment": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/repair": { accepts: ["PDF"], produces: "PDF", arity: "SISO" },
  "/api/v1/misc/replace-invert-pdf": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/scanner-effect": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/show-javascript": {
    accepts: ["PDF"],
    produces: "JAVASCRIPT",
    arity: "SISO",
  },
  "/api/v1/misc/unlock-pdf-forms": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/misc/update-metadata": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/security/add-password": {
    accepts: ["PDF"],
    produces: "PDF_ENCRYPTED",
    arity: "SISO",
    cases: [
      {
        when: [
          { param: "password", matches: [""] },
          { param: "ownerPassword", matches: [""] },
        ],
        produces: "PDF",
        arity: "SISO",
      },
    ],
  },
  "/api/v1/security/add-watermark": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/security/auto-redact": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/security/cert-sign": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/security/get-info-on-pdf": {
    accepts: ["PDF"],
    produces: "JSON",
    arity: "SISO",
  },
  "/api/v1/security/redact": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/security/redact-execute": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/security/remove-cert-sign": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/security/remove-password": {
    accepts: ["PDF", "PDF_ENCRYPTED"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/security/sanitize-pdf": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/security/timestamp-pdf": {
    accepts: ["PDF"],
    produces: "PDF",
    arity: "SISO",
  },
  "/api/v1/security/validate-signature": {
    accepts: ["PDF"],
    produces: "JSON",
    arity: "SISO",
  },
  "/api/v1/security/verify-pdf": {
    accepts: ["PDF"],
    produces: "JSON",
    arity: "SISO",
  },
};

/** The declaration for an endpoint, or undefined when it declares none. */
export function toolIOFor(
  operation: string,
  table: ToolIOTable = TOOL_IO,
): ToolIOSpec | undefined {
  // The table's own keys are the valid set, so a hasOwn guard is the narrowing.
  return Object.hasOwn(table, operation)
    ? table[operation as ToolEndpoint]
    : undefined;
}
