export type NavKey =
  | 'preferences'
  | 'notifications'
  | 'connections'
  | 'general'
  | 'people'
  | 'teams'
  | 'security'
  | 'identity'
  | 'plan'
  | 'payments'
  | 'requests'
  | 'developer'
  | 'api-keys'
  | 'hotkeys'
  | 'adminGeneral'
  | 'adminSecurity'
  | 'adminConnections'
  | 'adminPrivacy'
  | 'adminDatabase'
  | 'adminAdvanced'
  | 'adminLegal'
  | 'adminPremium'
  | 'adminFeatures'
  | 'adminPlan'
  | 'adminAudit'
  | 'adminUsage'
  | 'adminEndpoints';


  // some of these are not used yet, but appear in figma designs