import { test, expect } from "@app/tests/helpers/stub-test-base";
import {
  DisplayTransform,
  type DisplayTransformData,
} from "@app/tools/pdfTextEditor/v2/model/DisplayTransform";
import path from "path";

/**
 * Regression for the CropBox/rotation positioning bug (root-caused on
 * spirit-sx-user-guide.pdf, which is NEVER committed). These use SYNTHETIC
 * fixtures generated by generate-cropbox-fixtures.py:
 *
 *  - cropbox-control.pdf  : CropBox == MediaBox, /Rotate 0  (must be identity)
 *  - cropbox-offset.pdf   : CropBox origin (50,30), 300x350 visible page
 *  - cropbox-rotate90.pdf : same crop + /Rotate 90 (displayed 350x300)
 *
 * The page object stores a DisplayTransform read from the real PDF's CropBox +
 * rotation; the model stays in raw PDF (MediaBox) space; the overlay maps raw
 * coords to the rendered (cropped/rotated) bitmap. Each fixture draws "Hi" at
 * user-space baseline (60,350).
 */

interface Probe {
  width: number;
  height: number;
  runCount: number;
  matrixE: number;
  matrixF: number;
  boundsX: number;
  display: DisplayTransformData;
}

async function load(
  page: import("@playwright/test").Page,
  name: string,
): Promise<Probe> {
  await page.goto("/pdf-text-editor?charcodeStrategy=content-stream", {
    waitUntil: "domcontentloaded",
  });
  await expect(page.getByTestId("v2-root")).toBeVisible({ timeout: 30_000 });
  await page
    .locator('[data-testid="v2-file-input"]')
    .setInputFiles(path.join(__dirname, `../test-fixtures/${name}.pdf`));
  await expect(page.getByTestId("v2-page-0")).toBeVisible({ timeout: 30_000 });
  await page.waitForTimeout(800);
  return page.evaluate(() => {
    const s = (
      window as unknown as {
        __v2_editor_store: {
          doc: {
            page: (i: number) => {
              width: number;
              height: number;
              runs: Array<{
                bounds: { x: number };
                matrix: { e: number; f: number };
              }>;
              display: Probe["display"];
            };
          };
        };
      }
    ).__v2_editor_store;
    const pg = s.doc.page(0);
    const r = pg.runs[0];
    return {
      width: pg.width,
      height: pg.height,
      runCount: pg.runs.length,
      matrixE: r?.matrix.e,
      matrixF: r?.matrix.f,
      boundsX: r?.bounds.x,
      display: pg.display,
    };
  }) as Promise<Probe>;
}

test("control fixture (CropBox==MediaBox) yields an identity transform", async ({
  page,
}) => {
  const p = await load(page, "cropbox-control");
  expect(p.width).toBe(400);
  expect(p.height).toBe(400);
  expect(p.display.cropLeft).toBe(0);
  expect(p.display.cropBottom).toBe(0);
  expect(p.display.rotate).toBe(0);
  const t = DisplayTransform.fromData(p.display);
  expect(t.isIdentity).toBe(true);
  // Model is raw; with identity the display position equals the raw position.
  expect(t.apply(p.boundsX, p.matrixF)).toEqual({ x: p.boundsX, y: p.matrixF });
});

test("CropBox-offset fixture: page sized to CropBox, model raw, overlay offset", async ({
  page,
}) => {
  const p = await load(page, "cropbox-offset");
  // page dims are the CropBox (visible) size, not the square MediaBox.
  expect(p.width).toBe(300);
  expect(p.height).toBe(350);
  // The transform read the real PDF's CropBox origin.
  expect(p.display.cropLeft).toBe(50);
  expect(p.display.cropBottom).toBe(30);
  expect(p.display.rotate).toBe(0);
  // The MODEL stays in raw PDF (MediaBox) space - Td(60,350) baseline intact.
  expect(p.matrixE).toBeCloseTo(60, 1);
  expect(p.matrixF).toBeCloseTo(350, 1);
  // The display anchor subtracts the CropBox origin: raw (~61.8,350) -> (~11.8,320).
  const t = DisplayTransform.fromData(p.display);
  const disp = t.apply(p.boundsX, p.matrixF);
  expect(disp.x).toBeCloseTo(p.boundsX - 50, 3);
  expect(disp.y).toBeCloseTo(320, 3);
  // ...and the anchor now lands INSIDE the visible page (the bug put it past
  // the right edge / above the top because the +50/-30 offset wasn't removed).
  expect(disp.x).toBeGreaterThanOrEqual(0);
  expect(disp.x).toBeLessThanOrEqual(p.width);
  expect(disp.y).toBeGreaterThanOrEqual(0);
  expect(disp.y).toBeLessThanOrEqual(p.height);
  // Teeth: the un-transformed (pre-fix) x carried the +50 crop offset.
  expect(p.boundsX).toBeGreaterThan(disp.x + 40);
});

test("CropBox + Rotate 90 fixture: dims swap, rotation in the transform, model raw", async ({
  page,
}) => {
  const p = await load(page, "cropbox-rotate90");
  // /Rotate 90 swaps the displayed page dimensions.
  expect(p.width).toBe(350);
  expect(p.height).toBe(300);
  expect(p.display.rotate).toBe(1);
  expect(p.display.cropLeft).toBe(50);
  expect(p.display.cropBottom).toBe(30);
  // 90 CW affine is a proper rotation (det +1): a=0,b=-1,c=1,d=0.
  expect([p.display.a, p.display.b, p.display.c, p.display.d]).toEqual([
    0, -1, 1, 0,
  ]);
  expect(
    p.display.a * p.display.d - p.display.b * p.display.c,
    "rotation must be det +1, not a reflection",
  ).toBeCloseTo(1, 9);
  // Model still raw.
  expect(p.matrixF).toBeCloseTo(350, 1);
  // The display anchor lands inside the rotated visible page.
  const t = DisplayTransform.fromData(p.display);
  const disp = t.apply(p.boundsX, p.matrixF);
  expect(disp.x).toBeGreaterThanOrEqual(0);
  expect(disp.x).toBeLessThanOrEqual(p.width);
  expect(disp.y).toBeGreaterThanOrEqual(0);
  expect(disp.y).toBeLessThanOrEqual(p.height);
});

test("CropBox-offset: the rendered glyph pixels overlap the run overlay box", async ({
  page,
}) => {
  // End-to-end: the PDFium-rendered bitmap (CropBox-cropped) and the HTML
  // overlay (positioned via the transform) must agree on where "Hi" sits.
  await page.goto("/pdf-text-editor?charcodeStrategy=content-stream", {
    waitUntil: "domcontentloaded",
  });
  await expect(page.getByTestId("v2-root")).toBeVisible({ timeout: 30_000 });
  await page
    .locator('[data-testid="v2-file-input"]')
    .setInputFiles(path.join(__dirname, "../test-fixtures/cropbox-offset.pdf"));
  await expect(page.getByTestId("v2-page-0")).toBeVisible({ timeout: 30_000 });
  await page.waitForTimeout(1200);

  const result = await page.evaluate(() => {
    const pageEl = document.querySelector<HTMLElement>(
      '[data-testid="v2-page-0"]',
    )!;
    const canvas = pageEl.querySelector("canvas")!;
    const pageRect = pageEl.getBoundingClientRect();
    const ctx = canvas.getContext("2d")!;
    const img = ctx.getImageData(0, 0, canvas.width, canvas.height);
    // Find the dark-pixel bounding box (the "Hi" glyphs) in canvas px.
    let minX = Infinity,
      minY = Infinity,
      maxX = -Infinity,
      maxY = -Infinity;
    const { data, width, height } = img;
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        const o = (y * width + x) * 4;
        const lum = (data[o] + data[o + 1] + data[o + 2]) / 3;
        if (lum < 128 && data[o + 3] > 32) {
          if (x < minX) minX = x;
          if (x > maxX) maxX = x;
          if (y < minY) minY = y;
          if (y > maxY) maxY = y;
        }
      }
    }
    // Canvas is rendered at devicePixelRatio*scale; normalise to CSS px by the
    // canvas's own client size.
    const sx = canvas.clientWidth / canvas.width;
    const sy = canvas.clientHeight / canvas.height;
    const glyph = {
      left: minX * sx,
      top: minY * sy,
      right: maxX * sx,
      bottom: maxY * sy,
    };
    const overlay = document
      .querySelector<HTMLElement>('[data-testid^="v2-run-"]')!
      .getBoundingClientRect();
    const ov = {
      left: overlay.left - pageRect.left,
      top: overlay.top - pageRect.top,
      right: overlay.right - pageRect.left,
      bottom: overlay.bottom - pageRect.top,
    };
    return { glyph, ov, found: maxX >= minX };
  });

  expect(result.found).toBe(true);
  // The overlay box and the rendered-glyph box must overlap (loose: the
  // overlay box is taller than the glyph ink, but they must not be disjoint -
  // a pre-fix overlay would sit ~50px to the right and ~30px too high).
  const overlaps =
    result.ov.left <= result.glyph.right + 8 &&
    result.ov.right >= result.glyph.left - 8 &&
    result.ov.top <= result.glyph.bottom + 12 &&
    result.ov.bottom >= result.glyph.top - 12;
  expect(
    overlaps,
    `overlay ${JSON.stringify(result.ov)} must overlap glyph ${JSON.stringify(result.glyph)}`,
  ).toBe(true);
});
