worker_processes 1;
events { worker_connections 1024; }

http {
    upstream uno_pool {
        least_conn;
        server unoserver-1:2003 max_fails=1 fail_timeout=10s;
        server unoserver-2:2003 max_fails=1 fail_timeout=10s;
        server unoserver-3:2003 max_fails=1 fail_timeout=10s;
    }

    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_buffering off;

    server {
        listen 2003;

        location / {
            proxy_pass http://uno_pool;

            proxy_http_version 1.1;
            proxy_connect_timeout 5s;
            proxy_send_timeout 1830s;
            proxy_read_timeout 1830s;
            proxy_next_upstream off;
        }
    }
}
