name: Close stale issues

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    if: ${{ vars.CI_PROFILE != 'lite' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: 30 days stale issues
        uses: actions/stale@997185467fa4f803885201cee163a9f38240193d # v10.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: >
            This issue has been automatically marked as stale because it has had no recent activity.
            It will be closed if no further activity occurs. Thank you for your contributions.
          close-issue-message: >
            This issue has been automatically closed because it has had no recent activity after being marked as stale.
            Please reopen if you need further assistance.
          stale-issue-label: "Stale"
          remove-stale-when-updated: true
          only-issue-labels: "more-info-needed"
          days-before-pr-stale: -1 # Prevents PRs from being marked as stale
          days-before-pr-close: -1 # Prevents PRs from being closed
          start-date: "2024-07-06T00:00:00Z" # ISO 8601 Format
